'use client';

/**
 * BuildingVerticalSetupForm — ADR-451 «Quick Setup» (Revit-grade building setup).
 *
 * One step that generates the whole storey stack (basement → ground → upper
 * floors) with consistent elevations, plus the building-level foundation datum
 * (`hasFoundation` + `foundationDepth`). Incremental per-floor editing stays in the
 * «Όροφοι» table — this is only the fast-path bootstrap.
 *
 * SSoT: floors are created through the same `createFloorWithPolicy` path as the
 * inline form (server reconcile keeps `height` derived from `elevation`); the
 * stack itself comes from the pure {@link generateFloorStack} generator.
 *
 * @module components/building-management/tabs/BuildingVerticalSetupForm
 * @see docs/centralized-systems/reference/adrs/ADR-451-building-vertical-setup-floor-ssot.md
 */

import { useCallback, useMemo, useState } from 'react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Spinner } from '@/components/ui/spinner';
import { Check, X, AlertTriangle, Building2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useTranslation } from '@/i18n/hooks/useTranslation';
import { useSemanticColors } from '@/ui-adapters/react/useSemanticColors';
import { getStatusColor } from '@/lib/design-system';
import { formatFloorLabel } from '@/lib/intl-domain';
import { createFloorWithPolicy } from '@/services/floor-mutation-gateway';
import { updateBuildingWithPolicy } from '@/services/building/building-mutation-gateway';
import { createFloor } from '@/services/factories/floor.factory';
import { useNotifications } from '@/providers/NotificationProvider';
import {
  generateFloorStack,
  DEFAULT_TYPICAL_STOREY_HEIGHT_M,
} from './building-vertical-setup';
import { DEFAULT_BUILDING_FOUNDATION_DEPTH_M } from '@/types/building/elevation.schemas';

interface FloorMutationResponse {
  floorId?: string;
  data?: { floorId: string };
}

export interface BuildingVerticalSetupFormProps {
  buildingId: string;
  projectId?: string;
  /** Existing floor numbers — generation skips these (idempotent, no 409). */
  existingFloorNumbers: ReadonlySet<number>;
  /** Called after the stack is created so the parent refreshes the list. */
  onComplete: () => void;
  onCancel: () => void;
}

function parseCount(value: string): number {
  const n = parseInt(value, 10);
  return Number.isFinite(n) && n > 0 ? n : 0;
}

export function BuildingVerticalSetupForm({
  buildingId,
  projectId,
  existingFloorNumbers,
  onComplete,
  onCancel,
}: BuildingVerticalSetupFormProps) {
  const { t } = useTranslation(['building', 'building-tabs']);
  const { success, error: notifyError } = useNotifications();
  const colors = useSemanticColors();

  const [basements, setBasements] = useState('0');
  const [uppers, setUppers] = useState('2');
  const [typicalHeight, setTypicalHeight] = useState(DEFAULT_TYPICAL_STOREY_HEIGHT_M.toFixed(2));
  const [hasFoundation, setHasFoundation] = useState(true);
  const [foundationDepth, setFoundationDepth] = useState(DEFAULT_BUILDING_FOUNDATION_DEPTH_M.toFixed(2));
  const [busy, setBusy] = useState(false);

  const stack = useMemo(
    () => generateFloorStack({
      basementCount: parseCount(basements),
      upperCount: parseCount(uppers),
      typicalHeightM: parseFloat(typicalHeight) || DEFAULT_TYPICAL_STOREY_HEIGHT_M,
    }),
    [basements, uppers, typicalHeight],
  );

  // Idempotent (Revit-grade): only create storeys that don't already exist —
  // never crash on a duplicate number, never leave a half-built stack.
  const newSpecs = useMemo(
    () => stack.filter((s) => !existingFloorNumbers.has(s.number)),
    [stack, existingFloorNumbers],
  );
  const skippedCount = stack.length - newSpecs.length;

  const handleGenerate = useCallback(async () => {
    setBusy(true);
    try {
      // Create storeys low → high so the server reconcile sees a consistent chain.
      for (const spec of newSpecs) {
        const floor = createFloor({
          number: spec.number,
          name: formatFloorLabel(spec.number),
          buildingId,
          elevation: spec.elevation,
          height: spec.height,
          ...(projectId ? { projectId } : {}),
        });
        const payload: Record<string, unknown> = {
          number: floor.number,
          name: floor.name,
          kind: floor.kind,
          longName: floor.longName,
          nameAutoGenerated: floor.nameAutoGenerated,
          longNameAutoGenerated: floor.longNameAutoGenerated,
          finishThickness: floor.finishThickness,
          buildingId,
        };
        if (floor.elevation !== undefined) payload.elevation = floor.elevation;
        if (floor.height !== null && floor.height !== undefined) payload.height = floor.height;
        if (projectId) payload.projectId = projectId;
        await createFloorWithPolicy<FloorMutationResponse>({ payload });
      }

      // Foundation = auto-derived datum (building-level), NOT a counted storey.
      await updateBuildingWithPolicy({
        buildingId,
        updates: {
          hasFoundation,
          foundationDepth: hasFoundation ? parseFloat(foundationDepth) || 0 : 0,
        },
      });

      const created = newSpecs.length;
      if (created === 0) {
        success(t('tabs.floors.quickSetup.allExist'));
      } else if (skippedCount > 0) {
        success(t('tabs.floors.quickSetup.successSkipped', { created, skipped: skippedCount }));
      } else {
        success(t('tabs.floors.quickSetup.success', { count: created }));
      }
      onComplete();
    } catch (err) {
      const msg = err instanceof Error ? err.message : '';
      notifyError(t('tabs.floors.quickSetup.error') + (msg ? `: ${msg}` : ''));
    } finally {
      setBusy(false);
    }
  }, [newSpecs, skippedCount, buildingId, projectId, hasFoundation, foundationDepth, t, success, notifyError, onComplete]);

  return (
    <section className="flex flex-col gap-3 rounded-lg border border-border bg-muted/30 p-3" role="group">
      <header className="flex items-center gap-2 text-sm font-semibold">
        <Building2 className="h-4 w-4 text-primary" />
        {t('tabs.floors.quickSetup.title')}
      </header>

      {skippedCount > 0 && (
        <p className={cn('flex items-center gap-1.5 rounded-md border px-3 py-1.5 text-xs', getStatusColor('warning', 'border'), getStatusColor('warning', 'text'))}>
          <AlertTriangle className="h-3.5 w-3.5 shrink-0" />
          {t('tabs.floors.quickSetup.existingWarning', { skipped: skippedCount })}
        </p>
      )}

      <section className="grid grid-cols-2 gap-3 sm:grid-cols-3">
        <fieldset className="flex flex-col gap-1">
          <label className={cn('text-xs font-medium', colors.text.muted)}>{t('tabs.floors.quickSetup.basements')}</label>
          <Input type="number" min="0" value={basements} onChange={(e) => setBasements(e.target.value)} className="h-9" disabled={busy} />
        </fieldset>
        <fieldset className="flex flex-col gap-1">
          <label className={cn('text-xs font-medium', colors.text.muted)}>{t('tabs.floors.quickSetup.uppers')}</label>
          <Input type="number" min="0" value={uppers} onChange={(e) => setUppers(e.target.value)} className="h-9" disabled={busy} />
        </fieldset>
        <fieldset className="flex flex-col gap-1">
          <label className={cn('text-xs font-medium', colors.text.muted)}>{t('tabs.floors.quickSetup.typicalHeight')}</label>
          <Input type="number" step="0.01" min="0.1" value={typicalHeight} onChange={(e) => setTypicalHeight(e.target.value)} className="h-9" disabled={busy} />
        </fieldset>
      </section>

      <section className="flex flex-wrap items-end gap-3">
        <label className="flex items-center gap-2 text-xs font-medium">
          <input type="checkbox" checked={hasFoundation} onChange={(e) => setHasFoundation(e.target.checked)} disabled={busy} className="h-4 w-4 accent-[hsl(var(--primary))]" />
          {t('tabs.floors.quickSetup.hasFoundation')}
        </label>
        {hasFoundation && (
          <fieldset className="flex flex-col gap-1">
            <label className={cn('text-xs font-medium', colors.text.muted)}>{t('tabs.floors.quickSetup.foundationDepth')}</label>
            <Input type="number" step="0.01" min="0" value={foundationDepth} onChange={(e) => setFoundationDepth(e.target.value)} className="h-9 w-28" disabled={busy} />
          </fieldset>
        )}
      </section>

      <footer className="flex items-center justify-between">
        <p className={cn('text-xs', colors.text.muted)}>{t('tabs.floors.quickSetup.preview', { count: newSpecs.length })}</p>
        <nav className="flex gap-1">
          <Button type="button" size="sm" className="h-9" onClick={handleGenerate} disabled={busy || newSpecs.length === 0}>
            {busy ? <Spinner size="small" color="inherit" /> : <Check className="mr-1 h-4 w-4" />}
            {t('tabs.floors.quickSetup.generate')}
          </Button>
          <Button type="button" variant="ghost" size="sm" className="h-9" onClick={onCancel} disabled={busy}>
            <X className="h-4 w-4" />
          </Button>
        </nav>
      </footer>
    </section>
  );
}

export default BuildingVerticalSetupForm;
