import type { ViewerProps, PublicViewerHookShape } from '../../property-management/types/publicViewer';

export function buildViewerProps(h: PublicViewerHookShape): ViewerProps {
  return {
    properties: h.properties,
    setProperties: h.setProperties,
    selectedPropertyIds: h.selectedPropertyIds,
    hoveredPropertyId: h.hoveredPropertyId,
    selectedFloorId: h.selectedFloorId,
    onHoverProperty: h.onHoverProperty,
    onSelectFloor: h.onSelectFloor,
    undo: h.undo,
    redo: h.redo,
    canUndo: h.canUndo,
    canRedo: h.canRedo,
    setSelectedProperties: h.setSelectedProperties,
    floors: h.floors,
    currentFloor: h.currentFloor,
    activeTool: h.activeTool,
    setActiveTool: h.setActiveTool,
    showGrid: h.showGrid,
    setShowGrid: h.setShowGrid,
    snapToGrid: h.snapToGrid,
    setSnapToGrid: h.setSnapToGrid,
    gridSize: h.gridSize,
    setGridSize: h.setGridSize,
    showMeasurements: h.showMeasurements,
    setShowMeasurements: h.setShowMeasurements,
    scale: h.scale,
    setScale: h.setScale,
    handlePolygonSelect: h.handlePolygonSelect,
    handlePolygonCreated: h.handlePolygonCreated,
    handlePolygonUpdated: h.handlePolygonUpdated,
    handleDuplicate: h.handleDuplicate,
    handleDelete: h.handleDelete,
    suggestionToDisplay: h.suggestionToDisplay,
    connections: h.connections,
    setConnections: h.setConnections,
    groups: h.groups,
    setGroups: h.setGroups,
    isConnecting: h.isConnecting,
    setIsConnecting: h.setIsConnecting,
    firstConnectionPoint: h.firstConnectionPoint,
    setFirstConnectionPoint: h.setFirstConnectionPoint,
    isReadOnly: true, // δημόσια προβολή
  };
}
