/**
 * =============================================================================
 * FIRESTORE BOUNDARY CONTRACTS - SERVER-ONLY
 * =============================================================================
 *
 * These types define the exact shape of documents stored in Firestore.
 * Use these for setDoc/updateDoc operations - NO ad-hoc objects!
 *
 * @module server/types/conversations.firestore
 * @enterprise ADR-029 - Omnichannel Conversation Model
 * @server-only Uses FirebaseFirestore.Timestamp - do NOT import in client bundles
 */

import type { Timestamp } from 'firebase-admin/firestore';
import type { CommunicationChannel } from '@/types/communications';
import type { ConversationStatus, MessageDirection, DeliveryStatus, IdentityProvider, MessageAttachment } from '@/types/conversations';
import type { ParticipantRole, SenderType } from '@/config/domain-constants';

// ============================================================================
// CONVERSATION DOCUMENT (Firestore)
// ============================================================================

/**
 * Conversation document as stored in Firestore
 * @enterprise Use this type for all CONVERSATIONS collection writes
 * @usage const doc = { ... } satisfies ConversationDocument;
 */
export interface ConversationDocument {
  /** Document ID (generated by generateConversationId) */
  id: string;

  /** 🏢 TENANT ISOLATION: Company ID for multi-tenant filtering (AUTHZ Phase 2) */
  companyId: string;

  /** Communication channel */
  channel: CommunicationChannel;

  /** Conversation participants */
  participants: ConversationParticipantDoc[];

  /** Current status */
  status: ConversationStatus;

  /** Tags for categorization */
  tags: string[];

  /** Total message count */
  messageCount: number;

  /** Unread message count */
  unreadCount: number;

  /** Last message preview */
  lastMessage: {
    content: string;
    direction: MessageDirection;
    timestamp: Timestamp;
  };

  /** Audit trail */
  audit: {
    createdBy: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
  };
}

/**
 * Conversation participant sub-document
 * @enterprise Uses centralized ParticipantRole type from domain-constants
 */
export interface ConversationParticipantDoc {
  identityId: string;
  isInternal: boolean;
  displayName: string;
  role: ParticipantRole;
  joinedAt: Timestamp;
}

// ============================================================================
// MESSAGE DOCUMENT (Firestore)
// ============================================================================

/**
 * Message document as stored in Firestore
 * @enterprise Use this type for all MESSAGES collection writes
 * @usage const doc = { ... } satisfies MessageDocument;
 */
export interface MessageDocument {
  /** Document ID (generated by generateMessageDocId) */
  id: string;

  /** 🏢 TENANT ISOLATION: Company ID for multi-tenant filtering (AUTHZ Phase 2) */
  companyId: string;

  /** Parent conversation ID */
  conversationId: string;

  /** Message direction */
  direction: MessageDirection;

  /** Channel used */
  channel: CommunicationChannel;

  /** Sender identifier */
  senderId: string;

  /** Sender display name */
  senderName: string;

  /** Sender type - uses centralized SenderType from domain-constants */
  senderType: SenderType;

  /** Message content */
  content: {
    text?: string;
    /** 🏢 ADR-055: Attachments array for media messages */
    attachments?: MessageAttachment[];
  };

  /** Original provider message ID */
  providerMessageId: string;

  /** Delivery status */
  deliveryStatus: DeliveryStatus;

  /** Provider-specific metadata */
  providerMetadata: {
    platform: string;
    chatId: string;
    userName?: string;
  };

  /** Timestamps */
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// ============================================================================
// EXTERNAL IDENTITY DOCUMENT (Firestore)
// ============================================================================

/**
 * External identity document as stored in Firestore
 * @enterprise Use this type for all EXTERNAL_IDENTITIES collection writes
 * @usage const doc = { ... } satisfies ExternalIdentityDocument;
 */
export interface ExternalIdentityDocument {
  /** Document ID (generated by generateExternalIdentityId) */
  id: string;

  /** Provider type */
  provider: IdentityProvider;

  /** External user ID (the raw ID from provider) */
  externalUserId: string;

  /** Display name */
  displayName: string;

  /** Username if available */
  username?: string;

  /** Verification status */
  verified: boolean;

  /** Consent preferences */
  consent: {
    marketing: boolean;
    transactional: boolean;
  };

  /** Timestamps */
  createdAt: Timestamp;
  updatedAt: Timestamp;
  lastSeenAt: Timestamp;
}

// ============================================================================
// LEGACY COMMUNICATION DOCUMENT (Firestore)
// ============================================================================

/**
 * Legacy communication document (for backward compatibility)
 * @enterprise Use this type for COMMUNICATIONS collection writes
 * @usage const doc = { ... } satisfies LegacyCommunicationDocument;
 */
export interface LegacyCommunicationDocument {
  type: string;
  direction: MessageDirection;
  channel: string;
  from: string;
  to: string;
  content: string;
  status: string;
  entityType: string;
  entityId: string | null;
  externalId: string;
  conversationId: string;
  metadata: {
    userName: string;
    platform: string;
    chatId: string;
  };
  createdAt: Timestamp;
  updatedAt: Timestamp;
}
