import 'server-only';

import {
  getAdminFirestore,
  SERVER_COLLECTIONS,
} from '@/server/admin/admin-guards';

/**
 * ENTERPRISE: Admin Building Templates Service
 *
 * Server-only service for managing building templates from Firestore.
 * Uses Firebase Admin SDK - NOT client SDK.
 *
 * All enterprise data (legalInfo, technicalSpecs, financialData) must be
 * stored in templates in Firestore, NOT generated by code.
 *
 * @serverOnly This module must only be used in server-side code
 * @author Enterprise Architecture Team
 */

// ============================================================================
// TYPES
// ============================================================================

/**
 * Building payload containing all building data
 * Enterprise fields (legalInfo, technicalSpecs, financialData) are optional
 * and must be stored in Firestore templates, NOT hardcoded
 */
export interface BuildingPayload {
  name: string;
  description: string;
  address: string;
  city: string;
  totalArea: number;
  builtArea: number;
  floors: number;
  units: number;
  status: string;
  progress: number;
  startDate: string;
  completionDate: string;
  totalValue: number;
  category: string;
  features: string[];
  // Enterprise fields - stored in DB, NOT generated
  legalInfo?: {
    permitNumber?: string;
    permitDate?: string;
    buildingCode?: string;
    zoningCategory?: string;
    landUsePermit?: string;
    environmentalCertification?: string;
  };
  technicalSpecs?: {
    structuralType?: string;
    foundationType?: string;
    elevatorCount?: number;
    parkingSpaces?: number;
    energyClass?: string;
    seismicZone?: string;
  };
  financialData?: {
    estimatedCost?: number;
    actualCost?: number;
    pricePerSqm?: number;
    taxValue?: number;
    insuranceValue?: number;
  };
}

/**
 * Building template as stored in admin_building_templates collection
 */
export interface BuildingTemplate {
  id: string;
  templateKey: string;
  companyId: string;
  status: 'active' | 'inactive' | 'draft';
  projectId?: string;
  buildingPayload: BuildingPayload;
  createdAt: unknown;
  updatedAt: unknown;
}

// ============================================================================
// TEMPLATE QUERIES
// ============================================================================

/**
 * List all active templates for a company
 * Used by seed/populate routes to get templates from Firestore
 *
 * @param companyId - Company ID to filter by
 * @returns Array of active BuildingTemplates
 */
export async function listTemplatesForCompany(
  companyId: string
): Promise<BuildingTemplate[]> {
  const db = getAdminFirestore();

  const snapshot = await db
    .collection(SERVER_COLLECTIONS.ADMIN_BUILDING_TEMPLATES)
    .where('companyId', '==', companyId)
    .where('status', '==', 'active')
    .get();

  return snapshot.docs.map((doc) => ({
    id: doc.id,
    ...doc.data(),
  })) as BuildingTemplate[];
}

// ============================================================================
// IDEMPOTENCY CHECKS
// ============================================================================

/**
 * Check if a building already exists for a specific template
 * Used for idempotent seed/populate operations
 *
 * @param companyId - Company ID to filter by
 * @param templateId - Source template ID to check
 * @returns true if building exists, false otherwise
 */
export async function buildingExistsForTemplate(
  companyId: string,
  templateId: string
): Promise<boolean> {
  const db = getAdminFirestore();

  const snapshot = await db
    .collection(SERVER_COLLECTIONS.BUILDINGS)
    .where('companyId', '==', companyId)
    .where('sourceTemplateId', '==', templateId)
    .limit(1)
    .get();

  return !snapshot.empty;
}

/**
 * Get the ID of an existing building created from a template
 * Used to return existing building ID when skipping duplicate creation
 *
 * @param companyId - Company ID to filter by
 * @param templateId - Source template ID to find
 * @returns Building ID if exists, null otherwise
 */
export async function getExistingBuildingId(
  companyId: string,
  templateId: string
): Promise<string | null> {
  const db = getAdminFirestore();

  const snapshot = await db
    .collection(SERVER_COLLECTIONS.BUILDINGS)
    .where('companyId', '==', companyId)
    .where('sourceTemplateId', '==', templateId)
    .limit(1)
    .get();

  if (snapshot.empty) {
    return null;
  }

  return snapshot.docs[0].id;
}
