import type { ParkingSpotTemplate, ParkingTargetBuilding } from './parking-seed-types';

export const TARGET_BUILDING: ParkingTargetBuilding = {
  id: 'G8kMxQ2pVwN5jR7tE1sA',
  name: 'ΚΤΙΡΙΟ Α - Παλαιολόγου',
  projectId: 'xL2nV4bC6mZ8kJ9hG1fQ',
};

export const PARKING_PREVIEW_ID = 'park_xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx (θα δημιουργηθεί)';

export const PARKING_TEMPLATES: readonly ParkingSpotTemplate[] = [
  {
    number: 'P-001',
    type: 'standard',
    status: 'available',
    floor: 'Υπόγειο -1',
    location: 'Δεξιά της εισόδου',
    area: 12.5,
    price: 15000,
    notes: 'Εύκολη πρόσβαση από την κεντρική είσοδο',
  },
  {
    number: 'P-002',
    type: 'standard',
    status: 'sold',
    floor: 'Υπόγειο -1',
    location: 'Δεξιά της εισόδου',
    area: 12.5,
    price: 15000,
    notes: 'Πωλήθηκε στον ιδιοκτήτη Α1',
  },
  {
    number: 'P-003',
    type: 'handicapped',
    status: 'available',
    floor: 'Υπόγειο -1',
    location: 'Κοντά στον ανελκυστήρα',
    area: 15.0,
    price: 18000,
    notes: 'Θέση ΑμεΑ με ευρύτερο χώρο',
  },
  {
    number: 'P-004',
    type: 'standard',
    status: 'reserved',
    floor: 'Υπόγειο -1',
    location: 'Αριστερά της εισόδου',
    area: 12.5,
    price: 15000,
    notes: 'Κρατημένη για διαμέρισμα Β1',
  },
  {
    number: 'P-005',
    type: 'electric',
    status: 'available',
    floor: 'Υπόγειο -1',
    location: 'Κοντά στον πίνακα ρεύματος',
    area: 13.0,
    price: 20000,
    notes: 'Με σταθμό φόρτισης ηλεκτρικού οχήματος',
  },
  {
    number: 'P-006',
    type: 'motorcycle',
    status: 'available',
    floor: 'Υπόγειο -1',
    location: 'Γωνία βόρεια',
    area: 5.0,
    price: 5000,
    notes: 'Θέση μηχανής/σκούτερ',
  },
  {
    number: 'P-007',
    type: 'motorcycle',
    status: 'sold',
    floor: 'Υπόγειο -1',
    location: 'Γωνία βόρεια',
    area: 5.0,
    price: 5000,
    notes: 'Θέση μηχανής - πωλήθηκε',
  },
  {
    number: 'P-008',
    type: 'standard',
    status: 'available',
    floor: 'Υπόγειο -2',
    location: 'Κεντρική περιοχή',
    area: 12.5,
    price: 12000,
    notes: 'Υπόγειο -2, χαμηλότερη τιμή',
  },
  {
    number: 'P-009',
    type: 'visitor',
    status: 'available',
    floor: 'Ισόγειο',
    location: 'Μπροστά από την είσοδο',
    area: 14.0,
    price: 0,
    notes: 'Θέση επισκεπτών - κοινόχρηστη',
  },
  {
    number: 'P-010',
    type: 'standard',
    status: 'maintenance',
    floor: 'Υπόγειο -2',
    location: 'Πίσω αριστερά',
    area: 12.5,
    price: 12000,
    notes: 'Υπό συντήρηση - επισκευή δαπέδου',
  },
] as const;
