'use client';

/**
 * 🏢 ADR-233: Shared Entity Code Field Component
 *
 * Reusable field for entity code auto-suggestion with Popover info and validation feedback.
 * Used by: StorageGeneralTab, ParkingGeneralTab, AddStorageDialog, AddParkingDialog
 *
 * @module components/shared/EntityCodeField
 */

import { useEffect, useState } from 'react';
import { Info } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { useEntityCodeSuggestion } from '@/hooks/useEntityCodeSuggestion';
import { isValidEntityCodeFormat } from '@/services/entity-code.service';
import type { ParkingLocationZone } from '@/types/parking';

/** Minimal translation function type compatible with i18next TFunction */
type TranslationFn = {
  (key: string, defaultValue: string): string;
  (key: string, opts: Record<string, unknown>): string;
  (key: string): string;
};

// ============================================================================
// TYPES
// ============================================================================

interface EntityCodeFieldProps {
  /** Current code value */
  value: string;
  /** Called when user changes value */
  onChange: (value: string) => void;
  /** Entity type for code suggestion */
  entityType: 'storage' | 'parking';
  /** Building ID for code suggestion context */
  buildingId: string;
  /** Floor level for code suggestion context */
  floorLevel: number;
  /** Location zone (parking only) */
  locationZone?: ParkingLocationZone;
  /** Label text */
  label: string;
  /** Placeholder when no suggestion available */
  placeholderFallback: string;
  /** Example to show in Popover */
  infoExample: string;
  /** Whether the field is disabled */
  disabled?: boolean;
  /** Whether to show as compact (dialogs) vs full (detail forms) */
  variant?: 'form' | 'dialog';
  /** Translation function — compatible with i18next TFunction */
  t: TranslationFn;
}

interface EntityCodeFieldReturn {
  /** Whether the user has manually overridden the auto-suggested code */
  codeOverridden: boolean;
  /** The auto-suggested code (null if not yet available) */
  suggestedCode: string | null;
}

// ============================================================================
// COMPONENT
// ============================================================================

export function EntityCodeField({
  value,
  onChange,
  entityType,
  buildingId,
  floorLevel,
  locationZone,
  label,
  placeholderFallback,
  infoExample,
  disabled = false,
  variant = 'form',
  t,
}: EntityCodeFieldProps): React.JSX.Element {
  const [codeOverridden, setCodeOverridden] = useState(!!value);

  const { suggestedCode, isLoading: codeLoading } = useEntityCodeSuggestion({
    entityType,
    buildingId,
    floorLevel,
    locationZone: locationZone || undefined,
    disabled: codeOverridden || disabled,
  });

  // Auto-populate when suggestion arrives and field is empty
  useEffect(() => {
    if (suggestedCode && !codeOverridden && !value) {
      onChange(suggestedCode);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [suggestedCode, codeOverridden]);

  const handleChange = (newValue: string) => {
    onChange(newValue);
    if (!codeOverridden && newValue !== suggestedCode) setCodeOverridden(true);
    if (!newValue) setCodeOverridden(false);
  };

  const isForm = variant === 'form';
  const labelClassName = isForm
    ? 'text-muted-foreground text-xs flex items-center gap-1'
    : 'text-sm font-medium flex items-center gap-1';

  return (
    <fieldset className={isForm ? 'space-y-1.5' : 'flex flex-col gap-1.5'}>
      {isForm ? (
        <Label className={labelClassName}>
          {label}
          <CodeInfoPopover t={t} infoExample={infoExample} />
        </Label>
      ) : (
        <span className={labelClassName}>
          {label}
          <CodeInfoPopover t={t} infoExample={infoExample} />
        </span>
      )}
      <Input
        value={value}
        onChange={(e) => handleChange(e.target.value)}
        placeholder={suggestedCode || placeholderFallback}
        className={isForm ? 'h-8 text-sm' : undefined}
        disabled={disabled}
      />
      {value && isValidEntityCodeFormat(value) && (
        <p className="text-[10px] text-emerald-600">
          {t('entityCode.autoGenerated', { defaultValue: 'Αυτόματη κωδικοποίηση ADR-233' })}
        </p>
      )}
      {codeLoading && !disabled && (
        <p className="text-[10px] text-muted-foreground">
          {t('entityCode.loading', { defaultValue: 'Υπολογισμός κωδικού...' })}
        </p>
      )}
      {suggestedCode && codeOverridden && value !== suggestedCode && !disabled && (
        <p className="text-[10px] text-muted-foreground">
          {t('entityCode.suggested', { code: suggestedCode, defaultValue: `Προτεινόμενος: ${suggestedCode}` })}
        </p>
      )}
      {value && !isValidEntityCodeFormat(value) && !disabled && (
        <p className="text-[10px] text-amber-600">
          {t('entityCode.formatWarning', { defaultValue: 'Ο κωδικός δεν ακολουθεί το πρότυπο format' })}
        </p>
      )}
    </fieldset>
  );
}

// ============================================================================
// SUB-COMPONENT: Popover
// ============================================================================

function CodeInfoPopover({
  t,
  infoExample,
}: {
  t: (key: string, opts?: Record<string, unknown> | string) => string;
  infoExample: string;
}) {
  return (
    <Popover>
      <PopoverTrigger asChild>
        <button
          type="button"
          className="text-muted-foreground hover:text-foreground transition-colors"
          aria-label="Info"
        >
          <Info className="h-3 w-3" />
        </button>
      </PopoverTrigger>
      <PopoverContent className="w-72 text-xs" side="right" align="start">
        <h4 className="font-semibold mb-1">
          {t('entityCode.infoTitle', { defaultValue: 'Σύστημα Κωδικοποίησης ADR-233' })}
        </h4>
        <p className="text-muted-foreground mb-1">
          {t('entityCode.infoFormat', { defaultValue: 'Μορφή: {Κτίριο}-{Τύπος}-{Όροφος}.{ΑΑ}' })}
        </p>
        <p className="text-muted-foreground">{infoExample}</p>
      </PopoverContent>
    </Popover>
  );
}

export type { EntityCodeFieldProps };
