/**
 * ADR-684 Φ3 — Authoring defaults + per-shape dimension descriptors (SSoT).
 *
 * Two authoring-time concerns that the ribbon shape selector + bridge need, owned
 * once here (never hand-listed at the UI layer):
 *
 *   1. `defaultGenericSolidShapeOfKind(kind)` — a sensible starter shape when the
 *      user switches the shape selector (Revit/C4D «Add → primitive» ships a
 *      reasonable default, not a zero-sized solid).
 *   2. `GENERIC_SOLID_SHAPE_DIMENSIONS` — the ordered numeric fields each shape
 *      exposes for editing (field name + i18n label + quantity kind), so the
 *      ribbon tab is GENERATED by a loop over `GENERIC_SOLID_SHAPE_KINDS` instead
 *      of 8 near-identical hand-written numeric blocks (N.18 / gotcha §3.6).
 *   3. `updateGenericSolidShapeDimension(shape, field, value)` — immutable per-field
 *      patch, guarded so a field foreign to the current shape is a no-op.
 *
 * @see ./generic-solid-types — GenericSolidShape (the discriminated union this mirrors)
 */

import type { GenericSolidShape, GenericSolidShapeKind } from './generic-solid-types';

// ─── Starter shapes ────────────────────────────────────────────────────────────

/** A reasonable default instance per shape kind (mm). */
export const GENERIC_SOLID_SHAPE_DEFAULTS: {
  readonly [K in GenericSolidShapeKind]: Extract<GenericSolidShape, { kind: K }>;
} = {
  box: { kind: 'box', widthMm: 500, depthMm: 500, heightMm: 500 },
  sphere: { kind: 'sphere', radiusMm: 250 },
  cylinder: { kind: 'cylinder', radiusMm: 250, heightMm: 500 },
  cone: { kind: 'cone', radiusBottomMm: 250, radiusTopMm: 0, heightMm: 500 },
  torus: { kind: 'torus', majorRadiusMm: 250, tubeRadiusMm: 75 },
  pyramid: { kind: 'pyramid', baseWidthMm: 500, baseDepthMm: 500, heightMm: 500 },
  disc: { kind: 'disc', radiusMm: 250, thicknessMm: 50 },
  prism: { kind: 'prism', radiusMm: 250, heightMm: 500, sides: 6 },
};

/** Starter shape when the shape selector switches to `kind`. */
export function defaultGenericSolidShapeOfKind(kind: GenericSolidShapeKind): GenericSolidShape {
  return GENERIC_SOLID_SHAPE_DEFAULTS[kind];
}

// ─── Dimension descriptors (authoring UI) ──────────────────────────────────────

/** The quantity a numeric ribbon field represents (drives formatting + coverage). */
export type GenericSolidDimensionQuantity = 'length' | 'count';

/** One editable numeric field of a shape. */
export interface GenericSolidDimensionDescriptor {
  /** The shape field this edits (e.g. `widthMm`, `radiusMm`, `sides`). */
  readonly field: string;
  /** i18n label key (shared across shapes for the same field name). */
  readonly labelKey: string;
  /** length (mm dimension) or count (integer, e.g. prism sides). */
  readonly quantityKind: GenericSolidDimensionQuantity;
}

/** i18n label key for a dimension field (deduped: `radiusMm` shares one label). */
const dimLabel = (field: string): string => `ribbon.commands.genericSolidEditor.dim.${field}`;

const len = (field: string): GenericSolidDimensionDescriptor => ({
  field,
  labelKey: dimLabel(field),
  quantityKind: 'length',
});

/** The ordered numeric fields each shape exposes for editing. */
export const GENERIC_SOLID_SHAPE_DIMENSIONS: {
  readonly [K in GenericSolidShapeKind]: readonly GenericSolidDimensionDescriptor[];
} = {
  box: [len('widthMm'), len('depthMm'), len('heightMm')],
  sphere: [len('radiusMm')],
  cylinder: [len('radiusMm'), len('heightMm')],
  cone: [len('radiusBottomMm'), len('radiusTopMm'), len('heightMm')],
  torus: [len('majorRadiusMm'), len('tubeRadiusMm')],
  pyramid: [len('baseWidthMm'), len('baseDepthMm'), len('heightMm')],
  disc: [len('radiusMm'), len('thicknessMm')],
  prism: [len('radiusMm'), len('heightMm'), { field: 'sides', labelKey: dimLabel('sides'), quantityKind: 'count' }],
};

/** Every distinct dimension field across all shapes (for the command-key registry). */
export const GENERIC_SOLID_DIMENSION_FIELDS: readonly string[] = Array.from(
  new Set(Object.values(GENERIC_SOLID_SHAPE_DIMENSIONS).flatMap((dims) => dims.map((d) => d.field))),
);

// ─── Immutable per-field patch ─────────────────────────────────────────────────

/**
 * Return a copy of `shape` with `field` set to `value`. No-op (returns the same
 * shape) when `field` is not a numeric key of the current shape — so a stale
 * ribbon key from a previously-selected shape can never corrupt the union.
 */
export function updateGenericSolidShapeDimension(
  shape: GenericSolidShape,
  field: string,
  value: number,
): GenericSolidShape {
  if (!(field in shape) || field === 'kind') return shape;
  return { ...shape, [field]: value } as GenericSolidShape;
}
