/**
 * Floor Factory (ADR-369 §9 Q4 + Q6 + Q9) — Phase A2
 *
 * Pure factory function για δημιουργία `FloorDocument` με ADR-369 defaults +
 * auto-naming (Greek canonical longName, locale-independent short name).
 * Δεν γράφει σε Firestore — caller κάνει `setDoc()`.
 *
 * Auto-naming rules (ADR-369 §9 Q9):
 *   - Αν `name` δεν δοθεί → `generateAutoShortName(kind, number)` + flag=true
 *   - Αν `longName` δεν δοθεί → `generateAutoLongName(kind, number)` + flag=true
 *   - User override (provide name/longName) → flag=false (preserved on auto-renumber)
 *
 * Kind inference (ADR-369 §9 Q6):
 *   - Αν `kind` δεν δοθεί → `inferKindFromNumber(number)` (ground/standard/basement)
 *   - foundation/roof/mezzanine χρειάζονται explicit kind από caller.
 *
 * Mezzanine validation (ADR-369 §9 Q6 + user decision 2026-05-20):
 *   - kind='mezzanine' απαιτεί `mezzanineParentNumber` (parent standard floor).
 *   - `number` παραμένει ακέραιος (Floor.number z.number().int()).
 *
 * Defaults:
 *   - id              : enterprise floor ID (ADR-294)
 *   - finishThickness : 80mm (DEFAULT_FLOOR_FINISH_THICKNESS_MM Greek typical)
 *   - height          : 3.0m (DEFAULT_FLOOR_HEIGHT_M Greek residential)
 *
 * @see docs/centralized-systems/reference/adrs/ADR-369-bim-elevation-convention-revit-alignment.md §9 Q4, Q6, Q9
 */

import { generateFloorId } from '@/services/enterprise-id-convenience';
import type { FloorDocument } from '@/app/api/floors/floors.types';
import {
  generateAutoShortName,
  generateAutoLongName,
  inferKindFromNumber,
  DEFAULT_FLOOR_HEIGHT_M,
  DEFAULT_FLOOR_FINISH_THICKNESS_MM,
  type FloorKind,
} from '@/utils/floor-naming';

/**
 * Input για `createFloor`. Required: `number` + `buildingId`. Όλα τα άλλα
 * optional — auto-derived defaults εφαρμόζονται.
 */
export interface CreateFloorInput {
  /** Signed integer: negative=basement, 0=ground, positive=standard. */
  number: number;
  /** FK to parent Building. */
  buildingId: string;
  /** Optional explicit kind. Αν δεν δοθεί → inferred από `number`. */
  kind?: FloorKind;
  /** Optional override για short name. Αν δοθεί → nameAutoGenerated=false. */
  name?: string;
  /** Optional override για long name. Αν δοθεί → longNameAutoGenerated=false. */
  longName?: string;
  /** METRES — storey height. Default DEFAULT_FLOOR_HEIGHT_M=3.0. */
  height?: number | null;
  /** METRES — floor elevation (Floor.elevation = FFL relative to building). */
  elevation?: number;
  /** MILLIMETRES — finish thickness FFL→ToS. Default 80mm. */
  finishThickness?: number;
  /** Mezzanine only: parent standard floor number. Required when kind='mezzanine'. */
  mezzanineParentNumber?: number;
  /** Optional FK propagation. */
  projectId?: string;
  /** Optional tenant scope. */
  companyId?: string;
}

/**
 * Παράγει νέο `FloorDocument` με ADR-369 auto-naming + defaults.
 *
 * @throws Error αν kind='mezzanine' χωρίς `mezzanineParentNumber`.
 *
 * @example
 * createFloor({ number: 1, buildingId: 'bldg_...' });
 * // → kind='standard', name='L1', longName='1ος Όροφος', finishThickness=80, height=3.0
 *
 * @example
 * createFloor({ number: 0, buildingId: 'bldg_...' });
 * // → kind='ground', name='GF', longName='Ισόγειο'
 *
 * @example
 * createFloor({ number: 2, buildingId: 'bldg_...', kind: 'mezzanine', mezzanineParentNumber: 1 });
 * // → kind='mezzanine', name='M2', longName='2ο Μεσοπάτωμα'
 */
export function createFloor(input: CreateFloorInput): FloorDocument {
  const kind: FloorKind = input.kind ?? inferKindFromNumber(input.number);

  if (kind === 'mezzanine' && input.mezzanineParentNumber === undefined) {
    throw new Error(
      `createFloor: kind='mezzanine' requires mezzanineParentNumber (parent floor number).`,
    );
  }

  const nameProvided = input.name !== undefined;
  const longNameProvided = input.longName !== undefined;

  const name = nameProvided
    ? (input.name as string)
    : generateAutoShortName(kind, input.number);
  const longName = longNameProvided
    ? (input.longName as string)
    : generateAutoLongName(kind, input.number);

  const doc: FloorDocument = {
    id: generateFloorId(),
    number: input.number,
    name,
    buildingId: input.buildingId,
    kind,
    longName,
    nameAutoGenerated: !nameProvided,
    longNameAutoGenerated: !longNameProvided,
    finishThickness: input.finishThickness ?? DEFAULT_FLOOR_FINISH_THICKNESS_MM,
    height: input.height === undefined ? DEFAULT_FLOOR_HEIGHT_M : input.height,
  };

  if (input.elevation !== undefined) doc.elevation = input.elevation;
  if (input.projectId !== undefined) doc.projectId = input.projectId;
  if (input.companyId !== undefined) doc.companyId = input.companyId;
  if (input.mezzanineParentNumber !== undefined) {
    doc.mezzanineParentNumber = input.mezzanineParentNumber;
  }

  return doc;
}
