/**
 * Tests — Floor Factory (ADR-369 §9 Q4/Q6/Q9) — Phase A2
 */

import { createFloor } from '../floor.factory';

describe('createFloor', () => {
  // ─── Kind inference ───────────────────────────────────────────────────────

  describe('kind inference από number', () => {
    it('number=0 → kind="ground"', () => {
      const f = createFloor({ number: 0, buildingId: 'bldg_x' });
      expect(f.kind).toBe('ground');
      expect(f.name).toBe('GF');
      expect(f.longName).toBe('Ισόγειο');
    });

    it('positive number → kind="standard"', () => {
      const f = createFloor({ number: 3, buildingId: 'bldg_x' });
      expect(f.kind).toBe('standard');
      expect(f.name).toBe('L3');
      expect(f.longName).toBe('3ος Όροφος');
    });

    it('negative number → kind="basement"', () => {
      const f = createFloor({ number: -2, buildingId: 'bldg_x' });
      expect(f.kind).toBe('basement');
      expect(f.name).toBe('B2');
      expect(f.longName).toBe('2ο Υπόγειο');
    });
  });

  // ─── Auto-generation flags ────────────────────────────────────────────────

  describe('auto-generation flags', () => {
    it('no name/longName provided → both flags=true', () => {
      const f = createFloor({ number: 1, buildingId: 'bldg_x' });
      expect(f.nameAutoGenerated).toBe(true);
      expect(f.longNameAutoGenerated).toBe(true);
    });

    it('user provides name → nameAutoGenerated=false', () => {
      const f = createFloor({ number: 1, buildingId: 'bldg_x', name: 'Penthouse' });
      expect(f.name).toBe('Penthouse');
      expect(f.nameAutoGenerated).toBe(false);
      expect(f.longNameAutoGenerated).toBe(true);
    });

    it('user provides longName → longNameAutoGenerated=false', () => {
      const f = createFloor({
        number: 1,
        buildingId: 'bldg_x',
        longName: 'Όροφος Διευθυντή',
      });
      expect(f.longName).toBe('Όροφος Διευθυντή');
      expect(f.longNameAutoGenerated).toBe(false);
      expect(f.nameAutoGenerated).toBe(true);
    });
  });

  // ─── Explicit kind override ───────────────────────────────────────────────

  describe('explicit kind override', () => {
    it('kind="foundation" → name="F", longName="Θεμελίωση"', () => {
      const f = createFloor({ number: -3, buildingId: 'bldg_x', kind: 'foundation' });
      expect(f.kind).toBe('foundation');
      expect(f.name).toBe('F');
      expect(f.longName).toBe('Θεμελίωση');
    });

    it('kind="roof" → name="R", longName="Δώμα"', () => {
      const f = createFloor({ number: 5, buildingId: 'bldg_x', kind: 'roof' });
      expect(f.kind).toBe('roof');
      expect(f.name).toBe('R');
      expect(f.longName).toBe('Δώμα');
    });
  });

  // ─── Mezzanine validation ─────────────────────────────────────────────────

  describe('mezzanine', () => {
    it('kind="mezzanine" + mezzanineParentNumber → valid', () => {
      const f = createFloor({
        number: 1,
        buildingId: 'bldg_x',
        kind: 'mezzanine',
        mezzanineParentNumber: 1,
      });
      expect(f.kind).toBe('mezzanine');
      expect(f.mezzanineParentNumber).toBe(1);
      expect(f.name).toBe('M1');
      expect(f.longName).toBe('Μεσοπάτωμα');
    });

    it('kind="mezzanine" without mezzanineParentNumber → throws', () => {
      expect(() =>
        createFloor({ number: 1, buildingId: 'bldg_x', kind: 'mezzanine' }),
      ).toThrow(/mezzanineParentNumber/);
    });

    it('mezzanine number=2 → "2ο Μεσοπάτωμα"', () => {
      const f = createFloor({
        number: 2,
        buildingId: 'bldg_x',
        kind: 'mezzanine',
        mezzanineParentNumber: 1,
      });
      expect(f.longName).toBe('2ο Μεσοπάτωμα');
    });
  });

  // ─── Defaults ─────────────────────────────────────────────────────────────

  describe('defaults', () => {
    it('finishThickness default = 80mm', () => {
      const f = createFloor({ number: 1, buildingId: 'bldg_x' });
      expect(f.finishThickness).toBe(80);
    });

    it('height default = 3.0m', () => {
      const f = createFloor({ number: 1, buildingId: 'bldg_x' });
      expect(f.height).toBe(3.0);
    });

    it('user override finishThickness preserved', () => {
      const f = createFloor({ number: 1, buildingId: 'bldg_x', finishThickness: 120 });
      expect(f.finishThickness).toBe(120);
    });

    it('explicit height=null preserved (no default override)', () => {
      const f = createFloor({ number: 1, buildingId: 'bldg_x', height: null });
      expect(f.height).toBeNull();
    });
  });

  // ─── Enterprise ID ────────────────────────────────────────────────────────

  describe('enterprise ID', () => {
    it('id starts with "flr_" prefix', () => {
      const f = createFloor({ number: 1, buildingId: 'bldg_x' });
      expect(f.id).toMatch(/^flr_/);
    });

    it('100 calls produce unique IDs', () => {
      const ids = new Set<string>();
      for (let i = 0; i < 100; i++) {
        ids.add(createFloor({ number: i, buildingId: 'bldg_x' }).id);
      }
      expect(ids.size).toBe(100);
    });
  });

  // ─── Optional FK propagation ──────────────────────────────────────────────

  describe('optional FKs', () => {
    it('projectId / companyId propagated when provided', () => {
      const f = createFloor({
        number: 1,
        buildingId: 'bldg_x',
        projectId: 'proj_y',
        companyId: 'comp_z',
      });
      expect(f.projectId).toBe('proj_y');
      expect(f.companyId).toBe('comp_z');
    });

    it('FKs absent when not provided', () => {
      const f = createFloor({ number: 1, buildingId: 'bldg_x' });
      expect(f.projectId).toBeUndefined();
      expect(f.companyId).toBeUndefined();
    });
  });
});
