/**
 * 🌐 Auto-generated i18n TypeScript Definitions
 *
 * This file is automatically generated from translation files.
 * Do not edit manually - changes will be overwritten.
 *
 * Generated: 2025-12-10T16:31:49.291Z
 */

interface I18n_Auth {
  login: I18n_Auth_Login;
}

interface I18n_Auth_Login {
  title: string;
  subtitle: string;
  email: string;
  password: string;
  emailPlaceholder: string;
  submit: string;
  submitting: string;
  success: I18n_Auth_Login_Success;
}

interface I18n_Auth_Login_Success {
  title: string;
  message: string;
}

interface I18n_Building {
  floors: I18n_Building_Floors;
}

interface I18n_Building_Floors {
  ground: string;
  basement: string;
  floor: string;
  firstFloor: string;
  secondFloor: string;
  thirdFloor: string;
}

interface I18n_Common {
  buttons: I18n_Common_Buttons;
}

interface I18n_Common_Buttons {
  save: string;
  cancel: string;
  delete: string;
  edit: string;
  add: string;
  search: string;
  export: string;
  import: string;
  refresh: string;
  close: string;
}

interface I18n_Compositions {
  title: string;
  description: string;
  showcase: I18n_Compositions_Showcase;
}

interface I18n_Compositions_Showcase {
  title: string;
  subtitle: string;
  sections: I18n_Compositions_Showcase_Sections;
}

interface I18n_Compositions_Showcase_Sections {
  cards: string;
  toolbars: string;
  integration: string;
  benefits: string;
}

interface I18n_Contacts {
  details: I18n_Contacts_Details;
}

interface I18n_Contacts_Details {
  contactInfo: I18n_Contacts_Details_ContactInfo;
}

interface I18n_Contacts_Details_ContactInfo {
  title: string;
  noContactInfo: string;
}

interface I18n_Crm {
  overview: I18n_Crm_Overview;
}

interface I18n_Crm_Overview {
  stats: I18n_Crm_Overview_Stats;
}

interface I18n_Crm_Overview_Stats {
  newLeads: string;
  activeOpportunities: string;
  scheduledViewings: string;
  pendingTasks: string;
}

interface I18n_Dashboard {
  welcome: I18n_Dashboard_Welcome;
}

interface I18n_Dashboard_Welcome {
  title: string;
  subtitle: string;
  actions: I18n_Dashboard_Welcome_Actions;
}

interface I18n_Dashboard_Welcome_Actions {
  newContact: string;
  search: string;
}

interface I18n_Dxf-viewer {
  layers: I18n_Dxf-viewer_Layers;
}

interface I18n_Dxf-viewer_Layers {
  title: string;
  clickToSelect: string;
  delete: I18n_Dxf-viewer_Layers_Delete;
}

interface I18n_Dxf-viewer_Layers_Delete {
  confirm: string;
  success: string;
  error: string;
  tooltip: string;
}

interface I18n_Errors {
  http: I18n_Errors_Http;
}

interface I18n_Errors_Http {
  400: string;
  401: string;
  403: string;
  404: string;
  500: string;
}

interface I18n_Forms {
  labels: I18n_Forms_Labels;
}

interface I18n_Forms_Labels {
  name: string;
  email: string;
  phone: string;
  address: string;
  description: string;
  company: string;
  position: string;
  area: string;
  price: string;
  floor: string;
  status: string;
  salePricePerSqm: string;
  costPerSqm: string;
  realizedValue: string;
  completionAmount: string;
  financing: string;
}

interface I18n_Geo-canvas {
  title: string;
  subtitle: string;
  phases: I18n_Geo-canvas_Phases;
}

interface I18n_Geo-canvas_Phases {
  foundation: string;
  transformation: string;
  mapping: string;
  database: string;
  alerts: string;
  ui: string;
  performance: string;
  deployment: string;
}

interface I18n_Landing {
  hero: I18n_Landing_Hero;
}

interface I18n_Landing_Hero {
  findIdeal: string;
  property: string;
  subtitle: string;
}

interface I18n_Navigation {
  menu: I18n_Navigation_Menu;
}

interface I18n_Navigation_Menu {
  main: string;
  tools: string;
  settings: string;
}

interface I18n_Projects {
  title: string;
  description: string;
  toolbar: I18n_Projects_Toolbar;
}

interface I18n_Projects_Toolbar {
  new: string;
  edit: string;
  delete: string;
  export: string;
  import: string;
  refresh: string;
  archive: string;
  favorite: string;
  share: string;
  mapView: string;
  help: string;
  search: I18n_Projects_Toolbar_Search;
}

interface I18n_Projects_Toolbar_Search {
  placeholder: string;
}

interface I18n_Properties {
  building: I18n_Properties_Building;
}

interface I18n_Properties_Building {
  toolbar: I18n_Properties_Building_Toolbar;
}

interface I18n_Properties_Building_Toolbar {
  actions: I18n_Properties_Building_Toolbar_Actions;
}

interface I18n_Properties_Building_Toolbar_Actions {
  new: string;
  edit: string;
  delete: string;
}

interface I18n_Tasks {
  title: string;
  description: string;
  types: I18n_Tasks_Types;
}

interface I18n_Tasks_Types {
  call: string;
  email: string;
  meeting: string;
  viewing: string;
  followup: string;
  research: string;
  documentation: string;
  other: string;
}

interface I18n_Toasts {
  success: I18n_Toasts_Success;
}

interface I18n_Toasts_Success {
  saved: string;
  deleted: string;
  updated: string;
}

interface I18n_Toolbars {
  title: string;
  description: string;
  common: I18n_Toolbars_Common;
}

interface I18n_Toolbars_Common {
  actions: I18n_Toolbars_Common_Actions;
}

interface I18n_Toolbars_Common_Actions {
  new: string;
  edit: string;
  delete: string;
  export: string;
  import: string;
  refresh: string;
  archive: string;
  favorite: string;
  share: string;
  help: string;
}

interface I18n_Units {
  management: I18n_Units_Management;
}

interface I18n_Units_Management {
  title: string;
  subtitle: string;
}

interface I18n_Users {
  title: string;
  description: string;
  roles: I18n_Users_Roles;
}

interface I18n_Users_Roles {
  admin: string;
  manager: string;
  agent: string;
  user: string;
  viewer: string;
}

export interface I18nKeys {
  auth: I18n_Auth;
  building: I18n_Building;
  common: I18n_Common;
  compositions: I18n_Compositions;
  contacts: I18n_Contacts;
  crm: I18n_Crm;
  dashboard: I18n_Dashboard;
  dxf-viewer: I18n_Dxf-viewer;
  errors: I18n_Errors;
  forms: I18n_Forms;
  geo-canvas: I18n_Geo-canvas;
  landing: I18n_Landing;
  navigation: I18n_Navigation;
  projects: I18n_Projects;
  properties: I18n_Properties;
  tasks: I18n_Tasks;
  toasts: I18n_Toasts;
  toolbars: I18n_Toolbars;
  units: I18n_Units;
  users: I18n_Users;
}

export type TranslationNamespace = 'auth' | 'building' | 'common' | 'compositions' | 'contacts' | 'crm' | 'dashboard' | 'dxf-viewer' | 'errors' | 'forms' | 'geo-canvas' | 'landing' | 'navigation' | 'projects' | 'properties' | 'tasks' | 'toasts' | 'toolbars' | 'units' | 'users';

/**
 * Utility type for nested translation keys
 */
export type NestedKeyOf<ObjectType extends object> = {
  [Key in keyof ObjectType & (string | number)]: ObjectType[Key] extends object
    ? `${Key}.${NestedKeyOf<ObjectType[Key]>}`
    : `${Key}`
}[keyof ObjectType & (string | number)];

/**
 * All available translation keys in dot notation
 */
export type TranslationKey = NestedKeyOf<I18nKeys>;
