/**
 * 🌐 Auto-generated i18n TypeScript Definitions
 *
 * This file is automatically generated from translation files.
 * Do not edit manually - changes will be overwritten.
 *
 * Generated: 2025-12-13T09:51:19.779Z
 */

interface I18n_Auth {
  'login': I18n_Auth_Login;
}

interface I18n_Auth_Login {
  title: string;
  subtitle: string;
  email: string;
  password: string;
  emailPlaceholder: string;
  submit: string;
  submitting: string;
  'success': I18n_Auth_Login_Success;
  'error': I18n_Auth_Login_Error;
}

interface I18n_Auth_Login_Success {
  title: string;
  message: string;
}

interface I18n_Auth_Login_Error {
  title: string;
  message: string;
}

interface I18n_Building {
  'floors': I18n_Building_Floors;
  'categories': I18n_Building_Categories;
  'status': I18n_Building_Status;
  'units': I18n_Building_Units;
  'filters': I18n_Building_Filters;
}

interface I18n_Building_Floors {
  ground: string;
  basement: string;
  floor: string;
  firstFloor: string;
  secondFloor: string;
  thirdFloor: string;
}

interface I18n_Building_Categories {
  residential: string;
  commercial: string;
  mixed: string;
  industrial: string;
}

interface I18n_Building_Status {
  active: string;
  construction: string;
  planned: string;
  completed: string;
}

interface I18n_Building_Units {
  pricePerSqm: string;
  sqm: string;
}

interface I18n_Building_Filters {
  title: string;
  tooltip: string;
  clearAll: string;
  'states': I18n_Building_Filters_States;
  'types': I18n_Building_Filters_Types;
}

interface I18n_Building_Filters_States {
  active: string;
  construction: string;
  planned: string;
  completed: string;
}

interface I18n_Building_Filters_Types {
  residential: string;
  commercial: string;
  mixed: string;
}

interface I18n_Common {
  'buttons': I18n_Common_Buttons;
  'status': I18n_Common_Status;
  'placeholders': I18n_Common_Placeholders;
  'navigation': I18n_Common_Navigation;
  'actions': I18n_Common_Actions;
  'success': I18n_Common_Success;
}

interface I18n_Common_Buttons {
  save: string;
  cancel: string;
  delete: string;
  edit: string;
  add: string;
  search: string;
  export: string;
  import: string;
  refresh: string;
  close: string;
}

interface I18n_Common_Status {
  loading: string;
  error: string;
  success: string;
  pending: string;
  completed: string;
}

interface I18n_Common_Placeholders {
  search: string;
  selectOption: string;
  enterText: string;
}

interface I18n_Common_Navigation {
  home: string;
  properties: string;
  crm: string;
  admin: string;
}

interface I18n_Common_Actions {
  save: string;
  cancel: string;
  delete: string;
  edit: string;
  close: string;
  confirm: string;
}

interface I18n_Common_Success {
  fileUploaded: string;
  settingsSaved: string;
}

interface I18n_Compositions {
  title: string;
  description: string;
  'showcase': I18n_Compositions_Showcase;
  'cards': I18n_Compositions_Cards;
  'toolbars': I18n_Compositions_Toolbars;
  'demo': I18n_Compositions_Demo;
  'integration': I18n_Compositions_Integration;
  'benefits': I18n_Compositions_Benefits;
}

interface I18n_Compositions_Showcase {
  title: string;
  subtitle: string;
  'sections': I18n_Compositions_Showcase_Sections;
}

interface I18n_Compositions_Showcase_Sections {
  cards: string;
  toolbars: string;
  integration: string;
  benefits: string;
}

interface I18n_Compositions_Cards {
  'task': I18n_Compositions_Cards_Task;
  'user': I18n_Compositions_Cards_User;
  'building': I18n_Compositions_Cards_Building;
  'project': I18n_Compositions_Cards_Project;
  'contact': I18n_Compositions_Cards_Contact;
  'storage': I18n_Compositions_Cards_Storage;
  'property': I18n_Compositions_Cards_Property;
  'notification': I18n_Compositions_Cards_Notification;
}

interface I18n_Compositions_Cards_Task {
  title: string;
  description: string;
}

interface I18n_Compositions_Cards_User {
  title: string;
  description: string;
}

interface I18n_Compositions_Cards_Building {
  title: string;
  description: string;
}

interface I18n_Compositions_Cards_Project {
  title: string;
  description: string;
}

interface I18n_Compositions_Cards_Contact {
  title: string;
  description: string;
}

interface I18n_Compositions_Cards_Storage {
  title: string;
  description: string;
}

interface I18n_Compositions_Cards_Property {
  title: string;
  description: string;
}

interface I18n_Compositions_Cards_Notification {
  title: string;
  description: string;
}

interface I18n_Compositions_Toolbars {
  'building': I18n_Compositions_Toolbars_Building;
  'project': I18n_Compositions_Toolbars_Project;
  'contacts': I18n_Compositions_Toolbars_Contacts;
}

interface I18n_Compositions_Toolbars_Building {
  title: string;
  description: string;
}

interface I18n_Compositions_Toolbars_Project {
  title: string;
  description: string;
}

interface I18n_Compositions_Toolbars_Contacts {
  title: string;
  description: string;
}

interface I18n_Compositions_Demo {
  state: string;
  selected: string;
  search: string;
  filters: string;
  none: string;
  simulate: string;
  items: string;
}

interface I18n_Compositions_Integration {
  title: string;
  description: string;
  'examples': I18n_Compositions_Integration_Examples;
}

interface I18n_Compositions_Integration_Examples {
  buildings: string;
  projects: string;
  contacts: string;
}

interface I18n_Compositions_Benefits {
  title: string;
  'consistency': I18n_Compositions_Benefits_Consistency;
  'modularity': I18n_Compositions_Benefits_Modularity;
  'typeSafety': I18n_Compositions_Benefits_TypeSafety;
  'performance': I18n_Compositions_Benefits_Performance;
  'unifiedInterface': I18n_Compositions_Benefits_UnifiedInterface;
  'configurable': I18n_Compositions_Benefits_Configurable;
  'accessible': I18n_Compositions_Benefits_Accessible;
}

interface I18n_Compositions_Benefits_Consistency {
  title: string;
  description: string;
}

interface I18n_Compositions_Benefits_Modularity {
  title: string;
  description: string;
}

interface I18n_Compositions_Benefits_TypeSafety {
  title: string;
  description: string;
}

interface I18n_Compositions_Benefits_Performance {
  title: string;
  description: string;
}

interface I18n_Compositions_Benefits_UnifiedInterface {
  title: string;
  description: string;
}

interface I18n_Compositions_Benefits_Configurable {
  title: string;
  description: string;
}

interface I18n_Compositions_Benefits_Accessible {
  title: string;
  description: string;
}

interface I18n_Contacts {
  'details': I18n_Contacts_Details;
}

interface I18n_Contacts_Details {
  'contactInfo': I18n_Contacts_Details_ContactInfo;
  'taxInfo': I18n_Contacts_Details_TaxInfo;
}

interface I18n_Contacts_Details_ContactInfo {
  title: string;
  noContactInfo: string;
}

interface I18n_Contacts_Details_TaxInfo {
  title: string;
  vatNumber: string;
  notSet: string;
}

interface I18n_Crm {
  'overview': I18n_Crm_Overview;
  'opportunities': I18n_Crm_Opportunities;
  'dashboard': I18n_Crm_Dashboard;
  'tasks': I18n_Crm_Tasks;
  'errors': I18n_Crm_Errors;
  'success': I18n_Crm_Success;
}

interface I18n_Crm_Overview {
  'stats': I18n_Crm_Overview_Stats;
}

interface I18n_Crm_Overview_Stats {
  newLeads: string;
  activeOpportunities: string;
  scheduledViewings: string;
  pendingTasks: string;
}

interface I18n_Crm_Opportunities {
  'stages': I18n_Crm_Opportunities_Stages;
  'status': I18n_Crm_Opportunities_Status;
  'actions': I18n_Crm_Opportunities_Actions;
}

interface I18n_Crm_Opportunities_Stages {
  initial_contact: string;
  qualification: string;
  viewing: string;
  proposal: string;
  negotiation: string;
  contract: string;
  closed_won: string;
  closed_lost: string;
}

interface I18n_Crm_Opportunities_Status {
  active: string;
  inactive: string;
  pending: string;
}

interface I18n_Crm_Opportunities_Actions {
  edit: string;
  delete: string;
  view: string;
}

interface I18n_Crm_Dashboard {
  'tabs': I18n_Crm_Dashboard_Tabs;
}

interface I18n_Crm_Dashboard_Tabs {
  overview: string;
  contacts: string;
  pipeline: string;
  tasks: string;
  calendar: string;
  communications: string;
}

interface I18n_Crm_Tasks {
  title: string;
  newTask: string;
  noTasks: string;
  loading: string;
  searchPlaceholder: string;
  clearFilters: string;
  noDate: string;
  today: string;
  tomorrow: string;
  overdue: string;
  'status': I18n_Crm_Tasks_Status;
  'priority': I18n_Crm_Tasks_Priority;
  'type': I18n_Crm_Tasks_Type;
  'timeframe': I18n_Crm_Tasks_Timeframe;
  'actions': I18n_Crm_Tasks_Actions;
  'messages': I18n_Crm_Tasks_Messages;
}

interface I18n_Crm_Tasks_Status {
  all: string;
  pending: string;
  in_progress: string;
  completed: string;
  cancelled: string;
}

interface I18n_Crm_Tasks_Priority {
  all: string;
  urgent: string;
  high: string;
  medium: string;
  low: string;
}

interface I18n_Crm_Tasks_Type {
  all: string;
  call: string;
  meeting: string;
  viewing: string;
  follow_up: string;
  email: string;
  document: string;
  other: string;
}

interface I18n_Crm_Tasks_Timeframe {
  all: string;
  overdue: string;
  today: string;
  tomorrow: string;
  week: string;
}

interface I18n_Crm_Tasks_Actions {
  complete: string;
  edit: string;
  delete: string;
}

interface I18n_Crm_Tasks_Messages {
  completed: string;
  deleted: string;
  completeError: string;
  deleteError: string;
  loadError: string;
  deleteConfirm: string;
}

interface I18n_Crm_Errors {
  contactNotFound: string;
  invalidStage: string;
  deadlinePassed: string;
}

interface I18n_Crm_Success {
  contactCreated: string;
  contactUpdated: string;
  contactDeleted: string;
}

interface I18n_Dashboard {
  'welcome': I18n_Dashboard_Welcome;
  'stats': I18n_Dashboard_Stats;
  'quickActions': I18n_Dashboard_QuickActions;
  'recentActivities': I18n_Dashboard_RecentActivities;
}

interface I18n_Dashboard_Welcome {
  title: string;
  subtitle: string;
  'actions': I18n_Dashboard_Welcome_Actions;
}

interface I18n_Dashboard_Welcome_Actions {
  newContact: string;
  search: string;
}

interface I18n_Dashboard_Stats {
  totalContacts: string;
  newContacts: string;
  favorites: string;
  activeToday: string;
  'periods': I18n_Dashboard_Stats_Periods;
  quickAccess: string;
}

interface I18n_Dashboard_Stats_Periods {
  thisMonth: string;
  lastMonth: string;
  last24h: string;
}

interface I18n_Dashboard_QuickActions {
  title: string;
  subtitle: string;
  'individual': I18n_Dashboard_QuickActions_Individual;
  'company': I18n_Dashboard_QuickActions_Company;
  'service': I18n_Dashboard_QuickActions_Service;
}

interface I18n_Dashboard_QuickActions_Individual {
  title: string;
  description: string;
}

interface I18n_Dashboard_QuickActions_Company {
  title: string;
  description: string;
}

interface I18n_Dashboard_QuickActions_Service {
  title: string;
  description: string;
}

interface I18n_Dashboard_RecentActivities {
  title: string;
  subtitle: string;
  viewAll: string;
}

interface I18n_Dxfviewer {
  'layers': I18n_Dxfviewer_Layers;
  'confirmations': I18n_Dxfviewer_Confirmations;
  'common': I18n_Dxfviewer_Common;
  'panels': I18n_Dxfviewer_Panels;
  'toolbar': I18n_Dxfviewer_Toolbar;
  'import': I18n_Dxfviewer_Import;
}

interface I18n_Dxfviewer_Layers {
  title: string;
  clickToSelect: string;
  'delete': I18n_Dxfviewer_Layers_Delete;
  'colorPicker': I18n_Dxfviewer_Layers_ColorPicker;
  'actions': I18n_Dxfviewer_Layers_Actions;
  'info': I18n_Dxfviewer_Layers_Info;
}

interface I18n_Dxfviewer_Layers_Delete {
  confirm: string;
  success: string;
  error: string;
  tooltip: string;
}

interface I18n_Dxfviewer_Layers_ColorPicker {
  title: string;
  close: string;
}

interface I18n_Dxfviewer_Layers_Actions {
  select: string;
  hide: string;
  show: string;
  rename: string;
}

interface I18n_Dxfviewer_Layers_Info {
  layer: string;
  elements: string;
  visible: string;
  selected: string;
}

interface I18n_Dxfviewer_Confirmations {
  confirmed: string;
  cancelled: string;
  irreversible: string;
  'delete': I18n_Dxfviewer_Confirmations_Delete;
  'merge': I18n_Dxfviewer_Confirmations_Merge;
}

interface I18n_Dxfviewer_Confirmations_Delete {
  confirm: string;
  'layer': I18n_Dxfviewer_Confirmations_Delete_Layer;
  'entity': I18n_Dxfviewer_Confirmations_Delete_Entity;
  'colorGroup': I18n_Dxfviewer_Confirmations_Delete_ColorGroup;
}

interface I18n_Dxfviewer_Confirmations_Delete_Layer {
  title: string;
  message: string;
}

interface I18n_Dxfviewer_Confirmations_Delete_Entity {
  title: string;
  message: string;
}

interface I18n_Dxfviewer_Confirmations_Delete_ColorGroup {
  title: string;
  message: string;
}

interface I18n_Dxfviewer_Confirmations_Merge {
  confirm: string;
  'entities': I18n_Dxfviewer_Confirmations_Merge_Entities;
  'layers': I18n_Dxfviewer_Confirmations_Merge_Layers;
  'colorGroups': I18n_Dxfviewer_Confirmations_Merge_ColorGroups;
}

interface I18n_Dxfviewer_Confirmations_Merge_Entities {
  title: string;
  message: string;
}

interface I18n_Dxfviewer_Confirmations_Merge_Layers {
  title: string;
  message: string;
}

interface I18n_Dxfviewer_Confirmations_Merge_ColorGroups {
  title: string;
  message: string;
}

interface I18n_Dxfviewer_Common {
  confirm: string;
  cancel: string;
}

interface I18n_Dxfviewer_Panels {
  'properties': I18n_Dxfviewer_Panels_Properties;
  'overlay': I18n_Dxfviewer_Panels_Overlay;
  'levels': I18n_Dxfviewer_Panels_Levels;
  'hierarchy': I18n_Dxfviewer_Panels_Hierarchy;
  'layers': I18n_Dxfviewer_Panels_Layers;
}

interface I18n_Dxfviewer_Panels_Properties {
  title: string;
  description: string;
}

interface I18n_Dxfviewer_Panels_Overlay {
  title: string;
  description: string;
}

interface I18n_Dxfviewer_Panels_Levels {
  title: string;
  description: string;
}

interface I18n_Dxfviewer_Panels_Hierarchy {
  title: string;
  description: string;
  projectHierarchy: string;
  loading: string;
  error: string;
  retry: string;
  companies: string;
  noCompanies: string;
  projects: string;
  noProjects: string;
  buildings: string;
  floors: string;
  availableDestinations: string;
  buildingsCount: string;
  floorsCount: string;
  unitsCount: string;
  parkingSpots: string;
  storageAreas: string;
}

interface I18n_Dxfviewer_Panels_Layers {
  title: string;
  description: string;
}

interface I18n_Dxfviewer_Toolbar {
  select: string;
  pan: string;
  line: string;
  rectangle: string;
  circle: string;
  polyline: string;
}

interface I18n_Dxfviewer_Import {
  'fileDialog': I18n_Dxfviewer_Import_FileDialog;
  'mode': I18n_Dxfviewer_Import_Mode;
  'common': I18n_Dxfviewer_Import_Common;
}

interface I18n_Dxfviewer_Import_FileDialog {
  title: string;
  choose: string;
  hint: string;
  supported: string;
}

interface I18n_Dxfviewer_Import_Mode {
  title: string;
  file: string;
  enhancedTitle: string;
  enhancedDesc: string;
  enhancedDisabled: string;
  legacyTitle: string;
  legacyDesc: string;
}

interface I18n_Dxfviewer_Import_Common {
  cancel: string;
  destinations: string;
  close: string;
}

interface I18n_Errors {
  'http': I18n_Errors_Http;
  'auth': I18n_Errors_Auth;
  'storage': I18n_Errors_Storage;
  'network': I18n_Errors_Network;
  'file': I18n_Errors_File;
  'validation': I18n_Errors_Validation;
  'general': I18n_Errors_General;
  'generic': I18n_Errors_Generic;
}

interface I18n_Errors_Http {
  '400': string;
  '401': string;
  '403': string;
  '404': string;
  '500': string;
}

interface I18n_Errors_Auth {
  tokenExpired: string;
  invalidCredentials: string;
  accessDenied: string;
}

interface I18n_Errors_Storage {
  quotaExceeded: string;
  insufficientSpace: string;
  fileNotFound: string;
}

interface I18n_Errors_Network {
  connectionFailed: string;
  timeout: string;
  offline: string;
}

interface I18n_Errors_File {
  tooLarge: string;
  invalidFormat: string;
  parseError: string;
  uploadFailed: string;
}

interface I18n_Errors_Validation {
  required: string;
  invalid: string;
  tooShort: string;
  tooLong: string;
  failed: string;
  invalidEmail: string;
  passwordWeak: string;
}

interface I18n_Errors_General {
  unknown: string;
  error: string;
  tryAgain: string;
  contact: string;
}

interface I18n_Errors_Generic {
  unknown: string;
  permissionDenied: string;
}

interface I18n_Forms {
  'labels': I18n_Forms_Labels;
  'placeholders': I18n_Forms_Placeholders;
  'validation': I18n_Forms_Validation;
  'actions': I18n_Forms_Actions;
  'tooltips': I18n_Forms_Tooltips;
}

interface I18n_Forms_Labels {
  name: string;
  email: string;
  phone: string;
  address: string;
  description: string;
  company: string;
  position: string;
  area: string;
  price: string;
  floor: string;
  status: string;
  salePricePerSqm: string;
  costPerSqm: string;
  realizedValue: string;
  completionAmount: string;
  financing: string;
}

interface I18n_Forms_Placeholders {
  enterName: string;
  enterEmail: string;
  selectOption: string;
  enterDescription: string;
  enterPrice: string;
  enterArea: string;
}

interface I18n_Forms_Validation {
  required: string;
  invalidEmail: string;
  invalidPhone: string;
  invalidUrl: string;
  minLength: string;
  maxLength: string;
  exactLength: string;
  invalidNumber: string;
  notInteger: string;
  minValue: string;
  maxValue: string;
  positiveNumber: string;
  nonNegativeNumber: string;
  greaterThan: string;
  lessThan: string;
  invalidFormat: string;
  invalidDate: string;
  pastDate: string;
  futureDate: string;
  invalidSelection: string;
  fieldError: string;
  fillAllRequired: string;
  invalidCode: string;
  areaRequired: string;
  priceRequired: string;
  confirmPassword: string;
}

interface I18n_Forms_Actions {
  save: string;
  cancel: string;
  submit: string;
  reset: string;
  edit: string;
  delete: string;
  add: string;
  update: string;
}

interface I18n_Forms_Tooltips {
  salePricePerSqm: string;
  costPerSqm: string;
  realizedValue: string;
  completionAmount: string;
  financing: string;
}

interface I18n_Geocanvas {
  title: string;
  subtitle: string;
  'phases': I18n_Geocanvas_Phases;
  'status': I18n_Geocanvas_Status;
  'views': I18n_Geocanvas_Views;
  'toolbar': I18n_Geocanvas_Toolbar;
  'floorPlan': I18n_Geocanvas_FloorPlan;
  'georeferencing': I18n_Geocanvas_Georeferencing;
  'errors': I18n_Geocanvas_Errors;
  'notifications': I18n_Geocanvas_Notifications;
  'buttons': I18n_Geocanvas_Buttons;
  'loading': I18n_Geocanvas_Loading;
  'coordinateSystems': I18n_Geocanvas_CoordinateSystems;
  'footer': I18n_Geocanvas_Footer;
  'progress': I18n_Geocanvas_Progress;
  'features': I18n_Geocanvas_Features;
  'technical': I18n_Geocanvas_Technical;
  'next': I18n_Geocanvas_Next;
  'actions': I18n_Geocanvas_Actions;
  'validation': I18n_Geocanvas_Validation;
  panelTitle: string;
  addControlPoint: string;
  'panelHeader': I18n_Geocanvas_PanelHeader;
  'form': I18n_Geocanvas_Form;
  'controlPoints': I18n_Geocanvas_ControlPoints;
  'transformation': I18n_Geocanvas_Transformation;
  'workspace': I18n_Geocanvas_Workspace;
  'sidebar': I18n_Geocanvas_Sidebar;
  'errorBoundary': I18n_Geocanvas_ErrorBoundary;
  'phaseDetails': I18n_Geocanvas_PhaseDetails;
  'map': I18n_Geocanvas_Map;
  'accuracy': I18n_Geocanvas_Accuracy;
  'floorPlanControlPoints': I18n_Geocanvas_FloorPlanControlPoints;
  'floorPlanLayer': I18n_Geocanvas_FloorPlanLayer;
  'userTypeSelector': I18n_Geocanvas_UserTypeSelector;
  'propertyStatusManager': I18n_Geocanvas_PropertyStatusManager;
  'realEstateMonitoring': I18n_Geocanvas_RealEstateMonitoring;
  'toastMessages': I18n_Geocanvas_ToastMessages;
  'loadingStates': I18n_Geocanvas_LoadingStates;
  'phaseInformation': I18n_Geocanvas_PhaseInformation;
  'drawingInterfaces': I18n_Geocanvas_DrawingInterfaces;
  'mapStatus': I18n_Geocanvas_MapStatus;
  'hardcodedTexts': I18n_Geocanvas_HardcodedTexts;
  'citizenDrawingInterface': I18n_Geocanvas_CitizenDrawingInterface;
  'alertDashboard': I18n_Geocanvas_AlertDashboard;
  'userActions': I18n_Geocanvas_UserActions;
  'instructions': I18n_Geocanvas_Instructions;
}

interface I18n_Geocanvas_Phases {
  foundation: string;
  transformation: string;
  mapping: string;
  database: string;
  alerts: string;
  ui: string;
  performance: string;
  deployment: string;
}

interface I18n_Geocanvas_Status {
  ready: string;
  inProgress: string;
  completed: string;
  pending: string;
  transformationReady: string;
  mappingReady: string;
  databaseReady: string;
}

interface I18n_Geocanvas_Views {
  foundation: string;
  georeferencing: string;
  mapping: string;
  database: string;
  alerts: string;
}

interface I18n_Geocanvas_Toolbar {
  view: string;
  crs: string;
  zoom: string;
  coordinates: string;
  longitude: string;
  latitude: string;
}

interface I18n_Geocanvas_FloorPlan {
  'uploadButton': I18n_Geocanvas_FloorPlan_UploadButton;
  'uploadModal': I18n_Geocanvas_FloorPlan_UploadModal;
  'preview': I18n_Geocanvas_FloorPlan_Preview;
}

interface I18n_Geocanvas_FloorPlan_UploadButton {
  text: string;
  tooltip: string;
  loading: string;
}

interface I18n_Geocanvas_FloorPlan_UploadModal {
  title: string;
  description: string;
  dragText: string;
  dropText: string;
  orText: string;
  browseButton: string;
  supportedFormats: string;
  maxSize: string;
  'errors': I18n_Geocanvas_FloorPlan_UploadModal_Errors;
}

interface I18n_Geocanvas_FloorPlan_UploadModal_Errors {
  invalidFormat: string;
  fileTooLarge: string;
}

interface I18n_Geocanvas_FloorPlan_Preview {
  thumbnailTitle: string;
  fileInfoTitle: string;
  dxfDataTitle: string;
  imageDataTitle: string;
  nextStepsTitle: string;
  nextStepsDescription: string;
  fileName: string;
  format: string;
  fileSize: string;
  entities: string;
  layers: string;
  features: string;
  dimensions: string;
  layerList: string;
  moreLayers: string;
  aspectRatio: string;
  transparency: string;
  supported: string;
  notSupported: string;
}

interface I18n_Geocanvas_Georeferencing {
  title: string;
  subtitle: string;
  workspace: string;
  engineDescription: string;
  coordinateTransform: string;
  'steps': I18n_Geocanvas_Georeferencing_Steps;
  'workflow': I18n_Geocanvas_Georeferencing_Workflow;
  'uploadArea': I18n_Geocanvas_Georeferencing_UploadArea;
  'controlPoints': I18n_Geocanvas_Georeferencing_ControlPoints;
  'transformation': I18n_Geocanvas_Georeferencing_Transformation;
  'validation': I18n_Geocanvas_Georeferencing_Validation;
}

interface I18n_Geocanvas_Georeferencing_Steps {
  upload: string;
  points: string;
  transform: string;
  validate: string;
}

interface I18n_Geocanvas_Georeferencing_Workflow {
  step1: string;
  step2: string;
  step3: string;
  step4: string;
}

interface I18n_Geocanvas_Georeferencing_UploadArea {
  title: string;
  description: string;
  dragText: string;
  formats: string;
  button: string;
}

interface I18n_Geocanvas_Georeferencing_ControlPoints {
  title: string;
  description: string;
  count: string;
  addPoint: string;
  removePoint: string;
  accuracy: string;
  status: string;
  none: string;
  minimum: string;
  'features': I18n_Geocanvas_Georeferencing_ControlPoints_Features;
  'coordinates': I18n_Geocanvas_Georeferencing_ControlPoints_Coordinates;
}

interface I18n_Geocanvas_Georeferencing_ControlPoints_Features {
  addEdit: string;
  mapping: string;
  validation: string;
  distribution: string;
}

interface I18n_Geocanvas_Georeferencing_ControlPoints_Coordinates {
  local: string;
  world: string;
  x: string;
  y: string;
  lat: string;
  lng: string;
}

interface I18n_Geocanvas_Georeferencing_Transformation {
  title: string;
  controls: string;
  engine: string;
  method: string;
  'methods': I18n_Geocanvas_Georeferencing_Transformation_Methods;
  execute: string;
  calibrate: string;
  notCalibrated: string;
  'features': I18n_Geocanvas_Georeferencing_Transformation_Features;
  'results': I18n_Geocanvas_Georeferencing_Transformation_Results;
}

interface I18n_Geocanvas_Georeferencing_Transformation_Methods {
  affine: string;
  polynomial: string;
  tps: string;
}

interface I18n_Geocanvas_Georeferencing_Transformation_Features {
  affine: string;
  leastSquares: string;
  rmsCalculation: string;
  inverse: string;
}

interface I18n_Geocanvas_Georeferencing_Transformation_Results {
  title: string;
  accuracy: string;
  rmse: string;
  points: string;
  status: string;
}

interface I18n_Geocanvas_Georeferencing_Validation {
  title: string;
  description: string;
  checkAccuracy: string;
  export: string;
  save: string;
}

interface I18n_Geocanvas_Errors {
  fileUpload: string;
  invalidFile: string;
  insufficientPoints: string;
  transformationFailed: string;
  networkError: string;
  unauthorized: string;
}

interface I18n_Geocanvas_Notifications {
  fileUploaded: string;
  pointAdded: string;
  pointRemoved: string;
  transformationCompleted: string;
  projectSaved: string;
  dataExported: string;
}

interface I18n_Geocanvas_Buttons {
  upload: string;
  add: string;
  remove: string;
  transform: string;
  validate: string;
  save: string;
  export: string;
  cancel: string;
  confirm: string;
  reset: string;
  back: string;
  next: string;
  finish: string;
}

interface I18n_Geocanvas_Loading {
  uploading: string;
  processing: string;
  transforming: string;
  validating: string;
  saving: string;
  loading: string;
}

interface I18n_Geocanvas_CoordinateSystems {
  epsg4326: string;
  epsg3857: string;
  epsg2100: string;
  epsg4230: string;
  custom: string;
}

interface I18n_Geocanvas_Footer {
  poweredBy: string;
  version: string;
  lastUpdate: string;
  support: string;
  documentation: string;
  'status': I18n_Geocanvas_Footer_Status;
}

interface I18n_Geocanvas_Footer_Status {
  active: string;
  phase2DxfTransformation: string;
  georeferencingReady: string;
}

interface I18n_Geocanvas_Progress {
  title: string;
  phase1: string;
  phase1Description: string;
  phase2: string;
  phase2Description: string;
  phase3: string;
  phase3Description: string;
  phase4: string;
  phase4Description: string;
  phase5: string;
  phase5Description: string;
}

interface I18n_Geocanvas_Features {
  title: string;
  controlPointManagement: string;
  affineTransformation: string;
  accuracyValidation: string;
  spatialDistribution: string;
  rmsCalculation: string;
  coordinateTransformation: string;
}

interface I18n_Geocanvas_Technical {
  title: string;
  transformation: string;
  transformationValue: string;
  accuracy: string;
  accuracyValue: string;
  crsSupport: string;
  crsSupportValue: string;
  mathEngine: string;
  mathEngineValue: string;
  standards: string;
  standardsValue: string;
}

interface I18n_Geocanvas_Next {
  title: string;
  maplibre: string;
  interactivePicking: string;
  realtimePreview: string;
  basemapLayers: string;
  visualIndicators: string;
}

interface I18n_Geocanvas_Actions {
  savePoints: string;
  loadPoints: string;
  clearAllPoints: string;
  addPoint: string;
}

interface I18n_Geocanvas_Validation {
  status: string;
  ready: string;
  needsImprovement: string;
  'statistics': I18n_Geocanvas_Validation_Statistics;
  'sections': I18n_Geocanvas_Validation_Sections;
}

interface I18n_Geocanvas_Validation_Statistics {
  controlPoints: string;
  avgAccuracy: string;
  maxError: string;
  distribution: string;
}

interface I18n_Geocanvas_Validation_Sections {
  errors: string;
  warnings: string;
  recommendations: string;
}

interface I18n_Geocanvas_PanelHeader {
  title: string;
  subtitle: string;
}

interface I18n_Geocanvas_Form {
  dxfX: string;
  dxfY: string;
  geoLng: string;
  geoLat: string;
  accuracy: string;
  description: string;
}

interface I18n_Geocanvas_ControlPoints {
  noPointsYet: string;
  addMinimumPoints: string;
  cancel: string;
  addPoint: string;
  savePoints: string;
  loadPoints: string;
  clearAllPoints: string;
}

interface I18n_Geocanvas_Transformation {
  controls: string;
  status: string;
  calibrated: string;
  notCalibrated: string;
  calibrating: string;
  calibrateTransformation: string;
  calibratingButton: string;
}

interface I18n_Geocanvas_Workspace {
  dxfGeoreferencingWorkspace: string;
  phase2Transform: string;
  controlPointsTitle: string;
  'controlPointsFeatures': I18n_Geocanvas_Workspace_ControlPointsFeatures;
  transformationEngineTitle: string;
  'transformationEngineFeatures': I18n_Geocanvas_Workspace_TransformationEngineFeatures;
  nextPhase3: string;
  'nextPhase3Features': I18n_Geocanvas_Workspace_NextPhase3Features;
  workflowInstructions: string;
  'workflowSteps': I18n_Geocanvas_Workspace_WorkflowSteps;
}

interface I18n_Geocanvas_Workspace_ControlPointsFeatures {
  addEdit: string;
  mapping: string;
  accuracyValidation: string;
  spatialDistribution: string;
}

interface I18n_Geocanvas_Workspace_TransformationEngineFeatures {
  affine: string;
  leastSquares: string;
  rmsCalculation: string;
  inverseTransformation: string;
}

interface I18n_Geocanvas_Workspace_NextPhase3Features {
  maplibre: string;
  coordinatePicker: string;
  realtimePreview: string;
  basemapLayers: string;
}

interface I18n_Geocanvas_Workspace_WorkflowSteps {
  step1: string;
  step2: string;
  step3: string;
  step4: string;
}

interface I18n_Geocanvas_Sidebar {
  'phaseProgress': I18n_Geocanvas_Sidebar_PhaseProgress;
  'availableFeatures': I18n_Geocanvas_Sidebar_AvailableFeatures;
  'technicalSpecs': I18n_Geocanvas_Sidebar_TechnicalSpecs;
  'comingNext': I18n_Geocanvas_Sidebar_ComingNext;
}

interface I18n_Geocanvas_Sidebar_PhaseProgress {
  title: string;
  phase1Title: string;
  phase1Description: string;
  phase2Title: string;
  phase2Description: string;
  phase3Title: string;
  phase3Description: string;
  phase4Title: string;
  phase4Description: string;
  phase5Title: string;
  phase5Description: string;
}

interface I18n_Geocanvas_Sidebar_AvailableFeatures {
  title: string;
  controlPointManagement: string;
  affineTransformation: string;
  accuracyValidation: string;
  spatialDistributionAnalysis: string;
  rmsErrorCalculation: string;
  coordinateTransformation: string;
}

interface I18n_Geocanvas_Sidebar_TechnicalSpecs {
  title: string;
  transformation: string;
  transformationValue: string;
  accuracy: string;
  accuracyValue: string;
  crsSupport: string;
  crsSupportValue: string;
  mathEngine: string;
  mathEngineValue: string;
  standards: string;
  standardsValue: string;
}

interface I18n_Geocanvas_Sidebar_ComingNext {
  title: string;
  maplibreIntegration: string;
  interactiveCoordinatePicking: string;
  realtimeTransformationPreview: string;
  multipleBasemapLayers: string;
  visualAccuracyIndicators: string;
}

interface I18n_Geocanvas_ErrorBoundary {
  title: string;
  subtitle: string;
  errorDetails: string;
  errorMessage: string;
  stackTrace: string;
  componentStack: string;
  recoveryOptions: string;
  tryAgain: string;
  reloadPage: string;
  troubleshooting: string;
  'troubleshootingTips': I18n_Geocanvas_ErrorBoundary_TroubleshootingTips;
  developmentMode: string;
  developmentInfo: string;
  systemVersion: string;
  platformName: string;
}

interface I18n_Geocanvas_ErrorBoundary_TroubleshootingTips {
  tip1: string;
  tip2: string;
  tip3: string;
  tip4: string;
}

interface I18n_Geocanvas_PhaseDetails {
  'phase1Features': I18n_Geocanvas_PhaseDetails_Phase1Features;
  'phase2Features': I18n_Geocanvas_PhaseDetails_Phase2Features;
  'architectureOverview': I18n_Geocanvas_PhaseDetails_ArchitectureOverview;
}

interface I18n_Geocanvas_PhaseDetails_Phase1Features {
  foundationStructure: string;
  enterpriseTypeSystem: string;
  configurationSetup: string;
  routerIntegrationReady: string;
}

interface I18n_Geocanvas_PhaseDetails_Phase2Features {
  dxfTransformationEngine: string;
  coordinateSystemSupport: string;
  georeferencingTools: string;
  controlPointManagement: string;
}

interface I18n_Geocanvas_PhaseDetails_ArchitectureOverview {
  title: string;
  centralizedSystem: string;
  technologyStack: string;
  dataFlow: string;
  standards: string;
}

interface I18n_Geocanvas_Map {
  'controls': I18n_Geocanvas_Map_Controls;
  'status': I18n_Geocanvas_Map_Status;
  'coordinates': I18n_Geocanvas_Map_Coordinates;
  'styleSelector': I18n_Geocanvas_Map_StyleSelector;
}

interface I18n_Geocanvas_Map_Controls {
  pickGeographicPoint: string;
  cancelPicking: string;
  cancel: string;
  mapStyle: string;
  clickOnMap: string;
  openStreetMap: string;
  satellite: string;
  terrain: string;
  darkMode: string;
  greece: string;
  watercolor: string;
  toner: string;
}

interface I18n_Geocanvas_Map_Status {
  mapLoaded: string;
  mapLoading: string;
  points: string;
  controlPoints: string;
  avgAccuracy: string;
  best: string;
  accuracy: string;
}

interface I18n_Geocanvas_Map_Coordinates {
  lng: string;
  lat: string;
}

interface I18n_Geocanvas_Map_StyleSelector {
  style: string;
}

interface I18n_Geocanvas_Accuracy {
  legend: string;
  visualization: string;
  'types': I18n_Geocanvas_Accuracy_Types;
  'levels': I18n_Geocanvas_Accuracy_Levels;
  'controls': I18n_Geocanvas_Accuracy_Controls;
  'stats': I18n_Geocanvas_Accuracy_Stats;
}

interface I18n_Geocanvas_Accuracy_Types {
  circles: string;
  zones: string;
}

interface I18n_Geocanvas_Accuracy_Levels {
  excellent: string;
  good: string;
  fair: string;
  poor: string;
  veryPoor: string;
}

interface I18n_Geocanvas_Accuracy_Controls {
  hideIndicators: string;
  showIndicators: string;
}

interface I18n_Geocanvas_Accuracy_Stats {
  avgAccuracy: string;
  best: string;
  format: string;
}

interface I18n_Geocanvas_FloorPlanControlPoints {
  title: string;
  description: string;
  dragHandle: string;
  'tabs': I18n_Geocanvas_FloorPlanControlPoints_Tabs;
  'actions': I18n_Geocanvas_FloorPlanControlPoints_Actions;
  'status': I18n_Geocanvas_FloorPlanControlPoints_Status;
  'instructions': I18n_Geocanvas_FloorPlanControlPoints_Instructions;
  'buttons': I18n_Geocanvas_FloorPlanControlPoints_Buttons;
  'state': I18n_Geocanvas_FloorPlanControlPoints_State;
  'list': I18n_Geocanvas_FloorPlanControlPoints_List;
  'quality': I18n_Geocanvas_FloorPlanControlPoints_Quality;
  'confirm': I18n_Geocanvas_FloorPlanControlPoints_Confirm;
}

interface I18n_Geocanvas_FloorPlanControlPoints_Tabs {
  visualPicking: string;
  manualInput: string;
}

interface I18n_Geocanvas_FloorPlanControlPoints_Actions {
  calibrate: string;
  save: string;
  load: string;
  clear: string;
}

interface I18n_Geocanvas_FloorPlanControlPoints_Status {
  points: string;
  readyForGeoreferencing: string;
  needMorePoints: string;
  transformationQuality: string;
}

interface I18n_Geocanvas_FloorPlanControlPoints_Instructions {
  idle: string;
  pickFloorPlan: string;
  pickGeo: string;
}

interface I18n_Geocanvas_FloorPlanControlPoints_Buttons {
  addControlPoint: string;
  cancel: string;
  clearAll: string;
}

interface I18n_Geocanvas_FloorPlanControlPoints_State {
  idle: string;
  pickingFloorPlan: string;
  pickingGeo: string;
}

interface I18n_Geocanvas_FloorPlanControlPoints_List {
  title: string;
  noPoints: string;
  point: string;
  floorPlan: string;
  geographic: string;
  edit: string;
  delete: string;
  save: string;
  cancel: string;
}

interface I18n_Geocanvas_FloorPlanControlPoints_Quality {
  title: string;
  excellent: string;
  good: string;
  fair: string;
  poor: string;
  rmsError: string;
  maxError: string;
  meanError: string;
  lowAccuracyWarning: string;
}

interface I18n_Geocanvas_FloorPlanControlPoints_Confirm {
  clearAll: string;
  delete: string;
}

interface I18n_Geocanvas_FloorPlanLayer {
  title: string;
  toggle: string;
  show: string;
  hide: string;
  opacity: string;
  position: string;
  scale: string;
  rotation: string;
  'status': I18n_Geocanvas_FloorPlanLayer_Status;
}

interface I18n_Geocanvas_FloorPlanLayer_Status {
  loading: string;
  loaded: string;
  error: string;
  notLoaded: string;
}

interface I18n_Geocanvas_UserTypeSelector {
  title: string;
  currentType: string;
  changeType: string;
  'types': I18n_Geocanvas_UserTypeSelector_Types;
}

interface I18n_Geocanvas_UserTypeSelector_Types {
  'citizen': I18n_Geocanvas_UserTypeSelector_Types_Citizen;
  'professional': I18n_Geocanvas_UserTypeSelector_Types_Professional;
  'technical': I18n_Geocanvas_UserTypeSelector_Types_Technical;
}

interface I18n_Geocanvas_UserTypeSelector_Types_Citizen {
  title: string;
  description: string;
}

interface I18n_Geocanvas_UserTypeSelector_Types_Professional {
  title: string;
  description: string;
}

interface I18n_Geocanvas_UserTypeSelector_Types_Technical {
  title: string;
  description: string;
}

interface I18n_Geocanvas_PropertyStatusManager {
  title: string;
  subtitle: string;
  'colorScheme': I18n_Geocanvas_PropertyStatusManager_ColorScheme;
  statusCategories: string;
  selectAll: string;
  selectNone: string;
  hide: string;
  show: string;
  'statistics': I18n_Geocanvas_PropertyStatusManager_Statistics;
  'tips': I18n_Geocanvas_PropertyStatusManager_Tips;
}

interface I18n_Geocanvas_PropertyStatusManager_ColorScheme {
  title: string;
  status: string;
  price: string;
  type: string;
}

interface I18n_Geocanvas_PropertyStatusManager_Statistics {
  title: string;
  visibleStatus: string;
  scheme: string;
}

interface I18n_Geocanvas_PropertyStatusManager_Tips {
  title: string;
  description: string;
}

interface I18n_Geocanvas_RealEstateMonitoring {
  title: string;
  'stats': I18n_Geocanvas_RealEstateMonitoring_Stats;
  'actions': I18n_Geocanvas_RealEstateMonitoring_Actions;
  'tips': I18n_Geocanvas_RealEstateMonitoring_Tips;
}

interface I18n_Geocanvas_RealEstateMonitoring_Stats {
  monitoringZones: string;
  propertiesFound: string;
  avgConfidence: string;
  lastScan: string;
}

interface I18n_Geocanvas_RealEstateMonitoring_Actions {
  batchMode: string;
  monitorAll: string;
  exportCsv: string;
}

interface I18n_Geocanvas_RealEstateMonitoring_Tips {
  title: string;
  batchMode: string;
  export: string;
  realtime: string;
}

interface I18n_Geocanvas_ToastMessages {
  invalidCoordinates: string;
  pointAddedManually: string;
  errorAddingPoint: string;
  needMinimumPoints: string;
  calibrationComplete: string;
  noPointsToSave: string;
  pointsSaved: string;
  pointsLoaded: string;
  invalidPointsFile: string;
  errorLoadingFile: string;
}

interface I18n_Geocanvas_LoadingStates {
  loadingTranslations: string;
  loading: string;
}

interface I18n_Geocanvas_PhaseInformation {
  foundationStructure: string;
  enterpriseTypeSystem: string;
  configurationSetup: string;
  routerIntegrationReady: string;
  dxfTransformationEngine: string;
  coordinateSystemSupport: string;
  georeferencingTools: string;
  controlPointManagement: string;
  architectureOverview: string;
  centralizedSystem: string;
  technologyStack: string;
  dataFlow: string;
  standards: string;
}

interface I18n_Geocanvas_DrawingInterfaces {
  'common': I18n_Geocanvas_DrawingInterfaces_Common;
  'technical': I18n_Geocanvas_DrawingInterfaces_Technical;
  'professional': I18n_Geocanvas_DrawingInterfaces_Professional;
  'citizen': I18n_Geocanvas_DrawingInterfaces_Citizen;
}

interface I18n_Geocanvas_DrawingInterfaces_Common {
  cancel: string;
  complete: string;
  automatically: string;
  from: string;
  to: string;
  floorPlan: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Technical {
  title: string;
  subtitle: string;
  'tools': I18n_Geocanvas_DrawingInterfaces_Technical_Tools;
  'automatedAlerts': I18n_Geocanvas_DrawingInterfaces_Technical_AutomatedAlerts;
  'specifications': I18n_Geocanvas_DrawingInterfaces_Technical_Specifications;
  'actions': I18n_Geocanvas_DrawingInterfaces_Technical_Actions;
  'instructions': I18n_Geocanvas_DrawingInterfaces_Technical_Instructions;
  openViewer: string;
  cadEnvironment: string;
  fullDxfViewer: string;
  ultraPrecision: string;
  advancedSettings: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Technical_Tools {
  precision: string;
  settings: string;
  settingsAdvanced: string;
  alertsAuto: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Technical_AutomatedAlerts {
  title: string;
  detectionSensitivity: string;
  monitoringInterval: string;
  morePlatforms: string;
  technicalSpecifications: string;
  'sensitivity': I18n_Geocanvas_DrawingInterfaces_Technical_AutomatedAlerts_Sensitivity;
  'intervals': I18n_Geocanvas_DrawingInterfaces_Technical_AutomatedAlerts_Intervals;
}

interface I18n_Geocanvas_DrawingInterfaces_Technical_AutomatedAlerts_Sensitivity {
  high: string;
  medium: string;
  low: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Technical_AutomatedAlerts_Intervals {
  realtime: string;
  frequent: string;
  standard: string;
  hourly: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Technical_Specifications {
  title: string;
  accuracy: string;
  coordinates: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Technical_Actions {
  complete: string;
  cancel: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Technical_Instructions {
  precision: string;
  settings: string;
  automatedAlerts: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Professional {
  title: string;
  subtitle: string;
  'tools': I18n_Geocanvas_DrawingInterfaces_Professional_Tools;
  uploadFloorPlan: string;
  addPropertyPoints: string;
  autoDetectRooms: string;
  propertyManager: string;
  marketDashboard: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Professional_Tools {
  property: string;
  propertyManual: string;
  autoDetectAuto: string;
  monitoringMarket: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Citizen {
  title: string;
  subtitle: string;
  'tools': I18n_Geocanvas_DrawingInterfaces_Citizen_Tools;
  'actions': I18n_Geocanvas_DrawingInterfaces_Citizen_Actions;
  'instructions': I18n_Geocanvas_DrawingInterfaces_Citizen_Instructions;
  'realEstateSetup': I18n_Geocanvas_DrawingInterfaces_Citizen_RealEstateSetup;
  placePoint: string;
  addPolygonPoints: string;
  drawFreehand: string;
  drawInterestArea: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Citizen_Tools {
  point: string;
  pointDescription: string;
  polygon: string;
  polygonDescription: string;
  freehand: string;
  freehandDrawing: string;
  realEstate: string;
  realEstateDescription: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Citizen_Actions {
  complete: string;
  cancel: string;
  drawArea: string;
  clearAll: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Citizen_Instructions {
  realEstate: string;
}

interface I18n_Geocanvas_DrawingInterfaces_Citizen_RealEstateSetup {
  title: string;
  propertyType: string;
  'propertyTypes': I18n_Geocanvas_DrawingInterfaces_Citizen_RealEstateSetup_PropertyTypes;
}

interface I18n_Geocanvas_DrawingInterfaces_Citizen_RealEstateSetup_PropertyTypes {
  apartment: string;
  house: string;
  land: string;
  commercial: string;
}

interface I18n_Geocanvas_MapStatus {
  polygonClosed: string;
  clickToClose: string;
}

interface I18n_Geocanvas_HardcodedTexts {
  'ui': I18n_Geocanvas_HardcodedTexts_Ui;
  'labels': I18n_Geocanvas_HardcodedTexts_Labels;
  'actions': I18n_Geocanvas_HardcodedTexts_Actions;
  'placeholders': I18n_Geocanvas_HardcodedTexts_Placeholders;
  'values': I18n_Geocanvas_HardcodedTexts_Values;
}

interface I18n_Geocanvas_HardcodedTexts_Ui {
  upload: string;
  properties: string;
  status: string;
  monitor: string;
  alerts: string;
  autoDetect: string;
  dxfViewer: string;
  fullCad: string;
  show: string;
  start: string;
  stop: string;
  cancel: string;
  precision: string;
  technical: string;
  processing: string;
  confidence: string;
  monitoring: string;
}

interface I18n_Geocanvas_HardcodedTexts_Labels {
  dxfEntities: string;
  controlPoints: string;
  accuracyCircles: string;
  grid: string;
  transformed: string;
  errors: string;
  rmsAccuracy: string;
  technicalSensitivity: string;
  monitoringPlatforms: string;
  monitoringZones: string;
  detectedProperties: string;
  lastScan: string;
  technicalMatches: string;
  automatedAlerts: string;
  precisionLabel: string;
  georeferencing: string;
  confidenceThreshold: string;
  processingLabel: string;
  formats: string;
  cadTools: string;
  dxfViewerLabel: string;
}

interface I18n_Geocanvas_HardcodedTexts_Actions {
  automateAll: string;
  startMonitoring: string;
  stopAll: string;
  showDxfEntities: string;
  showControlPoints: string;
  showAccuracyCircles: string;
  showGrid: string;
}

interface I18n_Geocanvas_HardcodedTexts_Placeholders {
  optionalDescription: string;
  coordinates: string;
  longitude: string;
  latitude: string;
  accuracy: string;
}

interface I18n_Geocanvas_HardcodedTexts_Values {
  uploaded: string;
  millimeterLevel: string;
  wgs84LocalGrid: string;
  realtimeAutomated: string;
  dxfDwg: string;
  full: string;
  comingSoon: string;
  spitogatosGr: string;
  xeGr: string;
}

interface I18n_Geocanvas_CitizenDrawingInterface {
  'priceRange': I18n_Geocanvas_CitizenDrawingInterface_PriceRange;
}

interface I18n_Geocanvas_CitizenDrawingInterface_PriceRange {
  label: string;
}

interface I18n_Geocanvas_AlertDashboard {
  title: string;
}

interface I18n_Geocanvas_UserActions {
  changeUserType: string;
}

interface I18n_Geocanvas_Instructions {
  'citizen': I18n_Geocanvas_Instructions_Citizen;
}

interface I18n_Geocanvas_Instructions_Citizen {
  placePoint: string;
  addPolygonPoints: string;
  drawFreehand: string;
}

interface I18n_Landing {
  'hero': I18n_Landing_Hero;
  'search': I18n_Landing_Search;
  'features': I18n_Landing_Features;
  'stats': I18n_Landing_Stats;
  'cta': I18n_Landing_Cta;
}

interface I18n_Landing_Hero {
  findIdeal: string;
  property: string;
  subtitle: string;
}

interface I18n_Landing_Search {
  propertyType: string;
  location: string;
  priceRange: string;
  areaRange: string;
  allTypes: string;
  locationPlaceholder: string;
  searchButton: string;
  'types': I18n_Landing_Search_Types;
  'priceRanges': I18n_Landing_Search_PriceRanges;
  'areaRanges': I18n_Landing_Search_AreaRanges;
}

interface I18n_Landing_Search_Types {
  studio: string;
  studio2: string;
  apartment: string;
  maisonette: string;
  storage: string;
}

interface I18n_Landing_Search_PriceRanges {
  up50k: string;
  '50k100k': string;
  '100k200k': string;
  '200k500k': string;
  above500k: string;
}

interface I18n_Landing_Search_AreaRanges {
  up50: string;
  '50to100': string;
  '100to150': string;
  above150: string;
}

interface I18n_Landing_Features {
  title: string;
  subtitle: string;
  'professionalService': I18n_Landing_Features_ProfessionalService;
  'premiumLocations': I18n_Landing_Features_PremiumLocations;
  'trustedPartner': I18n_Landing_Features_TrustedPartner;
}

interface I18n_Landing_Features_ProfessionalService {
  title: string;
  description: string;
}

interface I18n_Landing_Features_PremiumLocations {
  title: string;
  description: string;
}

interface I18n_Landing_Features_TrustedPartner {
  title: string;
  description: string;
}

interface I18n_Landing_Stats {
  properties: string;
  clients: string;
  years: string;
}

interface I18n_Landing_Cta {
  title: string;
  description: string;
  contactUs: string;
  exploreProperties: string;
}

interface I18n_Navigation {
  'menu': I18n_Navigation_Menu;
  'pages': I18n_Navigation_Pages;
  'crm': I18n_Navigation_Crm;
  'tools': I18n_Navigation_Tools;
  'badges': I18n_Navigation_Badges;
  'user': I18n_Navigation_User;
}

interface I18n_Navigation_Menu {
  main: string;
  tools: string;
  settings: string;
}

interface I18n_Navigation_Pages {
  home: string;
  properties: string;
  contacts: string;
  projects: string;
  buildings: string;
  units: string;
  crm: string;
  login: string;
}

interface I18n_Navigation_Crm {
  dashboard: string;
  customers: string;
  communications: string;
  leads: string;
  tasks: string;
  pipeline: string;
  teams: string;
  notifications: string;
}

interface I18n_Navigation_Tools {
  legal: string;
  obligations: string;
  dxf: string;
  shortcuts: string;
  geoCanvas: string;
}

interface I18n_Navigation_Badges {
  new: string;
  pro: string;
  enterprise: string;
}

interface I18n_Navigation_User {
  title: string;
  name: string;
  email: string;
}

interface I18n_Projects {
  title: string;
  description: string;
  'toolbar': I18n_Projects_Toolbar;
  'card': I18n_Projects_Card;
  'messages': I18n_Projects_Messages;
}

interface I18n_Projects_Toolbar {
  new: string;
  edit: string;
  delete: string;
  export: string;
  import: string;
  refresh: string;
  archive: string;
  favorite: string;
  share: string;
  mapView: string;
  help: string;
  'search': I18n_Projects_Toolbar_Search;
  'filters': I18n_Projects_Toolbar_Filters;
  'selection': I18n_Projects_Toolbar_Selection;
  'shortcuts': I18n_Projects_Toolbar_Shortcuts;
}

interface I18n_Projects_Toolbar_Search {
  placeholder: string;
}

interface I18n_Projects_Toolbar_Filters {
  'status': I18n_Projects_Toolbar_Filters_Status;
  'type': I18n_Projects_Toolbar_Filters_Type;
  'sort': I18n_Projects_Toolbar_Filters_Sort;
}

interface I18n_Projects_Toolbar_Filters_Status {
  label: string;
  inProgress: string;
  planning: string;
  completed: string;
  onHold: string;
}

interface I18n_Projects_Toolbar_Filters_Type {
  label: string;
  residential: string;
  commercial: string;
  infrastructure: string;
}

interface I18n_Projects_Toolbar_Filters_Sort {
  label: string;
  ascending: string;
  descending: string;
  byDate: string;
  byCompletion: string;
  byPriority: string;
}

interface I18n_Projects_Toolbar_Selection {
  selected: string;
  deleteConfirm: string;
}

interface I18n_Projects_Toolbar_Shortcuts {
  newProject: string;
  editProject: string;
  refresh: string;
  help: string;
}

interface I18n_Projects_Card {
  'status': I18n_Projects_Card_Status;
  'priority': I18n_Projects_Card_Priority;
  'details': I18n_Projects_Card_Details;
  'actions': I18n_Projects_Card_Actions;
}

interface I18n_Projects_Card_Status {
  planning: string;
  inProgress: string;
  completed: string;
  onHold: string;
  cancelled: string;
}

interface I18n_Projects_Card_Priority {
  low: string;
  medium: string;
  high: string;
  urgent: string;
}

interface I18n_Projects_Card_Details {
  startDate: string;
  endDate: string;
  budget: string;
  progress: string;
  team: string;
  location: string;
  description: string;
}

interface I18n_Projects_Card_Actions {
  view: string;
  edit: string;
  duplicate: string;
  delete: string;
  archive: string;
  addToFavorites: string;
}

interface I18n_Projects_Messages {
  created: string;
  updated: string;
  deleted: string;
  archived: string;
  exported: string;
  noProjects: string;
  loadingError: string;
}

interface I18n_Properties {
  'building': I18n_Properties_Building;
  'units': I18n_Properties_Units;
  'search': I18n_Properties_Search;
  'filters': I18n_Properties_Filters;
  'projects': I18n_Properties_Projects;
}

interface I18n_Properties_Building {
  'toolbar': I18n_Properties_Building_Toolbar;
  'dialog': I18n_Properties_Building_Dialog;
  'storage': I18n_Properties_Building_Storage;
}

interface I18n_Properties_Building_Toolbar {
  'actions': I18n_Properties_Building_Toolbar_Actions;
}

interface I18n_Properties_Building_Toolbar_Actions {
  new: string;
  edit: string;
  delete: string;
}

interface I18n_Properties_Building_Dialog {
  'deleteConfirmation': I18n_Properties_Building_Dialog_DeleteConfirmation;
  cancel: string;
  delete: string;
}

interface I18n_Properties_Building_Dialog_DeleteConfirmation {
  title: string;
  message: string;
  warning: string;
}

interface I18n_Properties_Building_Storage {
  'types': I18n_Properties_Building_Storage_Types;
  'status': I18n_Properties_Building_Storage_Status;
  'form': I18n_Properties_Building_Storage_Form;
}

interface I18n_Properties_Building_Storage_Types {
  storage: string;
  parking: string;
}

interface I18n_Properties_Building_Storage_Status {
  available: string;
  reserved: string;
  sold: string;
  owner: string;
  maintenance: string;
}

interface I18n_Properties_Building_Storage_Form {
  basicInfo: string;
  code: string;
  status: string;
  description: string;
  area: string;
  price: string;
  floor: string;
  auto: string;
  'placeholders': I18n_Properties_Building_Storage_Form_Placeholders;
}

interface I18n_Properties_Building_Storage_Form_Placeholders {
  codeStorage: string;
  codeParking: string;
  descriptionStorage: string;
  descriptionParking: string;
}

interface I18n_Properties_Units {
  'types': I18n_Properties_Units_Types;
}

interface I18n_Properties_Units_Types {
  studio: string;
  apartment_1br: string;
  apartment_2br: string;
  apartment_3br: string;
  maisonette: string;
  shop: string;
  storage: string;
}

interface I18n_Properties_Search {
  'results': I18n_Properties_Search_Results;
  'terms': I18n_Properties_Search_Terms;
}

interface I18n_Properties_Search_Results {
  found: string;
  error: string;
}

interface I18n_Properties_Search_Terms {
  thousands: string;
  available: string;
  sold: string;
  reserved: string;
  apartment: string;
  maisonette: string;
  shop: string;
  parking: string;
  storage: string;
}

interface I18n_Properties_Filters {
  'advanced': I18n_Properties_Filters_Advanced;
}

interface I18n_Properties_Filters_Advanced {
  show: string;
  hide: string;
  'features': I18n_Properties_Filters_Advanced_Features;
}

interface I18n_Properties_Filters_Advanced_Features {
  parking: string;
  storage: string;
  fireplace: string;
  view: string;
  pool: string;
}

interface I18n_Properties_Projects {
  'buildingData': I18n_Properties_Projects_BuildingData;
}

interface I18n_Properties_Projects_BuildingData {
  title: string;
  'fields': I18n_Properties_Projects_BuildingData_Fields;
  'formulas': I18n_Properties_Projects_BuildingData_Formulas;
}

interface I18n_Properties_Projects_BuildingData_Fields {
  maxAllowedConstruction: string;
  maxCoveragePercentage: string;
  maxPlotCoverage: string;
  maxSemiOutdoorPercentage: string;
  maxAllowedSemiOutdoorArea: string;
  maxBalconyPercentage: string;
  maxBalconyArea: string;
  maxCombinedPercentage: string;
  maxCombinedArea: string;
  maxVolumeCoefficient: string;
  maxVolumeExploitation: string;
  maxAllowedHeight: string;
}

interface I18n_Properties_Projects_BuildingData_Formulas {
  construction: string;
  plotCoverage: string;
  semiOutdoor: string;
  balcony: string;
  combined: string;
  volume: string;
}

interface I18n_Tasks {
  title: string;
  description: string;
  'types': I18n_Tasks_Types;
  'status': I18n_Tasks_Status;
  'priority': I18n_Tasks_Priority;
  'card': I18n_Tasks_Card;
  'time': I18n_Tasks_Time;
  'form': I18n_Tasks_Form;
  'filters': I18n_Tasks_Filters;
  'messages': I18n_Tasks_Messages;
  'notifications': I18n_Tasks_Notifications;
}

interface I18n_Tasks_Types {
  call: string;
  email: string;
  meeting: string;
  viewing: string;
  followup: string;
  research: string;
  documentation: string;
  other: string;
}

interface I18n_Tasks_Status {
  pending: string;
  in_progress: string;
  completed: string;
  cancelled: string;
  overdue: string;
}

interface I18n_Tasks_Priority {
  low: string;
  medium: string;
  high: string;
  urgent: string;
}

interface I18n_Tasks_Card {
  'details': I18n_Tasks_Card_Details;
  'viewing': I18n_Tasks_Card_Viewing;
  'actions': I18n_Tasks_Card_Actions;
}

interface I18n_Tasks_Card_Details {
  assignedTo: string;
  dueDate: string;
  createdAt: string;
  updatedAt: string;
  completedAt: string;
  estimatedTime: string;
  actualTime: string;
}

interface I18n_Tasks_Card_Viewing {
  location: string;
  units: string;
  attendees: string;
  notes: string;
}

interface I18n_Tasks_Card_Actions {
  view: string;
  edit: string;
  complete: string;
  delete: string;
  duplicate: string;
  addToFavorites: string;
}

interface I18n_Tasks_Time {
  overdue: string;
  today: string;
  tomorrow: string;
  thisWeek: string;
  nextWeek: string;
  daysAgo: string;
  hoursAgo: string;
  minutesAgo: string;
  justNow: string;
}

interface I18n_Tasks_Form {
  title: string;
  description: string;
  type: string;
  priority: string;
  assignee: string;
  dueDate: string;
  contact: string;
  project: string;
  tags: string;
  notes: string;
  attachments: string;
  reminders: string;
}

interface I18n_Tasks_Filters {
  all: string;
  myTasks: string;
  pending: string;
  overdue: string;
  completed: string;
  highPriority: string;
  dueToday: string;
  dueThisWeek: string;
}

interface I18n_Tasks_Messages {
  created: string;
  updated: string;
  completed: string;
  deleted: string;
  assigned: string;
  duplicated: string;
  noTasks: string;
  loadingError: string;
  saveError: string;
}

interface I18n_Tasks_Notifications {
  reminder: string;
  overdue: string;
  assigned: string;
  completed: string;
  dueSoon: string;
}

interface I18n_Toasts {
  'success': I18n_Toasts_Success;
  'error': I18n_Toasts_Error;
  'loading': I18n_Toasts_Loading;
}

interface I18n_Toasts_Success {
  saved: string;
  deleted: string;
  updated: string;
}

interface I18n_Toasts_Error {
  general: string;
  network: string;
  validation: string;
}

interface I18n_Toasts_Loading {
  saving: string;
  loading: string;
  deleting: string;
}

interface I18n_Toolbars {
  title: string;
  description: string;
  'common': I18n_Toolbars_Common;
  'buildings': I18n_Toolbars_Buildings;
  'contacts': I18n_Toolbars_Contacts;
  'validation': I18n_Toolbars_Validation;
  'messages': I18n_Toolbars_Messages;
}

interface I18n_Toolbars_Common {
  'actions': I18n_Toolbars_Common_Actions;
  'search': I18n_Toolbars_Common_Search;
  'filters': I18n_Toolbars_Common_Filters;
  'sort': I18n_Toolbars_Common_Sort;
  'selection': I18n_Toolbars_Common_Selection;
  'shortcuts': I18n_Toolbars_Common_Shortcuts;
}

interface I18n_Toolbars_Common_Actions {
  new: string;
  edit: string;
  delete: string;
  export: string;
  import: string;
  refresh: string;
  archive: string;
  favorite: string;
  share: string;
  help: string;
}

interface I18n_Toolbars_Common_Search {
  placeholder: string;
  clear: string;
}

interface I18n_Toolbars_Common_Filters {
  label: string;
  clear: string;
  clearAll: string;
  active: string;
}

interface I18n_Toolbars_Common_Sort {
  label: string;
  ascending: string;
  descending: string;
  byName: string;
  byDate: string;
  byStatus: string;
}

interface I18n_Toolbars_Common_Selection {
  selected: string;
  selectAll: string;
  deselectAll: string;
}

interface I18n_Toolbars_Common_Shortcuts {
  newItem: string;
  editItem: string;
  deleteItem: string;
  refresh: string;
  help: string;
}

interface I18n_Toolbars_Buildings {
  title: string;
  'search': I18n_Toolbars_Buildings_Search;
  'filters': I18n_Toolbars_Buildings_Filters;
  'actions': I18n_Toolbars_Buildings_Actions;
  'selection': I18n_Toolbars_Buildings_Selection;
}

interface I18n_Toolbars_Buildings_Search {
  placeholder: string;
}

interface I18n_Toolbars_Buildings_Filters {
  'status': I18n_Toolbars_Buildings_Filters_Status;
  'type': I18n_Toolbars_Buildings_Filters_Type;
}

interface I18n_Toolbars_Buildings_Filters_Status {
  label: string;
  active: string;
  inactive: string;
  maintenance: string;
}

interface I18n_Toolbars_Buildings_Filters_Type {
  label: string;
  residential: string;
  commercial: string;
  mixed: string;
}

interface I18n_Toolbars_Buildings_Actions {
  newBuilding: string;
  editBuilding: string;
  deleteBuilding: string;
}

interface I18n_Toolbars_Buildings_Selection {
  selected: string;
}

interface I18n_Toolbars_Contacts {
  title: string;
  'search': I18n_Toolbars_Contacts_Search;
  'filters': I18n_Toolbars_Contacts_Filters;
  'actions': I18n_Toolbars_Contacts_Actions;
  'selection': I18n_Toolbars_Contacts_Selection;
}

interface I18n_Toolbars_Contacts_Search {
  placeholder: string;
}

interface I18n_Toolbars_Contacts_Filters {
  'type': I18n_Toolbars_Contacts_Filters_Type;
  'status': I18n_Toolbars_Contacts_Filters_Status;
}

interface I18n_Toolbars_Contacts_Filters_Type {
  label: string;
  individual: string;
  company: string;
  organization: string;
}

interface I18n_Toolbars_Contacts_Filters_Status {
  label: string;
  active: string;
  inactive: string;
  potential: string;
}

interface I18n_Toolbars_Contacts_Actions {
  newContact: string;
  editContact: string;
  deleteContact: string;
  call: string;
  email: string;
}

interface I18n_Toolbars_Contacts_Selection {
  selected: string;
}

interface I18n_Toolbars_Validation {
  required: string;
  invalidSelection: string;
  noItemsSelected: string;
}

interface I18n_Toolbars_Messages {
  actionSuccess: string;
  actionError: string;
  exportSuccess: string;
  importSuccess: string;
  refreshSuccess: string;
}

interface I18n_Units {
  'management': I18n_Units_Management;
  'tooltips': I18n_Units_Tooltips;
  'actions': I18n_Units_Actions;
  'types': I18n_Units_Types;
  'status': I18n_Units_Status;
}

interface I18n_Units_Management {
  title: string;
  subtitle: string;
}

interface I18n_Units_Tooltips {
  dashboard: string;
  listView: string;
  gridView: string;
  groupByType: string;
  groupByStatus: string;
}

interface I18n_Units_Actions {
  groupByType: string;
  groupByStatus: string;
  newUnit: string;
}

interface I18n_Units_Types {
  studio: string;
  apartment_1br: string;
  apartment_2br: string;
  apartment_3br: string;
  maisonette: string;
  shop: string;
  storage: string;
}

interface I18n_Units_Status {
  available: string;
  reserved: string;
  sold: string;
  owner: string;
}

interface I18n_Users {
  title: string;
  description: string;
  'roles': I18n_Users_Roles;
  'status': I18n_Users_Status;
  'card': I18n_Users_Card;
  'form': I18n_Users_Form;
  'filters': I18n_Users_Filters;
  'search': I18n_Users_Search;
  'bulk': I18n_Users_Bulk;
  'messages': I18n_Users_Messages;
  'confirmations': I18n_Users_Confirmations;
}

interface I18n_Users_Roles {
  admin: string;
  manager: string;
  agent: string;
  user: string;
  viewer: string;
}

interface I18n_Users_Status {
  active: string;
  inactive: string;
  pending: string;
  suspended: string;
}

interface I18n_Users_Card {
  'sections': I18n_Users_Card_Sections;
  'details': I18n_Users_Card_Details;
  'activity': I18n_Users_Card_Activity;
  'stats': I18n_Users_Card_Stats;
  'actions': I18n_Users_Card_Actions;
}

interface I18n_Users_Card_Sections {
  contact: string;
  location: string;
  activity: string;
  statistics: string;
  specialties: string;
}

interface I18n_Users_Card_Details {
  email: string;
  phone: string;
  company: string;
  location: string;
  department: string;
  lastActive: string;
  joinedDate: string;
  bio: string;
  tasksCompleted: string;
  projectsAssigned: string;
  achievements: string;
}

interface I18n_Users_Card_Activity {
  lastActive: string;
  joinedDate: string;
  today: string;
  yesterday: string;
  daysAgo: string;
  weeksAgo: string;
  never: string;
  notSet: string;
}

interface I18n_Users_Card_Stats {
  tasks: string;
  projects: string;
  achievements: string;
}

interface I18n_Users_Card_Actions {
  view: string;
  message: string;
  edit: string;
  deactivate: string;
  activate: string;
  delete: string;
  resetPassword: string;
  addToFavorites: string;
}

interface I18n_Users_Form {
  'basicInfo': I18n_Users_Form_BasicInfo;
  'profile': I18n_Users_Form_Profile;
  'security': I18n_Users_Form_Security;
}

interface I18n_Users_Form_BasicInfo {
  title: string;
  name: string;
  email: string;
  phone: string;
  role: string;
  department: string;
  company: string;
  location: string;
}

interface I18n_Users_Form_Profile {
  title: string;
  avatar: string;
  bio: string;
  specialties: string;
  skills: string;
  certifications: string;
}

interface I18n_Users_Form_Security {
  title: string;
  status: string;
  permissions: string;
  lastLogin: string;
  passwordReset: string;
}

interface I18n_Users_Filters {
  all: string;
  active: string;
  inactive: string;
  admins: string;
  managers: string;
  agents: string;
  recentlyActive: string;
  newUsers: string;
}

interface I18n_Users_Search {
  placeholder: string;
  byName: string;
  byEmail: string;
  byRole: string;
  byDepartment: string;
}

interface I18n_Users_Bulk {
  selected: string;
  'actions': I18n_Users_Bulk_Actions;
}

interface I18n_Users_Bulk_Actions {
  activate: string;
  deactivate: string;
  delete: string;
  export: string;
  assignRole: string;
  sendMessage: string;
}

interface I18n_Users_Messages {
  created: string;
  updated: string;
  deleted: string;
  activated: string;
  deactivated: string;
  passwordReset: string;
  messageSent: string;
  noUsers: string;
  loadingError: string;
  saveError: string;
}

interface I18n_Users_Confirmations {
  delete: string;
  deactivate: string;
  resetPassword: string;
  bulkAction: string;
}

export interface I18nKeys {
  'auth': I18n_Auth;
  'building': I18n_Building;
  'common': I18n_Common;
  'compositions': I18n_Compositions;
  'contacts': I18n_Contacts;
  'crm': I18n_Crm;
  'dashboard': I18n_Dashboard;
  'dxf-viewer': I18n_Dxfviewer;
  'errors': I18n_Errors;
  'forms': I18n_Forms;
  'geo-canvas': I18n_Geocanvas;
  'landing': I18n_Landing;
  'navigation': I18n_Navigation;
  'projects': I18n_Projects;
  'properties': I18n_Properties;
  'tasks': I18n_Tasks;
  'toasts': I18n_Toasts;
  'toolbars': I18n_Toolbars;
  'units': I18n_Units;
  'users': I18n_Users;
}

export type TranslationNamespace = 'auth' | 'building' | 'common' | 'compositions' | 'contacts' | 'crm' | 'dashboard' | 'dxf-viewer' | 'errors' | 'forms' | 'geo-canvas' | 'landing' | 'navigation' | 'projects' | 'properties' | 'tasks' | 'toasts' | 'toolbars' | 'units' | 'users';

/**
 * Utility type for nested translation keys
 */
export type NestedKeyOf<ObjectType extends object> = {
  [Key in keyof ObjectType & (string | number)]: ObjectType[Key] extends object
    ? `${Key}.${NestedKeyOf<ObjectType[Key]>}`
    : `${Key}`
}[keyof ObjectType & (string | number)];

/**
 * All available translation keys in dot notation
 */
export type TranslationKey = NestedKeyOf<I18nKeys>;
