/**
 * @fileoverview Banking Types for Contacts
 * @description Enterprise-grade banking account types for all contact types
 * @author Claude Code (Anthropic AI) + Γιώργος Παγώνης
 * @created 2026-02-01
 * @version 1.0.0
 * @compliance CLAUDE.md Enterprise Standards
 */

// ============================================================================
// CORE TYPES
// ============================================================================

/**
 * Account types for bank accounts
 * Matches Greek banking terminology
 */
export type AccountType = 'checking' | 'savings' | 'business' | 'other';

/**
 * Account type labels for UI display (Greek)
 */
export const ACCOUNT_TYPE_LABELS: Record<AccountType, string> = {
  checking: 'Τρεχούμενος',
  savings: 'Ταμιευτηρίου',
  business: 'Επαγγελματικός',
  other: 'Άλλος'
} as const;

/**
 * ISO 4217 Currency codes commonly used in Greece
 */
export type CurrencyCode = 'EUR' | 'USD' | 'GBP' | 'CHF';

/**
 * Currency labels for UI display
 */
export const CURRENCY_LABELS: Record<CurrencyCode, string> = {
  EUR: 'Ευρώ (EUR)',
  USD: 'Δολάριο ΗΠΑ (USD)',
  GBP: 'Λίρα Αγγλίας (GBP)',
  CHF: 'Ελβετικό Φράγκο (CHF)'
} as const;

// ============================================================================
// BANK INFO INTERFACE
// ============================================================================

/**
 * Bank information structure
 * Used for bank catalog and IBAN parsing
 */
export interface BankInfo {
  /** SWIFT/BIC code (8 or 11 characters) */
  code: string;
  /** Bank name (Greek) */
  name: string;
  /** Country ISO code */
  country: string;
  /** City of headquarters (optional) */
  city?: string;
  /** Bank's primary color for UI (optional) */
  brandColor?: string;
}

// ============================================================================
// BANK ACCOUNT INTERFACE
// ============================================================================

/**
 * Bank Account structure for Firestore subcollection
 *
 * Firestore path: contacts/{contactId}/bankAccounts/{accountId}
 *
 * @example
 * ```typescript
 * const account: BankAccount = {
 *   id: 'abc123',
 *   bankName: 'Εθνική Τράπεζα',
 *   bankCode: 'ETHNGRAA',
 *   iban: 'GR1601101250000000012300695',
 *   accountType: 'checking',
 *   currency: 'EUR',
 *   isPrimary: true,
 *   isActive: true,
 *   createdAt: new Date(),
 *   updatedAt: new Date()
 * };
 * ```
 */
export interface BankAccount {
  /** Unique identifier (auto-generated by Firestore) */
  id: string;

  /** Bank name (e.g., "Εθνική Τράπεζα") */
  bankName: string;

  /** SWIFT/BIC code (e.g., "ETHNGRAA") - optional for non-Greek banks */
  bankCode?: string;

  /** IBAN (validated, stored without spaces) */
  iban: string;

  /** Legacy account number (optional, for reference) */
  accountNumber?: string;

  /** Account type */
  accountType: AccountType;

  /** Currency ISO code (default: EUR) */
  currency: CurrencyCode;

  /** Whether this is the primary account for the contact */
  isPrimary: boolean;

  /** Account holder name (for joint accounts or different holder) */
  holderName?: string;

  /** Additional notes */
  notes?: string;

  /** Whether the account is active */
  isActive: boolean;

  /** Creation timestamp */
  createdAt: Date;

  /** Last update timestamp */
  updatedAt: Date;
}

/**
 * Input type for creating a new bank account
 * Omits auto-generated fields
 */
export type BankAccountInput = Omit<BankAccount, 'id' | 'createdAt' | 'updatedAt'>;

/**
 * Input type for updating a bank account
 * All fields optional except id
 */
export type BankAccountUpdate = Partial<Omit<BankAccount, 'id' | 'createdAt' | 'updatedAt'>>;

// ============================================================================
// IBAN VALIDATION & FORMATTING
// ============================================================================

/**
 * IBAN validation result
 */
export interface IBANValidationResult {
  valid: boolean;
  error?: string;
  countryCode?: string;
  checkDigits?: string;
  bankCode?: string;
  accountNumber?: string;
}

/**
 * IBAN country configurations
 * length: expected IBAN length for the country
 */
const IBAN_COUNTRY_CONFIG: Record<string, { length: number; name: string }> = {
  GR: { length: 27, name: 'Ελλάδα' },
  DE: { length: 22, name: 'Γερμανία' },
  FR: { length: 27, name: 'Γαλλία' },
  IT: { length: 27, name: 'Ιταλία' },
  ES: { length: 24, name: 'Ισπανία' },
  GB: { length: 22, name: 'Ηνωμένο Βασίλειο' },
  CY: { length: 28, name: 'Κύπρος' },
  BG: { length: 22, name: 'Βουλγαρία' },
  AT: { length: 20, name: 'Αυστρία' },
  NL: { length: 18, name: 'Ολλανδία' },
  BE: { length: 16, name: 'Βέλγιο' },
  CH: { length: 21, name: 'Ελβετία' }
};

/**
 * Validates an IBAN according to ISO 13616
 *
 * @param iban - The IBAN to validate (with or without spaces)
 * @returns Validation result with error details
 *
 * @example
 * ```typescript
 * const result = validateIBAN('GR16 0110 1250 0000 0001 2300 695');
 * if (result.valid) {
 *   console.log('Bank code:', result.bankCode);
 * } else {
 *   console.error('Error:', result.error);
 * }
 * ```
 */
export function validateIBAN(iban: string): IBANValidationResult {
  // Remove spaces and convert to uppercase
  const cleaned = iban.replace(/\s/g, '').toUpperCase();

  // Basic format check
  if (!cleaned) {
    return { valid: false, error: 'Το IBAN είναι κενό' };
  }

  // Check for valid characters (only letters A-Z and digits 0-9)
  if (!/^[A-Z0-9]+$/.test(cleaned)) {
    return { valid: false, error: 'Το IBAN περιέχει μη έγκυρους χαρακτήρες' };
  }

  // Extract country code
  const countryCode = cleaned.substring(0, 2);

  // Check if country is known
  const countryConfig = IBAN_COUNTRY_CONFIG[countryCode];
  if (!countryConfig) {
    // Allow unknown countries but with warning
    if (cleaned.length < 15 || cleaned.length > 34) {
      return { valid: false, error: 'Μη έγκυρο μήκος IBAN' };
    }
  } else {
    // Check length for known countries
    if (cleaned.length !== countryConfig.length) {
      return {
        valid: false,
        error: `Το IBAN για ${countryConfig.name} πρέπει να έχει ${countryConfig.length} χαρακτήρες (έχει ${cleaned.length})`
      };
    }
  }

  // Extract check digits
  const checkDigits = cleaned.substring(2, 4);

  // MOD 97 validation (ISO 7064)
  // Move first 4 characters to end
  const rearranged = cleaned.substring(4) + cleaned.substring(0, 4);

  // Convert letters to numbers (A=10, B=11, ..., Z=35)
  let numericString = '';
  for (const char of rearranged) {
    if (char >= 'A' && char <= 'Z') {
      numericString += (char.charCodeAt(0) - 55).toString();
    } else {
      numericString += char;
    }
  }

  // Calculate MOD 97 using chunks (to avoid BigInt issues)
  let remainder = 0;
  for (let i = 0; i < numericString.length; i += 7) {
    const chunk = numericString.substring(i, i + 7);
    remainder = parseInt(remainder.toString() + chunk, 10) % 97;
  }

  if (remainder !== 1) {
    return { valid: false, error: 'Μη έγκυρος αριθμός ελέγχου IBAN' };
  }

  // Extract bank code for Greek IBANs
  let bankCode: string | undefined;
  if (countryCode === 'GR') {
    bankCode = cleaned.substring(4, 7);
  }

  return {
    valid: true,
    countryCode,
    checkDigits,
    bankCode,
    accountNumber: cleaned.substring(4)
  };
}

/**
 * Formats an IBAN with spaces for display
 *
 * @param iban - The IBAN to format
 * @returns Formatted IBAN with spaces every 4 characters
 *
 * @example
 * ```typescript
 * formatIBAN('GR1601101250000000012300695');
 * // Returns: 'GR16 0110 1250 0000 0001 2300 695'
 * ```
 */
export function formatIBAN(iban: string): string {
  const cleaned = iban.replace(/\s/g, '').toUpperCase();
  return cleaned.match(/.{1,4}/g)?.join(' ') || cleaned;
}

/**
 * Removes formatting from an IBAN (for storage)
 *
 * @param iban - The IBAN to clean
 * @returns IBAN without spaces, uppercase
 */
export function cleanIBAN(iban: string): string {
  return iban.replace(/\s/g, '').toUpperCase();
}

/**
 * Extracts bank information from a Greek IBAN
 *
 * @param iban - The IBAN to parse
 * @returns Bank info if found, undefined otherwise
 *
 * @note This function requires the greek-banks catalog to be imported
 */
export function extractBankCodeFromIBAN(iban: string): string | undefined {
  const validation = validateIBAN(iban);
  if (!validation.valid || validation.countryCode !== 'GR') {
    return undefined;
  }
  return validation.bankCode;
}

// ============================================================================
// TYPE GUARDS
// ============================================================================

/**
 * Type guard for BankAccount
 */
export function isBankAccount(obj: unknown): obj is BankAccount {
  if (typeof obj !== 'object' || obj === null) return false;
  const account = obj as Record<string, unknown>;
  return (
    typeof account.id === 'string' &&
    typeof account.bankName === 'string' &&
    typeof account.iban === 'string' &&
    typeof account.accountType === 'string' &&
    typeof account.currency === 'string' &&
    typeof account.isPrimary === 'boolean' &&
    typeof account.isActive === 'boolean'
  );
}

/**
 * Type guard for AccountType
 */
export function isAccountType(value: string): value is AccountType {
  return ['checking', 'savings', 'business', 'other'].includes(value);
}

/**
 * Type guard for CurrencyCode
 */
export function isCurrencyCode(value: string): value is CurrencyCode {
  return ['EUR', 'USD', 'GBP', 'CHF'].includes(value);
}

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

/**
 * Creates a default empty bank account for forms
 */
export function createEmptyBankAccount(): BankAccountInput {
  return {
    bankName: '',
    iban: '',
    accountType: 'checking',
    currency: 'EUR',
    isPrimary: false,
    isActive: true
  };
}

/**
 * Masks an IBAN for display (shows only first and last 4 characters)
 *
 * @param iban - The IBAN to mask
 * @returns Masked IBAN string
 *
 * @example
 * ```typescript
 * maskIBAN('GR1601101250000000012300695');
 * // Returns: 'GR16 **** **** **** **** **** 695'
 * ```
 */
export function maskIBAN(iban: string): string {
  const formatted = formatIBAN(iban);
  const parts = formatted.split(' ');
  if (parts.length <= 2) return formatted;

  const masked = parts.map((part, index) => {
    if (index === 0 || index === parts.length - 1) return part;
    return '****';
  });

  return masked.join(' ');
}
