import {
  Building,
  Car,
  CheckSquare,
  Construction,
  Euro,
  Factory,
  FileText,
  Home,
  Landmark,
  Layers,
  Mail,
  MapPin,
  MessageSquare,
  Package,
  Phone,
  Receipt,
  Ruler,
  Target,
  User,
} from 'lucide-react';
import type { NavigationEntitiesConfig } from './types';

export const NAVIGATION_ENTITIES: NavigationEntitiesConfig = {
  company: {
    icon: Factory,
    color: 'text-blue-600',
    label: 'navigation.entities.company.label',
    pluralLabel: 'navigation.entities.company.plural',
    description: 'navigation.entities.company.description',
  },
  project: {
    icon: Construction,
    color: 'text-green-600',
    label: 'navigation.entities.project.label',
    pluralLabel: 'navigation.entities.project.plural',
    description: 'navigation.entities.project.description',
  },
  building: {
    icon: Building,
    color: 'text-purple-600',
    label: 'navigation.entities.building.label',
    pluralLabel: 'navigation.entities.building.plural',
    description: 'navigation.entities.building.description',
  },
  property: {
    icon: Home,
    color: 'text-teal-600',
    label: 'navigation.entities.property.label',
    pluralLabel: 'navigation.entities.property.plural',
    description: 'navigation.entities.property.description',
  },
  floor: {
    icon: Layers,
    color: 'text-orange-600',
    label: 'navigation.entities.floor.label',
    pluralLabel: 'navigation.entities.floor.plural',
    description: 'navigation.entities.floor.description',
  },
  parking: {
    icon: Car,
    color: 'text-amber-600',
    label: 'navigation.entities.parking.label',
    pluralLabel: 'navigation.entities.parking.plural',
    description: 'navigation.entities.parking.description',
  },
  storage: {
    icon: Package,
    color: 'text-indigo-600',
    label: 'navigation.entities.storage.label',
    pluralLabel: 'navigation.entities.storage.plural',
    description: 'navigation.entities.storage.description',
  },
  procurement: {
    icon: Package,
    color: 'text-blue-600',
    label: 'navigation.entities.procurement.label',
    pluralLabel: 'navigation.entities.procurement.plural',
    description: 'navigation.entities.procurement.description',
  },
  quote: {
    icon: FileText,
    color: 'text-amber-600',
    label: 'navigation.entities.quote.label',
    pluralLabel: 'navigation.entities.quote.plural',
    description: 'navigation.entities.quote.description',
  },
  location: {
    icon: MapPin,
    color: 'text-red-600',
    label: 'navigation.entities.location.label',
    pluralLabel: 'navigation.entities.location.plural',
    description: 'navigation.entities.location.description',
  },
  area: {
    icon: Ruler,
    color: 'text-pink-600',
    label: 'navigation.entities.area.label',
    pluralLabel: 'navigation.entities.area.plural',
    description: 'navigation.entities.area.description',
  },
  price: {
    icon: Euro,
    color: 'text-emerald-600',
    label: 'navigation.entities.price.label',
    pluralLabel: 'navigation.entities.price.plural',
    description: 'navigation.entities.price.description',
  },
  phone: {
    icon: Phone,
    color: 'text-sky-600',
    label: 'navigation.entities.phone.label',
    pluralLabel: 'navigation.entities.phone.plural',
    description: 'navigation.entities.phone.description',
  },
  email: {
    icon: Mail,
    color: 'text-rose-600',
    label: 'navigation.entities.email.label',
    pluralLabel: 'navigation.entities.email.plural',
    description: 'navigation.entities.email.description',
  },
  vat: {
    icon: Receipt,
    color: 'text-slate-600',
    label: 'navigation.entities.vat.label',
    pluralLabel: 'navigation.entities.vat.plural',
    description: 'navigation.entities.vat.description',
  },
  contactIndividual: {
    icon: User,
    color: 'text-blue-600',
    label: 'navigation.entities.contactIndividual.label',
    pluralLabel: 'navigation.entities.contactIndividual.plural',
    description: 'navigation.entities.contactIndividual.description',
  },
  contactCompany: {
    icon: Factory,
    color: 'text-blue-600',
    label: 'navigation.entities.contactCompany.label',
    pluralLabel: 'navigation.entities.contactCompany.plural',
    description: 'navigation.entities.contactCompany.description',
  },
  contactService: {
    icon: Landmark,
    color: 'text-amber-600',
    label: 'navigation.entities.contactService.label',
    pluralLabel: 'navigation.entities.contactService.plural',
    description: 'navigation.entities.contactService.description',
  },
  contact: {
    icon: User,
    color: 'text-violet-500',
    label: 'navigation.entities.contact.label',
    pluralLabel: 'navigation.entities.contact.plural',
    description: 'navigation.entities.contact.description',
  },
  file: {
    icon: FileText,
    color: 'text-slate-500',
    label: 'navigation.entities.file.label',
    pluralLabel: 'navigation.entities.file.plural',
    description: 'navigation.entities.file.description',
  },
  opportunity: {
    icon: Target,
    color: 'text-emerald-500',
    label: 'navigation.entities.opportunity.label',
    pluralLabel: 'navigation.entities.opportunity.plural',
    description: 'navigation.entities.opportunity.description',
  },
  communication: {
    icon: MessageSquare,
    color: 'text-sky-500',
    label: 'navigation.entities.communication.label',
    pluralLabel: 'navigation.entities.communication.plural',
    description: 'navigation.entities.communication.description',
  },
  task: {
    icon: CheckSquare,
    color: 'text-orange-500',
    label: 'navigation.entities.task.label',
    pluralLabel: 'navigation.entities.task.plural',
    description: 'navigation.entities.task.description',
  },
} as const;
