/**
 * GET /api/storage/file/[...path] — Auth-gated proxy for Storage objects.
 *
 * Browser-friendly URL produced by `uploadPublicFile()`. The bytes live in a
 * private bucket (UBLA blocks anonymous reads, Storage Rules deny token URLs
 * generated by Admin SDK) — this proxy authenticates the user via session
 * cookie, verifies the path's `companyId` matches the user's claim, and
 * streams the object back with original `Content-Type` and `Cache-Control`.
 *
 * Path scheme (must match `buildStoragePath`): `companies/{companyId}/...`.
 *
 * @module api/storage/file/[...path]
 * @see src/services/storage-admin/public-upload.service.ts (canonical writer)
 */

import 'server-only';

import { NextRequest, NextResponse } from 'next/server';
import { withAuth } from '@/lib/auth';
import type { AuthContext, PermissionCache } from '@/lib/auth';
import { withStandardRateLimit } from '@/lib/middleware/with-rate-limit';
import { getAdminBucket } from '@/lib/firebaseAdmin';
import { createModuleLogger } from '@/lib/telemetry';
import { getErrorMessage } from '@/lib/error-utils';

const logger = createModuleLogger('STORAGE_FILE_PROXY');

async function handleGet(
  request: NextRequest,
  segmentData?: { params: Promise<{ path: string[] }> },
): Promise<NextResponse> {
  const { path: rawSegments } = await segmentData!.params;
  const segments = rawSegments.map((s) => decodeURIComponent(s));
  const storagePath = segments.join('/');

  const handler = withAuth(
    async (_req: NextRequest, ctx: AuthContext, _cache: PermissionCache): Promise<NextResponse> => {
      if (segments[0] !== 'companies' || segments[1] !== ctx.companyId) {
        return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
      }

      try {
        const bucket = getAdminBucket();
        // Diagnostic: also test the default bucket reference. If they resolve
        // to different physical buckets, getMetadata results will differ.
        let defaultBucketProbe: { name: string; exists: boolean | null; error?: string } | null = null;
        try {
          const { getAdminStorage } = await import('@/lib/firebaseAdmin');
          const defaultBucket = getAdminStorage().bucket();
          const defaultRef = defaultBucket.file(storagePath);
          try {
            await defaultRef.getMetadata();
            defaultBucketProbe = { name: defaultBucket.name, exists: true };
          } catch (probeErr) {
            const code = (probeErr as { code?: number }).code;
            defaultBucketProbe = {
              name: defaultBucket.name,
              exists: code === 404 ? false : null,
              error: code !== 404 ? getErrorMessage(probeErr) : undefined,
            };
          }
        } catch (e) {
          defaultBucketProbe = { name: '<probe-init-failed>', exists: null, error: getErrorMessage(e) };
        }
        const fileRef = bucket.file(storagePath);

        // Direct getMetadata: file.exists() returns false against
        // .firebasestorage.app buckets in some Admin SDK paths even when the
        // object is present. getMetadata() throws a structured 404 we can
        // distinguish from other errors.
        let metadata: Awaited<ReturnType<typeof fileRef.getMetadata>>[0];
        try {
          [metadata] = await fileRef.getMetadata();
        } catch (metaErr) {
          const errCode = (metaErr as { code?: number }).code;
          // Diagnostic: list a few sibling files to see what the proxy's
          // bucket actually contains at this path's parent.
          let siblings: string[] = [];
          let bucketTopFiles: string[] = [];
          try {
            const parentPrefix = storagePath.split('/').slice(0, -1).join('/') + '/';
            const [files] = await bucket.getFiles({ prefix: parentPrefix, maxResults: 5 });
            siblings = files.map((f) => f.name);
            const [topFiles] = await bucket.getFiles({ maxResults: 5 });
            bucketTopFiles = topFiles.map((f) => f.name);
          } catch (listErr) {
            siblings = [`<list error: ${getErrorMessage(listErr)}>`];
          }
          logger.warn('Storage file proxy: getMetadata failed', {
            bucket: bucket.name,
            storagePath,
            errorCode: errCode,
            errorMessage: getErrorMessage(metaErr),
            siblingsAtParent: siblings,
            bucketTopFiles,
            envFirebaseStorageBucket: process.env.FIREBASE_STORAGE_BUCKET,
            defaultBucketProbe,
          });
          if (errCode === 404) {
            return NextResponse.json({ error: 'Not found' }, { status: 404 });
          }
          throw metaErr;
        }

        const contentType = (metadata.contentType as string | undefined) ?? 'application/octet-stream';
        const cacheControl = (metadata.cacheControl as string | undefined) ?? 'private, max-age=86400';
        const sizeRaw = metadata.size;
        const size = typeof sizeRaw === 'string' ? Number(sizeRaw) : (sizeRaw as number | undefined);

        const nodeStream = fileRef.createReadStream();
        const stream = new ReadableStream<Uint8Array>({
          start(controller) {
            nodeStream.on('data', (chunk: Buffer) => controller.enqueue(new Uint8Array(chunk)));
            nodeStream.on('end', () => controller.close());
            nodeStream.on('error', (err) => controller.error(err));
          },
          cancel() {
            nodeStream.destroy();
          },
        });

        const headers = new Headers({
          'Content-Type': contentType,
          'Cache-Control': cacheControl,
        });
        if (typeof size === 'number' && Number.isFinite(size)) {
          headers.set('Content-Length', String(size));
        }

        return new NextResponse(stream, { status: 200, headers });
      } catch (err) {
        const message = getErrorMessage(err, 'Failed to fetch file');
        logger.error('Storage file proxy error', { storagePath, error: message });
        return NextResponse.json({ error: message }, { status: 500 });
      }
    },
  );
  return handler(request);
}

export const GET = withStandardRateLimit(handleGet);
