/**
 * ADR-408 Φ8 — Pure builders for MEP segment (duct/pipe) entity creation.
 *
 * SSoT:
 *   - Entity creation via `createMepSegment()` factory.
 *   - IDs auto-generated by factory (prefix 'mepseg').
 *   - Geometry via `computeMepSegmentGeometry()` — pure.
 *   - Validation via `validateMepSegmentParams()` — errors block creation.
 *   - Types via `bim/types/mep-segment-types.ts`.
 *
 * Placement flow: 2-click (start → end), `completeMepSegmentFromTwoClicks`.
 *
 * @see ./beam-completion.ts (template)
 * @see docs/centralized-systems/reference/adrs/ADR-408-mep-connectors-and-systems.md §Φ8
 */

import type { Point2D } from '../../rendering/types/Types';
import type { Point3D } from '../../bim/types/bim-base';
import {
  DEFAULT_DUCT_WIDTH_MM,
  DEFAULT_DUCT_HEIGHT_MM,
  DEFAULT_ROUND_DUCT_DIAMETER_MM,
  DEFAULT_PIPE_DIAMETER_MM,
  DEFAULT_SEGMENT_CENTERLINE_ELEVATION_MM,
  type MepSegmentDomain,
  type MepSegmentEntity,
  type MepSegmentParams,
  type MepSegmentSectionKind,
} from '../../bim/types/mep-segment-types';
import { deriveCenterlineElevationMm } from '../../bim/types/mep-segment-types';
import { computeMepSegmentGeometry, validateMepSegmentParams } from '../../bim/geometry/mep-segment-geometry';
import { createMepSegment } from '@/services/factories/mep-segment.factory';
import type { SceneUnits } from '../../utils/scene-units';

export type { SceneUnits };

/**
 * Field overrides for `buildDefaultMepSegmentParams`. The ribbon (contextual
 * duct/pipe tab) supplies domain / sectionKind / section dims / elevation.
 */
export interface MepSegmentParamOverrides {
  readonly domain?: MepSegmentDomain;
  readonly sectionKind?: MepSegmentSectionKind;
  /** mm — rectangular duct width. */
  readonly width?: number;
  /** mm — rectangular duct height. */
  readonly height?: number;
  /** mm — round duct / pipe diameter. */
  readonly diameter?: number;
  /** mm — pipe wall thickness. */
  readonly wallThickness?: number;
  /** mm — centreline ("Middle Elevation") from project origin. */
  readonly centerlineElevationMm?: number;
  readonly material?: string;
}

/** A pipe is always round; a duct defaults to rectangular. */
function defaultSectionKind(domain: MepSegmentDomain): MepSegmentSectionKind {
  return domain === 'pipe' ? 'round' : 'rectangular';
}

/**
 * Build `MepSegmentParams` from 2 click points + optional overrides.
 * Resolves the right section fields for the section kind (round ⇒ diameter,
 * rectangular ⇒ width+height) so the schema's superRefine passes.
 */
export function buildDefaultMepSegmentParams(
  startPoint: Readonly<Point2D>,
  endPoint: Readonly<Point2D>,
  domainArg?: MepSegmentDomain,
  overrides: MepSegmentParamOverrides = {},
  sceneUnits: SceneUnits = 'mm',
  startElevationMm: number | null = null,
  endElevationMm: number | null = null,
): MepSegmentParams {
  const domain = overrides.domain ?? domainArg ?? 'duct';
  // A pipe forces round; otherwise honour the override / default.
  const sectionKind: MepSegmentSectionKind =
    domain === 'pipe' ? 'round' : overrides.sectionKind ?? defaultSectionKind(domain);

  const baseCenterMm =
    overrides.centerlineElevationMm ?? DEFAULT_SEGMENT_CENTERLINE_ELEVATION_MM;
  // ADR-408 Φ-A/Φ-B1: each endpoint carries its OWN elevation (mm) as the
  // authoritative z. Connector-mate cascade (Revit "Connect To"): an endpoint that
  // snapped to a connector inherits its elevation; a FREE end follows the snapped
  // end (horizontal continuation); if NEITHER snapped, both sit at the centreline
  // default. So: start@manifold(400)+free end ⇒ flat @400; start@manifold(400)+
  // end@pipe(2800) ⇒ sloped riser. `centerlineElevationMm` stays the derived cache.
  const startZ = startElevationMm ?? endElevationMm ?? baseCenterMm;
  const endZ = endElevationMm ?? startElevationMm ?? baseCenterMm;
  const centerlineElevationMm = deriveCenterlineElevationMm(startZ, endZ);
  const start: Point3D = { x: startPoint.x, y: startPoint.y, z: startZ };
  const end: Point3D = { x: endPoint.x, y: endPoint.y, z: endZ };

  const base: MepSegmentParams = {
    domain,
    sectionKind,
    startPoint: start,
    endPoint: end,
    centerlineElevationMm,
    sceneUnits,
    ...(overrides.material !== undefined ? { material: overrides.material } : {}),
  };

  if (sectionKind === 'round') {
    const diameter =
      overrides.diameter ??
      (domain === 'pipe' ? DEFAULT_PIPE_DIAMETER_MM : DEFAULT_ROUND_DUCT_DIAMETER_MM);
    return {
      ...base,
      diameter,
      ...(domain === 'pipe'
        ? { wallThickness: overrides.wallThickness }
        : {}),
    };
  }
  return {
    ...base,
    width: overrides.width ?? DEFAULT_DUCT_WIDTH_MM,
    height: overrides.height ?? DEFAULT_DUCT_HEIGHT_MM,
  };
}

// ─── Entity builder ──────────────────────────────────────────────────────────

export type BuildMepSegmentEntityResult =
  | { readonly ok: true; readonly entity: MepSegmentEntity }
  | { readonly ok: false; readonly hardErrors: readonly string[] };

/**
 * Build a `MepSegmentEntity` from params. Geometry via SSoT
 * `computeMepSegmentGeometry()`. Hard errors short-circuit creation. Final entity
 * via `createMepSegment()` factory (auto-fills id + ifcGuid + ifcType).
 */
export function buildMepSegmentEntity(
  params: Readonly<MepSegmentParams>,
  layerId: string,
): BuildMepSegmentEntityResult {
  const validation = validateMepSegmentParams(params);
  if (validation.errors.length > 0) {
    return { ok: false, hardErrors: validation.errors };
  }
  const geometry = computeMepSegmentGeometry(params);
  const entity = createMepSegment({ params, geometry, layerId, visible: true });
  return { ok: true, entity };
}

/**
 * High-level helper bridging the segment-tool FSM (2-click) and the builder.
 * Pure — no side effects.
 */
export function completeMepSegmentFromTwoClicks(
  startPoint: Readonly<Point2D>,
  endPoint: Readonly<Point2D>,
  layerId: string,
  domain: MepSegmentDomain = 'duct',
  overrides: MepSegmentParamOverrides = {},
  sceneUnits: SceneUnits = 'mm',
  startElevationMm: number | null = null,
  endElevationMm: number | null = null,
): BuildMepSegmentEntityResult {
  const params = buildDefaultMepSegmentParams(
    startPoint,
    endPoint,
    domain,
    overrides,
    sceneUnits,
    startElevationMm,
    endElevationMm,
  );
  return buildMepSegmentEntity(params, layerId);
}
