/**
 * @fileoverview PDF Exporter — Financial Reports (Phase 2e)
 * @description jsPDF + autoTable export with Greek font support
 * @author Claude Code (Anthropic AI) + Γιώργος Παγώνης
 * @created 2026-03-30
 * @see DECISIONS-PHASE-2.md §2e (Q8 — export formats)
 * @compliance CLAUDE.md Enterprise Standards — zero `any`
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { registerGreekFont } from '@/services/pdf/greek-font-loader';
import type { ReportType, ReportDataMap, ResolvedPeriods } from '../../types/reports';
import { flattenReportForExport } from './report-table-adapter';
import type { CellValue } from './report-table-adapter';
import { triggerBlobDownload } from '@/services/gantt-export/gantt-export-utils';

// ============================================================================
// CONSTANTS
// ============================================================================

const PAGE_MARGIN = 14;
const TITLE_FONT_SIZE = 16;
const SUBTITLE_FONT_SIZE = 10;
const TABLE_FONT_SIZE = 9;

// ============================================================================
// HELPERS
// ============================================================================

function cellToString(value: CellValue): string {
  if (value === null || value === undefined) return '—';
  if (typeof value === 'number') {
    return value.toLocaleString('el-GR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }
  return String(value);
}

function buildFilename(reportType: ReportType, period: ResolvedPeriods): string {
  const date = period.current.from.replace(/-/g, '');
  return `${reportType}_${date}.pdf`;
}

// ============================================================================
// PUBLIC API
// ============================================================================

export async function exportReportPdf(
  reportType: ReportType,
  data: ReportDataMap[ReportType],
  period: ResolvedPeriods,
  title: string
): Promise<void> {
  const tableData = flattenReportForExport(reportType, data);
  const isWide = tableData.headers.length > 4;

  const pdf = new jsPDF({
    orientation: isWide ? 'landscape' : 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Register Greek font
  await registerGreekFont(pdf);

  // Title
  pdf.setFontSize(TITLE_FONT_SIZE);
  pdf.text(title, PAGE_MARGIN, 20);

  // Subtitle with period
  pdf.setFontSize(SUBTITLE_FONT_SIZE);
  pdf.setTextColor(100, 100, 100);
  pdf.text(
    `Period: ${period.current.from} — ${period.current.to}`,
    PAGE_MARGIN,
    28
  );
  pdf.setTextColor(0, 0, 0);

  // Summary metrics
  let startY = 35;
  if (tableData.summaryMetrics.length > 0) {
    autoTable(pdf, {
      startY,
      head: [['Metric', 'Value', 'Change %']],
      body: tableData.summaryMetrics.map((m) => [
        m.label,
        m.value.toLocaleString('el-GR', { minimumFractionDigits: 2 }),
        m.change?.percentage !== null && m.change?.percentage !== undefined
          ? `${m.change.percentage.toFixed(1)}%`
          : '—',
      ]),
      styles: { fontSize: TABLE_FONT_SIZE, cellPadding: 2 },
      headStyles: { fillColor: [31, 41, 55], textColor: [255, 255, 255] },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
      theme: 'striped',
    });
    // Get Y after summary table
    startY = (pdf as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? startY;
    startY += 8;
  }

  // Main data table
  autoTable(pdf, {
    startY,
    head: [tableData.headers],
    body: tableData.rows.map((row) => row.map(cellToString)),
    styles: { fontSize: TABLE_FONT_SIZE, cellPadding: 2 },
    headStyles: { fillColor: [31, 41, 55], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    theme: 'striped',
    columnStyles: tableData.headers.reduce<Record<number, { halign: 'left' | 'right' }>>(
      (acc, _, i) => {
        if (i > 0) acc[i] = { halign: 'right' };
        return acc;
      },
      {}
    ),
  });

  // Footer
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    const pageHeight = pdf.internal.pageSize.getHeight();
    pdf.text(
      `Generated by Nestor App — Page ${i}/${pageCount}`,
      PAGE_MARGIN,
      pageHeight - 8
    );
  }

  // Download
  const blob = pdf.output('blob');
  const filename = buildFilename(reportType, period);
  triggerBlobDownload(blob, filename);
}
