/**
 * =============================================================================
 * Upload Entry Points — Building Entries (35 entries, incl. ADR-191 studies)
 * =============================================================================
 *
 * @module config/upload-entry-points/entries-building
 * @enterprise ADR-031 + ADR-191
 */

import type { UploadEntryPoint } from './types';

/**
 * Building upload entry points.
 * Includes hierarchical study entries (ADR-191) with perFloor support.
 */
export const BUILDING_ENTRY_POINTS: UploadEntryPoint[] = [
    {
      id: 'building-permit',
      purpose: 'permit',
      domain: 'construction',
      category: 'permits',
      label: {
        el: 'Οικοδομική Άδεια',
        en: 'Building Permit',
      },
      icon: 'FileCheck',
      order: 1,
    },
    {
      id: 'floor-plan',
      purpose: 'floorplan',
      domain: 'construction',
      category: 'floorplans',
      label: {
        el: 'Κάτοψη',
        en: 'Floor Plan',
      },
      icon: 'LayoutGrid',
      order: 2,
    },
    {
      id: 'exterior-photo',
      purpose: 'exterior',
      domain: 'construction',
      category: 'photos',
      label: {
        el: 'Φωτογραφία Εξωτερικού',
        en: 'Exterior Photo',
      },
      icon: 'Camera',
      order: 3,
    },
    // ------------------------------------------------------------------------
    // ΦΩΤΟΓΡΑΦΙΕΣ ΚΤΙΡΙΟΥ (Photos)
    // ------------------------------------------------------------------------
    {
      id: 'building-interior-photo',
      purpose: 'interior',
      domain: 'construction',
      category: 'photos',
      label: {
        el: 'Εσωτερικό Κτιρίου',
        en: 'Building Interior',
      },
      icon: 'Camera',
      order: 4,
    },
    {
      id: 'building-progress-photo',
      purpose: 'progress',
      domain: 'construction',
      category: 'photos',
      label: {
        el: 'Πρόοδος Κατασκευής',
        en: 'Construction Progress',
      },
      icon: 'Camera',
      order: 5,
    },
    {
      id: 'building-common-areas-photo',
      purpose: 'common-areas',
      domain: 'construction',
      category: 'photos',
      label: {
        el: 'Κοινόχρηστοι Χώροι',
        en: 'Common Areas',
      },
      icon: 'Camera',
      order: 6,
    },
    // ------------------------------------------------------------------------
    // ΒΙΝΤΕΟ ΚΤΙΡΙΟΥ (Videos)
    // ------------------------------------------------------------------------
    {
      id: 'building-walkthrough-video',
      purpose: 'walkthrough',
      domain: 'construction',
      category: 'videos',
      label: {
        el: 'Περιήγηση Κτιρίου',
        en: 'Building Walkthrough',
      },
      icon: 'Video',
      order: 10,
    },
    {
      id: 'building-drone-video',
      purpose: 'drone',
      domain: 'construction',
      category: 'videos',
      label: {
        el: 'Drone Κτιρίου',
        en: 'Building Drone',
      },
      icon: 'Video',
      order: 11,
    },
    {
      id: 'building-progress-video',
      purpose: 'construction-video',
      domain: 'construction',
      category: 'videos',
      label: {
        el: 'Πρόοδος Κατασκευής',
        en: 'Construction Progress',
      },
      icon: 'Video',
      order: 12,
    },
    // ------------------------------------------------------------------------
    // ΣΥΜΒΟΛΑΙΑ ΚΤΙΡΙΟΥ (Contracts)
    // ------------------------------------------------------------------------
    {
      id: 'building-contract',
      purpose: 'contract',
      domain: 'legal',
      category: 'contracts',
      label: {
        el: 'Συμβόλαιο Κτιρίου',
        en: 'Building Contract',
      },
      icon: 'FileSignature',
      order: 20,
    },
    {
      id: 'building-lease-agreement',
      purpose: 'lease',
      domain: 'legal',
      category: 'contracts',
      label: {
        el: 'Μισθωτήριο',
        en: 'Lease Agreement',
      },
      icon: 'FileSignature',
      order: 21,
    },
    {
      id: 'building-insurance',
      purpose: 'insurance',
      domain: 'legal',
      category: 'contracts',
      label: {
        el: 'Ασφάλεια Κτιρίου',
        en: 'Building Insurance',
      },
      icon: 'Shield',
      order: 22,
    },
    {
      id: 'generic-building-doc',
      purpose: 'generic',
      domain: 'construction',
      category: 'documents',
      label: {
        el: 'Άλλο Έγγραφο',
        en: 'Other Document',
      },
      icon: 'File',
      order: 99,
      requiresCustomTitle: true, // 🏢 ENTERPRISE: Mandatory title field (ΤΕΛΕΙΩΤΙΚΗ ΕΝΤΟΛΗ)
    },

    // ========================================================================
    // 🏢 ADR-191: ΜΕΛΕΤΕΣ ΟΙΚΟΔΟΜΙΚΗΣ ΑΔΕΙΑΣ — BUILDING LEVEL
    // ========================================================================

    // --- ARCHITECTURAL / ΑΡΧΙΤΕΚΤΟΝΙΚΑ (300-349) ---
    {
      id: 'study-arch-coverage',
      purpose: 'study-coverage',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Διάγραμμα Κάλυψης', en: 'Coverage Diagram' },
      description: { el: 'Διάγραμμα κάλυψης / δόμησης', en: 'Site coverage / building ratio diagram' },
      icon: 'LayoutGrid',
      order: 300,
      group: 'architectural',
    },
    {
      id: 'study-arch-section',
      purpose: 'study-arch-section',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Αρχιτεκτονική Τομή', en: 'Architectural Section' },
      description: { el: 'Τομές κτιρίου (εγκάρσια, διαμήκης)', en: 'Building sections (cross, longitudinal)' },
      icon: 'Scissors',
      order: 301,
      group: 'architectural',
    },
    {
      id: 'study-arch-elevation',
      purpose: 'study-arch-elevation',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Όψεις Κτιρίου', en: 'Building Elevations' },
      description: { el: 'Αρχιτεκτονικές όψεις (Βόρεια, Νότια κ.λπ.)', en: 'Architectural elevations (North, South etc.)' },
      icon: 'Building',
      order: 302,
      group: 'architectural',
    },
    {
      id: 'study-arch-detail',
      purpose: 'study-arch-detail',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Αρχιτεκτονικές Λεπτομέρειες', en: 'Architectural Details' },
      description: { el: 'Κατασκευαστικές λεπτομέρειες', en: 'Construction detail drawings' },
      icon: 'Focus',
      order: 303,
      group: 'architectural',
    },
    {
      id: 'study-arch-3d',
      purpose: 'study-3d-render',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Τρισδιάστατα / Φωτορεαλισμός', en: '3D Renders / Visualizations' },
      description: { el: '3D απεικονίσεις κτιρίου', en: '3D building visualizations' },
      icon: 'Box',
      order: 304,
      group: 'architectural',
    },
    {
      id: 'study-arch-floorplan',
      purpose: 'study-floorplan',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Κάτοψη', en: 'Floor Plan' },
      description: { el: 'Αρχιτεκτονική κάτοψη ορόφου', en: 'Architectural floor plan' },
      icon: 'LayoutGrid',
      order: 310,
      group: 'architectural',
      perFloor: true,
    },
    {
      id: 'study-arch-other',
      purpose: 'study-arch-other',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Άλλο Αρχιτεκτονικό', en: 'Other Architectural' },
      description: { el: 'Λοιπό αρχιτεκτονικό σχέδιο', en: 'Other architectural drawing' },
      icon: 'File',
      order: 349,
      group: 'architectural',
      requiresCustomTitle: true,
    },

    // --- STRUCTURAL / ΣΤΑΤΙΚΑ (400-449) ---
    {
      id: 'study-struct-analysis',
      purpose: 'study-struct-analysis',
      domain: 'construction',
      category: 'documents',
      label: { el: 'Στατική Μελέτη (Τεύχος)', en: 'Structural Analysis Report' },
      description: { el: 'Τεύχος στατικής μελέτης / υπολογισμοί', en: 'Structural calculation report' },
      icon: 'FileBarChart',
      order: 400,
      group: 'structural',
    },
    {
      id: 'study-struct-foundation',
      purpose: 'study-struct-foundation',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Σχέδιο Θεμελίωσης', en: 'Foundation Plan' },
      description: { el: 'Ξυλότυπος θεμελίωσης', en: 'Foundation formwork plan' },
      icon: 'Layers',
      order: 401,
      group: 'structural',
    },
    {
      id: 'study-struct-reinforcement',
      purpose: 'study-reinforcement',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Σχέδιο Οπλισμού', en: 'Reinforcement Plan' },
      description: { el: 'Σχέδια σιδηρού οπλισμού', en: 'Steel reinforcement drawings' },
      icon: 'Grid3x3',
      order: 402,
      group: 'structural',
    },
    {
      id: 'study-struct-formwork',
      purpose: 'study-struct-plan',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Ξυλότυπος', en: 'Formwork Plan' },
      description: { el: 'Ξυλότυπος ορόφου', en: 'Floor formwork plan' },
      icon: 'SquareDashedBottom',
      order: 410,
      group: 'structural',
      perFloor: true,
    },
    {
      id: 'study-struct-bearing',
      purpose: 'study-bearing-plan',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Σχέδιο Φέρουσας Κατασκευής', en: 'Load-Bearing Plan' },
      description: { el: 'Φέρουσα κατασκευή ορόφου', en: 'Floor load-bearing structure plan' },
      icon: 'Building2',
      order: 411,
      group: 'structural',
      perFloor: true,
    },
    {
      id: 'study-struct-other',
      purpose: 'study-struct-other',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Άλλο Στατικό', en: 'Other Structural' },
      description: { el: 'Λοιπό στατικό σχέδιο/μελέτη', en: 'Other structural drawing/study' },
      icon: 'File',
      order: 449,
      group: 'structural',
      requiresCustomTitle: true,
    },

    // --- MECHANICAL / Η/Μ (500-549) ---
    {
      id: 'study-mep-general',
      purpose: 'study-mep-general',
      domain: 'construction',
      category: 'documents',
      label: { el: 'Η/Μ Μελέτη (Τεύχος)', en: 'MEP Study Report' },
      description: { el: 'Γενικό τεύχος Η/Μ μελέτης', en: 'General MEP study report' },
      icon: 'FileBarChart',
      order: 500,
      group: 'mechanical',
    },
    {
      id: 'study-mep-overview',
      purpose: 'study-mep-overview',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Γενικό Σχέδιο Η/Μ', en: 'MEP Overview Drawing' },
      description: { el: 'Συνολική αποτύπωση Η/Μ εγκαταστάσεων', en: 'Overall MEP installations drawing' },
      icon: 'Wrench',
      order: 501,
      group: 'mechanical',
    },
    {
      id: 'study-mep-water',
      purpose: 'study-mep-water',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Ύδρευση', en: 'Water Supply' },
      description: { el: 'Σχέδιο ύδρευσης ορόφου', en: 'Floor water supply plan' },
      icon: 'Droplets',
      order: 510,
      group: 'mechanical',
      perFloor: true,
    },
    {
      id: 'study-mep-drainage',
      purpose: 'study-mep-drainage',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Αποχέτευση', en: 'Drainage' },
      description: { el: 'Σχέδιο αποχέτευσης ορόφου', en: 'Floor drainage plan' },
      icon: 'ArrowDownToLine',
      order: 511,
      group: 'mechanical',
      perFloor: true,
    },
    {
      id: 'study-mep-heating',
      purpose: 'study-mep-heating',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Θέρμανση', en: 'Heating' },
      description: { el: 'Σχέδιο θέρμανσης ορόφου', en: 'Floor heating plan' },
      icon: 'Flame',
      order: 512,
      group: 'mechanical',
      perFloor: true,
    },
    {
      id: 'study-mep-hvac',
      purpose: 'study-mep-hvac',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Κλιματισμός / Εξαερισμός', en: 'HVAC / Ventilation' },
      description: { el: 'Σχέδιο κλιματισμού-εξαερισμού ορόφου', en: 'Floor HVAC/ventilation plan' },
      icon: 'Wind',
      order: 513,
      group: 'mechanical',
      perFloor: true,
    },
    {
      id: 'study-mep-electrical',
      purpose: 'study-mep-electrical',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Ηλεκτρολογικά', en: 'Electrical' },
      description: { el: 'Ηλεκτρολογικό σχέδιο ορόφου', en: 'Floor electrical plan' },
      icon: 'Zap',
      order: 514,
      group: 'mechanical',
      perFloor: true,
    },
    {
      id: 'study-mep-telecom',
      purpose: 'study-mep-telecom',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Τηλεπικοινωνίες / Δίκτυα', en: 'Telecom / Network' },
      description: { el: 'Τηλεφωνία, δεδομένα, δίκτυα ορόφου', en: 'Floor telecom/network plan' },
      icon: 'Wifi',
      order: 515,
      group: 'mechanical',
      perFloor: true,
    },
    {
      id: 'study-mep-other',
      purpose: 'study-mep-other',
      domain: 'construction',
      category: 'drawings',
      label: { el: 'Άλλο Η/Μ', en: 'Other MEP' },
      description: { el: 'Λοιπό ηλεκτρομηχανολογικό σχέδιο', en: 'Other MEP drawing' },
      icon: 'File',
      order: 549,
      group: 'mechanical',
      requiresCustomTitle: true,
    },
];
