/**
 * =============================================================================
 * Upload Entry Points — Study Entries (Single Source of Truth)
 * =============================================================================
 *
 * All study entries for building permits (ADR-191) defined ONCE.
 * Visibility per entity level is controlled by:
 *   1. Group-level: StudyGroupMeta.entityLevels (study-groups-config.ts)
 *   2. Entry-level override: UploadEntryPoint.visibleIn
 *
 * @module config/upload-entry-points/entries-studies
 * @enterprise ADR-031 + ADR-191
 */

import type { UploadEntryPoint } from './types';

/**
 * All study entry points — unified from building + project entries.
 * Each entry belongs to a StudyGroup via the `group` field.
 * Filtering by entity level happens at assembly time (queries.ts).
 */
export const STUDY_ENTRIES: UploadEntryPoint[] = [
  // ========================================================================
  // ADMINISTRATIVE / ΝΟΜΙΚΑ (100-119) — group: 'administrative'
  // ========================================================================
  {
    id: 'study-admin-application',
    purpose: 'study-application',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Αίτηση Οικοδομικής Άδειας', en: 'Building Permit Application' },
    description: { el: 'Αίτηση προς πολεοδομία', en: 'Application to planning authority' },
    icon: 'FileText',
    order: 100,
    group: 'administrative',
  },
  {
    id: 'study-admin-title-deed',
    purpose: 'study-title-deed',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Τίτλος Ιδιοκτησίας', en: 'Title Deed' },
    description: { el: 'Συμβόλαιο κτήσης / τίτλος ιδιοκτησίας', en: 'Property title deed / ownership document' },
    icon: 'ScrollText',
    order: 101,
    group: 'administrative',
  },
  {
    id: 'study-admin-cadastre',
    purpose: 'study-cadastre',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Κτηματογράφηση', en: 'Cadastre Certificate' },
    description: { el: 'Κτηματολογικό φύλλο / απόσπασμα', en: 'Cadastral map / excerpt' },
    icon: 'Map',
    order: 102,
    group: 'administrative',
  },
  {
    id: 'study-admin-topographic',
    purpose: 'study-topographic',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Τοπογραφικό Διάγραμμα', en: 'Topographic Survey' },
    description: { el: 'Τοπογραφικό διάγραμμα μηχανικού', en: 'Engineer topographic survey plan' },
    icon: 'MapPin',
    order: 103,
    group: 'administrative',
  },
  {
    id: 'study-admin-authority-approval',
    purpose: 'study-authority-approval',
    domain: 'admin',
    category: 'permits',
    label: { el: 'Εγκρίσεις Φορέων', en: 'Authority Approvals' },
    description: { el: 'Εγκρίσεις δασαρχείου, αρχαιολογίας κ.λπ.', en: 'Forestry, archaeology approvals etc.' },
    icon: 'ShieldCheck',
    order: 104,
    group: 'administrative',
  },
  {
    id: 'study-admin-urban-plan',
    purpose: 'study-urban-plan',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Βεβαίωση Χρήσεων Γης', en: 'Land Use Certificate' },
    description: { el: 'Βεβαίωση πολεοδομικών χρήσεων γης', en: 'Urban land use certification' },
    icon: 'FileCheck2',
    order: 105,
    group: 'administrative',
  },
  {
    id: 'study-admin-legal-status',
    purpose: 'study-legal-status',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Νομική Κατάσταση Ακινήτου', en: 'Property Legal Status' },
    description: { el: 'Πιστοποιητικό βαρών, υποθηκών κ.λπ.', en: 'Encumbrances, mortgages certificate' },
    icon: 'Scale',
    order: 106,
    group: 'administrative',
  },
  {
    id: 'study-admin-regulation',
    purpose: 'study-regulation',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Κανονισμός Πολυκατοικίας', en: 'Building Regulation' },
    description: { el: 'Κανονισμός συνιδιοκτησίας', en: 'Co-ownership building regulation' },
    icon: 'BookOpen',
    order: 107,
    group: 'administrative',
  },
  {
    id: 'study-admin-other',
    purpose: 'study-admin-other',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Άλλο Διοικητικό', en: 'Other Administrative' },
    description: { el: 'Λοιπό διοικητικό/νομικό έγγραφο', en: 'Other administrative/legal document' },
    icon: 'File',
    order: 119,
    group: 'administrative',
    requiresCustomTitle: true,
  },

  // ========================================================================
  // FISCAL / ΑΣΦΑΛΙΣΤΙΚΑ (200-219) — group: 'fiscal'
  // ========================================================================
  {
    id: 'study-fiscal-efka',
    purpose: 'study-efka',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Εισφορές ΕΦΚΑ', en: 'EFKA Contributions' },
    description: { el: 'Αποδεικτικό εισφορών ΕΦΚΑ (e-ΕΦΚΑ)', en: 'EFKA social insurance proof' },
    icon: 'Landmark',
    order: 200,
    group: 'fiscal',
  },
  {
    id: 'study-fiscal-engineer-fees',
    purpose: 'study-engineer-fees',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Αμοιβές Μηχανικών', en: 'Engineer Fees' },
    description: { el: 'Δήλωση αμοιβής μηχανικών (ΤΕΕ)', en: 'Engineer fee declaration (TEE)' },
    icon: 'Calculator',
    order: 201,
    group: 'fiscal',
  },
  {
    id: 'study-fiscal-fem',
    purpose: 'study-fem',
    domain: 'admin',
    category: 'documents',
    label: { el: 'ΦΕΜ (Φόρος Μηχανικού)', en: 'FEM (Engineer Tax)' },
    description: { el: 'Φορολογικό Ένσημο Μηχανικού', en: 'Engineer fiscal stamp' },
    icon: 'Stamp',
    order: 202,
    group: 'fiscal',
  },
  {
    id: 'study-fiscal-deductions',
    purpose: 'study-deductions',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Κρατήσεις / Τέλη', en: 'Deductions / Fees' },
    description: { el: 'Κρατήσεις ΤΕΕ, ΕΜΠ, ΤΣΜΕΔΕ', en: 'TEE, EMP, TSMEDE deductions' },
    icon: 'Percent',
    order: 203,
    group: 'fiscal',
  },
  {
    id: 'study-fiscal-municipal-tax',
    purpose: 'study-municipal-tax',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Δημοτικά Τέλη', en: 'Municipal Fees' },
    description: { el: 'Αποδεικτικά δημοτικών τελών', en: 'Municipal fee receipts' },
    icon: 'Building2',
    order: 204,
    group: 'fiscal',
  },
  {
    id: 'study-fiscal-insurance',
    purpose: 'study-insurance',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Ασφαλιστήριο Έργου', en: 'Project Insurance' },
    description: { el: 'Ασφαλιστήριο συμβόλαιο κατασκευής', en: 'Construction project insurance policy' },
    icon: 'ShieldCheck',
    order: 205,
    group: 'fiscal',
  },
  {
    id: 'study-fiscal-other',
    purpose: 'study-fiscal-other',
    domain: 'admin',
    category: 'documents',
    label: { el: 'Άλλο Φορολογικό', en: 'Other Fiscal' },
    description: { el: 'Λοιπό φορολογικό/ασφαλιστικό έγγραφο', en: 'Other fiscal/insurance document' },
    icon: 'File',
    order: 219,
    group: 'fiscal',
    requiresCustomTitle: true,
  },

  // ========================================================================
  // ARCHITECTURAL / ΑΡΧΙΤΕΚΤΟΝΙΚΑ (300-349) — group: 'architectural'
  // ========================================================================
  {
    id: 'study-arch-coverage',
    purpose: 'study-coverage',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Διάγραμμα Κάλυψης', en: 'Coverage Diagram' },
    description: { el: 'Διάγραμμα κάλυψης / δόμησης', en: 'Site coverage / building ratio diagram' },
    icon: 'LayoutGrid',
    order: 300,
    group: 'architectural',
  },
  {
    id: 'study-arch-section',
    purpose: 'study-arch-section',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Αρχιτεκτονική Τομή', en: 'Architectural Section' },
    description: { el: 'Τομές κτιρίου (εγκάρσια, διαμήκης)', en: 'Building sections (cross, longitudinal)' },
    icon: 'Scissors',
    order: 301,
    group: 'architectural',
  },
  {
    id: 'study-arch-elevation',
    purpose: 'study-arch-elevation',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Όψεις Κτιρίου', en: 'Building Elevations' },
    description: { el: 'Αρχιτεκτονικές όψεις (Βόρεια, Νότια κ.λπ.)', en: 'Architectural elevations (North, South etc.)' },
    icon: 'Building',
    order: 302,
    group: 'architectural',
  },
  {
    id: 'study-arch-detail',
    purpose: 'study-arch-detail',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Αρχιτεκτονικές Λεπτομέρειες', en: 'Architectural Details' },
    description: { el: 'Κατασκευαστικές λεπτομέρειες', en: 'Construction detail drawings' },
    icon: 'Focus',
    order: 303,
    group: 'architectural',
  },
  {
    id: 'study-arch-3d',
    purpose: 'study-3d-render',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Τρισδιάστατα / Φωτορεαλισμός', en: '3D Renders / Visualizations' },
    description: { el: '3D απεικονίσεις κτιρίου', en: '3D building visualizations' },
    icon: 'Box',
    order: 304,
    group: 'architectural',
  },
  {
    id: 'study-arch-floorplan',
    purpose: 'study-floorplan',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Κάτοψη', en: 'Floor Plan' },
    description: { el: 'Αρχιτεκτονική κάτοψη ορόφου', en: 'Architectural floor plan' },
    icon: 'LayoutGrid',
    order: 310,
    group: 'architectural',
    perFloor: true,
  },
  {
    id: 'study-arch-other',
    purpose: 'study-arch-other',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Άλλο Αρχιτεκτονικό', en: 'Other Architectural' },
    description: { el: 'Λοιπό αρχιτεκτονικό σχέδιο', en: 'Other architectural drawing' },
    icon: 'File',
    order: 349,
    group: 'architectural',
    requiresCustomTitle: true,
  },

  // ========================================================================
  // STRUCTURAL / ΣΤΑΤΙΚΑ (400-449) — group: 'structural'
  // ========================================================================
  {
    id: 'study-struct-analysis',
    purpose: 'study-struct-analysis',
    domain: 'construction',
    category: 'documents',
    label: { el: 'Στατική Μελέτη (Τεύχος)', en: 'Structural Analysis Report' },
    description: { el: 'Τεύχος στατικής μελέτης / υπολογισμοί', en: 'Structural calculation report' },
    icon: 'FileBarChart',
    order: 400,
    group: 'structural',
  },
  {
    id: 'study-struct-foundation',
    purpose: 'study-struct-foundation',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Σχέδιο Θεμελίωσης', en: 'Foundation Plan' },
    description: { el: 'Ξυλότυπος θεμελίωσης', en: 'Foundation formwork plan' },
    icon: 'Layers',
    order: 401,
    group: 'structural',
  },
  {
    id: 'study-struct-reinforcement',
    purpose: 'study-reinforcement',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Σχέδιο Οπλισμού', en: 'Reinforcement Plan' },
    description: { el: 'Σχέδια σιδηρού οπλισμού', en: 'Steel reinforcement drawings' },
    icon: 'Grid3x3',
    order: 402,
    group: 'structural',
  },
  {
    id: 'study-struct-formwork',
    purpose: 'study-struct-plan',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Ξυλότυπος', en: 'Formwork Plan' },
    description: { el: 'Ξυλότυπος ορόφου', en: 'Floor formwork plan' },
    icon: 'SquareDashedBottom',
    order: 410,
    group: 'structural',
    perFloor: true,
  },
  {
    id: 'study-struct-bearing',
    purpose: 'study-bearing-plan',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Σχέδιο Φέρουσας Κατασκευής', en: 'Load-Bearing Plan' },
    description: { el: 'Φέρουσα κατασκευή ορόφου', en: 'Floor load-bearing structure plan' },
    icon: 'Building2',
    order: 411,
    group: 'structural',
    perFloor: true,
  },
  {
    id: 'study-struct-other',
    purpose: 'study-struct-other',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Άλλο Στατικό', en: 'Other Structural' },
    description: { el: 'Λοιπό στατικό σχέδιο/μελέτη', en: 'Other structural drawing/study' },
    icon: 'File',
    order: 449,
    group: 'structural',
    requiresCustomTitle: true,
  },

  // ========================================================================
  // MECHANICAL / Η/Μ (500-549) — group: 'mechanical'
  // ========================================================================
  {
    id: 'study-mep-general',
    purpose: 'study-mep-general',
    domain: 'construction',
    category: 'documents',
    label: { el: 'Η/Μ Μελέτη (Τεύχος)', en: 'MEP Study Report' },
    description: { el: 'Γενικό τεύχος Η/Μ μελέτης', en: 'General MEP study report' },
    icon: 'FileBarChart',
    order: 500,
    group: 'mechanical',
  },
  {
    id: 'study-mep-overview',
    purpose: 'study-mep-overview',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Γενικό Σχέδιο Η/Μ', en: 'MEP Overview Drawing' },
    description: { el: 'Συνολική αποτύπωση Η/Μ εγκαταστάσεων', en: 'Overall MEP installations drawing' },
    icon: 'Wrench',
    order: 501,
    group: 'mechanical',
  },
  {
    id: 'study-mep-water',
    purpose: 'study-mep-water',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Ύδρευση', en: 'Water Supply' },
    description: { el: 'Σχέδιο ύδρευσης ορόφου', en: 'Floor water supply plan' },
    icon: 'Droplets',
    order: 510,
    group: 'mechanical',
    perFloor: true,
  },
  {
    id: 'study-mep-drainage',
    purpose: 'study-mep-drainage',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Αποχέτευση', en: 'Drainage' },
    description: { el: 'Σχέδιο αποχέτευσης ορόφου', en: 'Floor drainage plan' },
    icon: 'ArrowDownToLine',
    order: 511,
    group: 'mechanical',
    perFloor: true,
  },
  {
    id: 'study-mep-heating',
    purpose: 'study-mep-heating',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Θέρμανση', en: 'Heating' },
    description: { el: 'Σχέδιο θέρμανσης ορόφου', en: 'Floor heating plan' },
    icon: 'Flame',
    order: 512,
    group: 'mechanical',
    perFloor: true,
  },
  {
    id: 'study-mep-hvac',
    purpose: 'study-mep-hvac',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Κλιματισμός / Εξαερισμός', en: 'HVAC / Ventilation' },
    description: { el: 'Σχέδιο κλιματισμού-εξαερισμού ορόφου', en: 'Floor HVAC/ventilation plan' },
    icon: 'Wind',
    order: 513,
    group: 'mechanical',
    perFloor: true,
  },
  {
    id: 'study-mep-electrical',
    purpose: 'study-mep-electrical',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Ηλεκτρολογικά', en: 'Electrical' },
    description: { el: 'Ηλεκτρολογικό σχέδιο ορόφου', en: 'Floor electrical plan' },
    icon: 'Zap',
    order: 514,
    group: 'mechanical',
    perFloor: true,
  },
  {
    id: 'study-mep-telecom',
    purpose: 'study-mep-telecom',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Τηλεπικοινωνίες / Δίκτυα', en: 'Telecom / Network' },
    description: { el: 'Τηλεφωνία, δεδομένα, δίκτυα ορόφου', en: 'Floor telecom/network plan' },
    icon: 'Wifi',
    order: 515,
    group: 'mechanical',
    perFloor: true,
  },
  {
    id: 'study-mep-other',
    purpose: 'study-mep-other',
    domain: 'construction',
    category: 'drawings',
    label: { el: 'Άλλο Η/Μ', en: 'Other MEP' },
    description: { el: 'Λοιπό ηλεκτρομηχανολογικό σχέδιο', en: 'Other MEP drawing' },
    icon: 'File',
    order: 549,
    group: 'mechanical',
    requiresCustomTitle: true,
  },

  // ========================================================================
  // ENERGY / ΕΝΕΡΓΕΙΑΚΑ (600-619) — group: 'energy'
  // ========================================================================
  {
    id: 'study-energy-mea',
    purpose: 'study-mea',
    domain: 'construction',
    category: 'documents',
    label: { el: 'ΜΕΑ / ΚΕΝΑΚ', en: 'Energy Study (KENAK)' },
    description: { el: 'Μελέτη Ενεργειακής Απόδοσης / ΚΕΝΑΚ', en: 'Energy performance study / KENAK' },
    icon: 'Zap',
    order: 600,
    group: 'energy',
  },
  {
    id: 'study-energy-certificate',
    purpose: 'study-energy-cert',
    domain: 'construction',
    category: 'documents',
    label: { el: 'Ενεργειακό Πιστοποιητικό (ΠΕΑ)', en: 'Energy Certificate (PEA)' },
    description: { el: 'Πιστοποιητικό Ενεργειακής Απόδοσης', en: 'Energy Performance Certificate' },
    icon: 'Award',
    order: 601,
    group: 'energy',
  },
  {
    id: 'study-energy-insulation',
    purpose: 'study-insulation',
    domain: 'construction',
    category: 'documents',
    label: { el: 'Μελέτη Θερμομόνωσης', en: 'Insulation Study' },
    description: { el: 'Μελέτη θερμομόνωσης κτιρίου', en: 'Building thermal insulation study' },
    icon: 'Thermometer',
    order: 602,
    group: 'energy',
  },
  {
    id: 'study-energy-other',
    purpose: 'study-energy-other',
    domain: 'construction',
    category: 'documents',
    label: { el: 'Άλλο Ενεργειακό', en: 'Other Energy' },
    description: { el: 'Λοιπό ενεργειακό έγγραφο', en: 'Other energy document' },
    icon: 'File',
    order: 619,
    group: 'energy',
    requiresCustomTitle: true,
  },

  // ========================================================================
  // SITE / ΕΡΓΟΤΑΞΙΑΚΑ (700-719) — group: 'site'
  // ========================================================================
  {
    id: 'study-site-say-fay',
    purpose: 'study-say-fay',
    domain: 'construction',
    category: 'documents',
    label: { el: 'ΣΑΥ-ΦΑΥ', en: 'Safety Plan (SAY-FAY)' },
    description: { el: 'Σχέδιο Ασφάλειας & Υγείας / Φάκελος', en: 'Health & Safety Plan / File' },
    icon: 'HardHat',
    order: 700,
    group: 'site',
  },
  {
    id: 'study-site-waste',
    purpose: 'study-waste',
    domain: 'construction',
    category: 'documents',
    label: { el: 'ΣΔΑ (Διαχείριση Αποβλήτων)', en: 'Waste Management Plan' },
    description: { el: 'Σχέδιο Διαχείρισης Αποβλήτων', en: 'Construction waste management plan' },
    icon: 'Trash2',
    order: 701,
    group: 'site',
  },
  {
    id: 'study-site-schedule',
    purpose: 'study-schedule',
    domain: 'construction',
    category: 'documents',
    label: { el: 'Χρονοδιάγραμμα Κατασκευής', en: 'Construction Schedule' },
    description: { el: 'Χρονοδιάγραμμα εργασιών (Gantt)', en: 'Construction work schedule (Gantt)' },
    icon: 'CalendarRange',
    order: 702,
    group: 'site',
  },
  {
    id: 'study-site-environmental',
    purpose: 'study-env-terms',
    domain: 'construction',
    category: 'documents',
    label: { el: 'Περιβαλλοντικοί Όροι', en: 'Environmental Terms' },
    description: { el: 'Απόφαση Έγκρισης Περιβαλλοντικών Όρων', en: 'Environmental terms approval decision' },
    icon: 'TreeDeciduous',
    order: 703,
    group: 'site',
  },
  {
    id: 'study-site-fire-safety',
    purpose: 'study-fire-safety',
    domain: 'construction',
    category: 'documents',
    label: { el: 'Μελέτη Πυρασφάλειας', en: 'Fire Safety Study' },
    description: { el: 'Μελέτη πυρασφάλειας / πυροπροστασίας', en: 'Fire protection study' },
    icon: 'Flame',
    order: 704,
    group: 'site',
  },
  {
    id: 'study-site-other',
    purpose: 'study-site-other',
    domain: 'construction',
    category: 'documents',
    label: { el: 'Άλλο Εργοταξιακό', en: 'Other Site Document' },
    description: { el: 'Λοιπό εργοταξιακό/περιβαλλοντικό', en: 'Other site/environmental document' },
    icon: 'File',
    order: 719,
    group: 'site',
    requiresCustomTitle: true,
  },
];
