import type { ConflictResponseBody } from '@/types/versioning';
import type { FloorKind } from '@/utils/floor-naming';

/**
 * Floor Firestore document (ADR-369-aware).
 *
 * ADR-369 additions (Phase A2, 2026-05-20):
 *   - kind                    : Revit-style classification
 *   - longName                : Greek canonical label
 *   - nameAutoGenerated       : true αν `name` auto-derived
 *   - longNameAutoGenerated   : true αν `longName` auto-derived
 *   - finishThickness         : mm — FFL → Top-of-Structural-Slab offset (default 80mm)
 *   - mezzanineParentNumber   : parent floor number (mezzanine only)
 *
 * Units (ADR-369 §1):
 *   - elevation, height       : METRES
 *   - finishThickness         : MILLIMETRES
 *   - number                  : signed integer (-N=basement, 0=ground, +N=standard)
 *
 * @see docs/centralized-systems/reference/adrs/ADR-369-bim-elevation-convention-revit-alignment.md §9 Q4, Q6, Q9
 */
export interface FloorDocument {
  id: string;
  number: number;
  name?: string;
  buildingId: string;
  projectId?: string;
  companyId?: string;
  height?: number | null;
  hasFloorplan?: boolean;

  // ─── ADR-369 additions ───────────────────────────────────────────────────
  kind?: FloorKind;
  longName?: string;
  nameAutoGenerated?: boolean;
  longNameAutoGenerated?: boolean;
  finishThickness?: number;
  mezzanineParentNumber?: number;

  [key: string]: unknown;
}

export type FloorsListSuccess = {
  success: true;
  floors: FloorDocument[];
  floorsByBuilding?: Record<string, FloorDocument[]>;
  stats: {
    totalFloors: number;
    buildingId?: string;
    projectId?: string;
    buildingsWithFloors?: number;
  };
  message?: string;
};

export type FloorsListError = {
  success: false;
  error: string;
  details?: string;
};

export type FloorsListResponse = FloorsListSuccess | FloorsListError;

export interface FloorCreateResponse {
  floorId: string;
}

export type FloorUpdateResponse =
  | { success: true; message: string; _v?: number }
  | { success: false; error: string; details?: string }
  | ConflictResponseBody;

export type FloorDeleteResponse =
  | { success: true; message: string }
  | { success: false; error: string; details?: string };
