import { z } from 'zod';
import { FLOOR_KIND_VALUES, type FloorKind } from '@/utils/floor-naming';

// ─── ADR-369 enum schema ─────────────────────────────────────────────────────

/** Strict enum για `FloorKind` — mirrors `FLOOR_KIND_VALUES` SSoT. */
export const FloorKindSchema = z.enum(
  FLOOR_KIND_VALUES as readonly [FloorKind, ...FloorKind[]],
);

// ─── Create / Update floor (ADR-369-aware) ───────────────────────────────────

export const CreateFloorSchema = z.object({
  number: z.number().int(),
  name: z.string().min(1).max(200),
  buildingId: z.string().min(1).max(128),
  buildingName: z.string().max(200).optional(),
  projectId: z.string().max(128).optional(),
  projectName: z.string().max(200).optional(),
  units: z.number().int().min(0).max(9999).optional(),
  elevation: z.number().min(-999).max(9999).optional(),
  height: z.number().min(0.1).max(999).optional(),

  // ADR-369 additions
  kind: FloorKindSchema,
  longName: z.string().min(1).max(200),
  nameAutoGenerated: z.boolean(),
  longNameAutoGenerated: z.boolean(),
  /** mm — finish thickness FFL → ToS (default 80 per Greek typical). */
  finishThickness: z.number().min(0).max(1000).optional(),
  /** Mezzanine only — parent standard floor number. */
  mezzanineParentNumber: z.number().int().optional(),
});

export const UpdateFloorSchema = z.object({
  floorId: z.string().min(1).max(128),
  number: z.number().int().optional(),
  name: z.string().max(200).optional(),
  elevation: z.number().min(-999).max(9999).optional(),
  height: z.number().min(0.1).max(999).optional().nullable(),
  _v: z.number().int().optional(),

  // ADR-369 additions (all optional on update)
  kind: FloorKindSchema.optional(),
  longName: z.string().max(200).optional(),
  nameAutoGenerated: z.boolean().optional(),
  longNameAutoGenerated: z.boolean().optional(),
  finishThickness: z.number().min(0).max(1000).optional(),
  mezzanineParentNumber: z.number().int().optional().nullable(),
}).passthrough();
