// -----------------------------------------------------------------------------
// Obligations Barrel - Types & Utilities
// -----------------------------------------------------------------------------
export type {
  ObligationDocument,
  ObligationSection,
  ObligationArticle,
  ObligationParagraph,
  ObligationSubsection,
  ObligationTemplate,
  Owner,
  ProjectDetails,
  SectionCategory,
  Specification,
  TableOfContentsItem,
  DragItem,
  DropResult,
  PreviewState,
  EditorState,
} from '@/types/obligations';

export {
  createNewSection,
  createNewArticle,
  createNewParagraph,
  renumberSections,
  renumberArticles,
  renumberParagraphs,
  generateTableOfContents,
  flattenDocument,
  moveSection,
  moveArticle,
  moveParagraph,
} from '@/types/obligations';

export {
  getStatusLabel,
  getStatusColor,
  getStatusIcon,
  getCategoryLabel,
  getCategoryColor,
  getCategoryIcon,
  validateObligation,
  validateSection,
  validateArticle,
  validateParagraph,
  generateObligationTitle,
  truncateText,
  getWordCount,
  getCharacterCount,
  getReadingTime,
  getTotalWordCount,
  getDocumentReadingTime,
  getContentSummary,
  formatDate,
  formatShortDate,
  formatDateTime,
  getRelativeTime,
  generateFileName,
  highlightSearchTerm,
  searchInText,
  searchInDocument,
  sortObligations,
  calculateProgress,
  calculateCompletionPercentage,
  getObligationStats,
  applyTemplate,
  stripHtmlTags,
  convertMarkdownToHtml,
  generateSectionId,
} from '@/lib/obligations-utils';
