/**
 * Unit tests — handleCreateFloor kind persistence (ADR-461 Phase B, boy-scout N.0.2)
 *
 * Before Phase B `handleCreateFloor` dropped `kind` / `longName` / the auto-naming
 * flags even though `CreateFloorSchema` validated them — so no floor ever persisted
 * its classification and special levels (foundation / stair-penthouse) were
 * indistinguishable from counted storeys. These tests pin the threading: every
 * ADR-369/461 field reaches `createEntity`'s `entitySpecificFields`.
 */

// next/server needs Edge `Request`/`Response` globals — stub it (we only assert on
// the createEntity call args, never on the NextResponse shape).
jest.mock('next/server', () => ({
  NextRequest: class {},
  NextResponse: { json: (body: unknown, init?: unknown) => ({ body, init }) },
}));

jest.mock('firebase-admin/firestore', () => ({
  FieldValue: { serverTimestamp: () => 'TS' },
}));

jest.mock('@/lib/telemetry', () => ({
  createModuleLogger: () => ({ info: jest.fn(), warn: jest.fn(), error: jest.fn(), debug: jest.fn() }),
}));

jest.mock('@/services/entity-audit.service', () => ({
  EntityAuditService: { recordChange: jest.fn().mockResolvedValue('audit_1') },
}));

jest.mock('@/lib/firestore/deletion-guard', () => ({ executeDeletion: jest.fn() }));
jest.mock('@/lib/firestore/version-check', () => ({
  withVersionCheck: jest.fn(),
  ConflictError: class ConflictError extends Error {},
}));
jest.mock('../floors.shared', () => ({
  buildFloorsQuery: jest.fn(),
  resolveFloorsListParams: jest.fn(),
  resolveTenantCompanyId: jest.fn(),
  sortFloors: jest.fn(),
}));
jest.mock('../floor-stack-reconcile.service', () => ({ reconcileFloorStackAfterEdit: jest.fn() }));

const createEntityMock = jest.fn().mockResolvedValue({ id: 'floor_new_1' });
jest.mock('@/lib/firestore/entity-creation.service', () => ({
  createEntity: (...args: unknown[]) => createEntityMock(...args),
}));

// Minimal Firestore Admin double: building lookup + empty duplicate-number check.
const getAdminFirestoreMock = jest.fn();
jest.mock('@/lib/firebaseAdmin', () => ({
  getAdminFirestore: () => getAdminFirestoreMock(),
}));

import { handleCreateFloor } from '../floors.handlers';
import type { AuthContext } from '@/lib/auth';

function makeDb() {
  const duplicateQuery = {
    where: () => duplicateQuery,
    select: () => duplicateQuery,
    limit: () => duplicateQuery,
    get: async () => ({ empty: true }),
  };
  return {
    collection: (name: string) => ({
      doc: () => ({
        get: async () => ({ data: () => (name.includes('building') ? { name: 'Κτήριο Α' } : {}) }),
      }),
      where: () => duplicateQuery,
    }),
  };
}

function makeRequest(body: Record<string, unknown>) {
  return { json: async () => body } as unknown as Parameters<typeof handleCreateFloor>[0];
}

const ctx = { uid: 'u1', companyId: 'co_1', globalRole: 'user', email: 'a@b.gr' } as unknown as AuthContext;

const baseBody = {
  number: 0,
  name: 'Ισόγειο',
  buildingId: 'bldg_1',
  kind: 'ground',
  longName: 'Ισόγειο',
  nameAutoGenerated: false,
  longNameAutoGenerated: true,
  elevation: 0,
  height: 3,
};

beforeEach(() => {
  createEntityMock.mockClear();
  getAdminFirestoreMock.mockReturnValue(makeDb());
});

describe('handleCreateFloor — ADR-461 kind persistence', () => {
  it('threads kind + auto-naming flags into entitySpecificFields', async () => {
    await handleCreateFloor(makeRequest(baseBody), ctx);

    expect(createEntityMock).toHaveBeenCalledTimes(1);
    const fields = createEntityMock.mock.calls[0][1].entitySpecificFields as Record<string, unknown>;
    expect(fields.kind).toBe('ground');
    expect(fields.longName).toBe('Ισόγειο');
    expect(fields.nameAutoGenerated).toBe(false);
    expect(fields.longNameAutoGenerated).toBe(true);
  });

  it('persists the foundation special level kind', async () => {
    await handleCreateFloor(
      makeRequest({ ...baseBody, number: -1, name: 'F', kind: 'foundation', longName: 'Θεμελίωση', nameAutoGenerated: true }),
      ctx,
    );
    const fields = createEntityMock.mock.calls[0][1].entitySpecificFields as Record<string, unknown>;
    expect(fields.kind).toBe('foundation');
    expect(fields.longName).toBe('Θεμελίωση');
  });

  it('persists the stair-penthouse special level kind', async () => {
    await handleCreateFloor(
      makeRequest({ ...baseBody, number: 3, name: 'SP', kind: 'stair-penthouse', longName: 'Απόληξη Κλιμακοστασίου', nameAutoGenerated: true }),
      ctx,
    );
    const fields = createEntityMock.mock.calls[0][1].entitySpecificFields as Record<string, unknown>;
    expect(fields.kind).toBe('stair-penthouse');
    expect(fields.longName).toBe('Απόληξη Κλιμακοστασίου');
  });

  it('forwards finishThickness + mezzanineParentNumber only when provided', async () => {
    await handleCreateFloor(
      makeRequest({ ...baseBody, number: 2, kind: 'mezzanine', mezzanineParentNumber: 1, finishThickness: 80 }),
      ctx,
    );
    const fields = createEntityMock.mock.calls[0][1].entitySpecificFields as Record<string, unknown>;
    expect(fields.finishThickness).toBe(80);
    expect(fields.mezzanineParentNumber).toBe(1);
  });

  it('omits finishThickness / mezzanineParentNumber when absent (no undefined writes)', async () => {
    await handleCreateFloor(makeRequest(baseBody), ctx);
    const fields = createEntityMock.mock.calls[0][1].entitySpecificFields as Record<string, unknown>;
    expect('finishThickness' in fields).toBe(false);
    expect('mezzanineParentNumber' in fields).toBe(false);
  });
});
