/**
 * Unit tests — handleCreateFloor kind persistence (ADR-461 Phase B, boy-scout N.0.2)
 *
 * Before Phase B `handleCreateFloor` dropped `kind` / `longName` / the auto-naming
 * flags even though `CreateFloorSchema` validated them — so no floor ever persisted
 * its classification and special levels (foundation / stair-penthouse) were
 * indistinguishable from counted storeys. These tests pin the threading: every
 * ADR-369/461 field reaches `createEntity`'s `entitySpecificFields`.
 */

// next/server needs Edge `Request`/`Response` globals — stub it (we only assert on
// the createEntity call args, never on the NextResponse shape).
jest.mock('next/server', () => ({
  NextRequest: class {},
  NextResponse: { json: (body: unknown, init?: unknown) => ({ body, init }) },
}));

jest.mock('firebase-admin/firestore', () => ({
  FieldValue: { serverTimestamp: () => 'TS' },
}));

jest.mock('@/lib/telemetry', () => ({
  createModuleLogger: () => ({ info: jest.fn(), warn: jest.fn(), error: jest.fn(), debug: jest.fn() }),
}));

jest.mock('@/services/entity-audit.service', () => ({
  EntityAuditService: { recordChange: jest.fn().mockResolvedValue('audit_1') },
}));

jest.mock('@/lib/firestore/deletion-guard', () => ({ executeDeletion: jest.fn() }));
jest.mock('@/lib/firestore/version-check', () => ({
  withVersionCheck: jest.fn(),
  ConflictError: class ConflictError extends Error {},
}));
jest.mock('../floors.shared', () => ({
  buildFloorsQuery: jest.fn(),
  resolveFloorsListParams: jest.fn(),
  sortFloors: jest.fn(),
}));
jest.mock('../floor-stack-reconcile.service', () => ({
  reconcileFloorStackAfterEdit: jest.fn(),
  // ADR-461 satellite placement — called after every successful create. The
  // handler wraps it in try/catch, so a missing double failed silently as a
  // logged warning instead of a test failure.
  reconcileSpecialLevelPlacement: jest.fn(),
}));

const createEntityMock = jest.fn().mockResolvedValue({ id: 'floor_new_1' });
jest.mock('@/lib/firestore/entity-creation.service', () => ({
  createEntity: (...args: unknown[]) => createEntityMock(...args),
}));

// Minimal Firestore Admin double: building lookup + the ADR-461 sibling scan.
const getAdminFirestoreMock = jest.fn();
jest.mock('@/lib/firebaseAdmin', () => ({
  getAdminFirestore: () => getAdminFirestoreMock(),
}));

import { handleCreateFloor } from '../floors.handlers';
import type { AuthContext } from '@/lib/auth';

/** A floor already present in the building, as the sibling scan sees it. */
interface SiblingRow {
  number: number;
  kind?: string;
}

/**
 * @param siblings floors the building already holds — drives the ADR-461
 *                 kind-aware uniqueness decision the handler makes in memory
 */
function makeDb(siblings: SiblingRow[] = []) {
  const floorsQuery = {
    where: () => floorsQuery,
    select: () => floorsQuery,
    limit: () => floorsQuery,
    get: async () => ({
      empty: siblings.length === 0,
      docs: siblings.map((row) => ({ data: () => row })),
    }),
  };
  return {
    collection: (name: string) => ({
      doc: () => ({
        exists: true,
        get: async () => ({
          exists: true,
          data: () => (name.includes('building') ? { name: 'Κτήριο Α' } : {}),
        }),
      }),
      where: () => floorsQuery,
    }),
  };
}

function makeRequest(body: Record<string, unknown>) {
  return { json: async () => body } as unknown as Parameters<typeof handleCreateFloor>[0];
}

const ctx = { uid: 'u1', companyId: 'co_1', globalRole: 'user', email: 'a@b.gr' } as unknown as AuthContext;

const baseBody = {
  number: 0,
  name: 'Ισόγειο',
  buildingId: 'bldg_1',
  kind: 'ground',
  longName: 'Ισόγειο',
  nameAutoGenerated: false,
  longNameAutoGenerated: true,
  elevation: 0,
  height: 3,
};

beforeEach(() => {
  createEntityMock.mockClear();
  getAdminFirestoreMock.mockReturnValue(makeDb());
});

describe('handleCreateFloor — ADR-461 kind persistence', () => {
  it('threads kind + auto-naming flags into entitySpecificFields', async () => {
    await handleCreateFloor(makeRequest(baseBody), ctx);

    expect(createEntityMock).toHaveBeenCalledTimes(1);
    const fields = createEntityMock.mock.calls[0][1].entitySpecificFields as Record<string, unknown>;
    expect(fields.kind).toBe('ground');
    expect(fields.longName).toBe('Ισόγειο');
    expect(fields.nameAutoGenerated).toBe(false);
    expect(fields.longNameAutoGenerated).toBe(true);
  });

  it('persists the foundation special level kind', async () => {
    await handleCreateFloor(
      makeRequest({ ...baseBody, number: -1, name: 'F', kind: 'foundation', longName: 'Θεμελίωση', nameAutoGenerated: true }),
      ctx,
    );
    const fields = createEntityMock.mock.calls[0][1].entitySpecificFields as Record<string, unknown>;
    expect(fields.kind).toBe('foundation');
    expect(fields.longName).toBe('Θεμελίωση');
  });

  it('persists the stair-penthouse special level kind', async () => {
    await handleCreateFloor(
      makeRequest({ ...baseBody, number: 3, name: 'SP', kind: 'stair-penthouse', longName: 'Απόληξη Κλιμακοστασίου', nameAutoGenerated: true }),
      ctx,
    );
    const fields = createEntityMock.mock.calls[0][1].entitySpecificFields as Record<string, unknown>;
    expect(fields.kind).toBe('stair-penthouse');
    expect(fields.longName).toBe('Απόληξη Κλιμακοστασίου');
  });

  it('forwards finishThickness + mezzanineParentNumber only when provided', async () => {
    await handleCreateFloor(
      makeRequest({ ...baseBody, number: 2, kind: 'mezzanine', mezzanineParentNumber: 1, finishThickness: 80 }),
      ctx,
    );
    const fields = createEntityMock.mock.calls[0][1].entitySpecificFields as Record<string, unknown>;
    expect(fields.finishThickness).toBe(80);
    expect(fields.mezzanineParentNumber).toBe(1);
  });

  it('omits finishThickness / mezzanineParentNumber when absent (no undefined writes)', async () => {
    await handleCreateFloor(makeRequest(baseBody), ctx);
    const fields = createEntityMock.mock.calls[0][1].entitySpecificFields as Record<string, unknown>;
    expect('finishThickness' in fields).toBe(false);
    expect('mezzanineParentNumber' in fields).toBe(false);
  });
});

/**
 * ADR-461 kind-aware uniqueness — the rule that broke this file's Firestore
 * double when it landed (`5ab8033d`) and that nothing pinned until now: the
 * suite failed on `siblingsSnap.docs` being undefined, so the rule itself shipped
 * unverified. Counted storeys must keep unique numbers among themselves; a
 * special level may share a number with one, but there may be only ONE per kind.
 */
describe('handleCreateFloor — ADR-461 kind-aware uniqueness', () => {
  async function expectRejection(body: Record<string, unknown>): Promise<{ statusCode?: number; message: string }> {
    try {
      await handleCreateFloor(makeRequest(body), ctx);
      throw new Error('expected the create to be rejected');
    } catch (error) {
      const typed = error as { statusCode?: number; message: string };
      if (typed.message === 'expected the create to be rejected') throw error;
      return typed;
    }
  }

  it('rejects a counted storey whose number is already taken by a counted storey', async () => {
    getAdminFirestoreMock.mockReturnValue(makeDb([{ number: 0, kind: 'ground' }]));

    const error = await expectRejection(baseBody);

    expect(error.statusCode).toBe(409);
    expect(error.message).toContain('already exists in building');
    expect(createEntityMock).not.toHaveBeenCalled();
  });

  it('treats a legacy floor with NO kind as a counted storey', async () => {
    // Pre-ADR-461 documents carry no `kind`; they must still block a clashing number.
    getAdminFirestoreMock.mockReturnValue(makeDb([{ number: 0 }]));

    expect((await expectRejection(baseBody)).statusCode).toBe(409);
  });

  it('rejects a SECOND special level of the same kind', async () => {
    getAdminFirestoreMock.mockReturnValue(makeDb([{ number: -1, kind: 'foundation' }]));

    const error = await expectRejection({ ...baseBody, number: -5, kind: 'foundation' });

    expect(error.statusCode).toBe(409);
    expect(error.message).toContain('special level already exists');
  });

  it('ALLOWS a special level to share a number with a counted storey', async () => {
    // The Revit-true case: a foundation auto-numbered −1 co-existing with a
    // manually created basement −1. A number-only check would have refused this.
    getAdminFirestoreMock.mockReturnValue(makeDb([{ number: -1, kind: 'basement' }]));

    await handleCreateFloor(makeRequest({ ...baseBody, number: -1, kind: 'foundation' }), ctx);

    expect(createEntityMock).toHaveBeenCalledTimes(1);
  });

  it('ALLOWS a counted storey whose number is only taken by a special level', async () => {
    getAdminFirestoreMock.mockReturnValue(makeDb([{ number: 3, kind: 'stair-penthouse' }]));

    await handleCreateFloor(makeRequest({ ...baseBody, number: 3, kind: 'standard' }), ctx);

    expect(createEntityMock).toHaveBeenCalledTimes(1);
  });
});
