/**
 * ADR-684 — Contextual ribbon tab for the generic-solid tool (παραμετρικά στερεά).
 *
 * Trigger: `generic-solid-tool-active` (dispatched from `app/resolve-tool-active-
 * trigger.ts` when `activeTool === 'generic-solid'` — the TOOL-active pattern,
 * mirror of the furniture tab). Lets the user pick WHICH primitive to place +
 * tune its per-shape dimensions + rotation / elevation before clicking, bound live
 * to `genericSolidToolBridgeStore` via `useRibbonGenericSolidBridge`.
 *
 * The 8 per-shape dimension panels are GENERATED by a loop over
 * `GENERIC_SOLID_SHAPE_KINDS` × `GENERIC_SOLID_SHAPE_DIMENSIONS` (never 8 hand-
 * written near-identical numeric blocks — N.18 / gotcha §3.6). Each shape's panel
 * carries a `visibilityKey`; the bridge shows only the selected shape's panel.
 *
 * @see docs/centralized-systems/reference/adrs/ADR-684-generic-solid-primitive-entity.md
 * @see ./contextual-furniture-tab.ts — the closest sibling (tool-active «pick → place»)
 */

import type { RibbonButton, RibbonTab } from '../types/ribbon-types';
import {
  GENERIC_SOLID_SHAPE_KINDS,
  GENERIC_SOLID_STRUCTURAL_ROLES,
  type GenericSolidShapeKind,
} from '../../../bim/entities/generic-solid/generic-solid-types';
import {
  GENERIC_SOLID_SHAPE_DIMENSIONS,
  type GenericSolidDimensionDescriptor,
} from '../../../bim/entities/generic-solid/generic-solid-shape-defaults';
import {
  GENERIC_SOLID_RIBBON_KEYS,
  GENERIC_SOLID_PANEL_KEY_BY_KIND,
} from '../hooks/bridge/generic-solid-command-keys';
import { literalNumberOptions } from './ribbon-numeric-options';
import { singleRowPanel } from './ribbon-panel-builders';

export const GENERIC_SOLID_CONTEXTUAL_TRIGGER = 'generic-solid-tool-active';

// ─── Combobox option ladders ───────────────────────────────────────────────────

const DIMENSION_MM_OPTIONS = literalNumberOptions([
  50, 100, 150, 200, 250, 300, 400, 500, 750, 1000, 1500, 2000,
]);
const SIDES_OPTIONS = literalNumberOptions([3, 4, 5, 6, 8, 10, 12]);
const ROTATION_DEG_OPTIONS = literalNumberOptions([0, 45, 90, 135, 180, 225, 270, 315]);
const ELEVATION_MM_OPTIONS = literalNumberOptions([0, 100, 250, 500, 1000, 1500, 2000]);

/** Shape selector options — labels routed through i18n per shape kind. */
const SHAPE_KIND_OPTIONS = GENERIC_SOLID_SHAPE_KINDS.map((kind) => ({
  value: kind,
  labelKey: `ribbon.commands.genericSolidEditor.shape.${kind}`,
  isLiteralLabel: false,
}));

/** ADR-684 Φ4-C — structural/decorative classification options (§4.3). */
const STRUCTURAL_ROLE_OPTIONS = GENERIC_SOLID_STRUCTURAL_ROLES.map((role) => ({
  value: role,
  labelKey: `ribbon.commands.genericSolidEditor.structuralRole.${role}`,
  isLiteralLabel: false,
}));

// ─── Button builders ───────────────────────────────────────────────────────────

/** A numeric-editable combobox bound to one shape dimension. */
function dimensionButton(
  kind: GenericSolidShapeKind,
  dim: GenericSolidDimensionDescriptor,
): RibbonButton {
  return {
    type: 'combobox',
    size: 'small',
    command: {
      id: `genericSolid.${kind}.${dim.field}`,
      labelKey: dim.labelKey,
      commandKey: GENERIC_SOLID_RIBBON_KEYS.dim(dim.field),
      comboboxWidthPx: 80,
      options: dim.quantityKind === 'count' ? SIDES_OPTIONS : DIMENSION_MM_OPTIONS,
      numericInput: { quantityKind: dim.quantityKind },
    },
  };
}

const SHAPE_SELECTOR_BUTTON: RibbonButton = {
  type: 'combobox',
  size: 'small',
  command: {
    id: 'genericSolid.shape',
    labelKey: 'ribbon.commands.genericSolidEditor.shapeLabel',
    commandKey: GENERIC_SOLID_RIBBON_KEYS.stringParams.shapeKind,
    comboboxWidthPx: 160,
    options: SHAPE_KIND_OPTIONS,
  },
};

/** ADR-684 Φ4-C — δομικό vs διακοσμητικό (ταξινόμηση/BOQ §4.3, Revit «Structural» toggle). */
const STRUCTURAL_ROLE_BUTTON: RibbonButton = {
  type: 'combobox',
  size: 'small',
  command: {
    id: 'genericSolid.structuralRole',
    labelKey: 'ribbon.commands.genericSolidEditor.structuralRoleLabel',
    commandKey: GENERIC_SOLID_RIBBON_KEYS.stringParams.structuralRole,
    comboboxWidthPx: 140,
    options: STRUCTURAL_ROLE_OPTIONS,
  },
};

const PLACEMENT_BUTTONS: readonly RibbonButton[] = [
  {
    type: 'combobox',
    size: 'small',
    command: {
      id: 'genericSolid.rotation',
      labelKey: 'ribbon.commands.genericSolidEditor.rotation',
      commandKey: GENERIC_SOLID_RIBBON_KEYS.params.rotation,
      comboboxWidthPx: 80,
      options: ROTATION_DEG_OPTIONS,
      numericInput: { quantityKind: 'angle' },
    },
  },
  {
    type: 'combobox',
    size: 'small',
    command: {
      id: 'genericSolid.mountingElevation',
      labelKey: 'ribbon.commands.genericSolidEditor.mountingElevation',
      commandKey: GENERIC_SOLID_RIBBON_KEYS.params.mountingElevation,
      comboboxWidthPx: 90,
      options: ELEVATION_MM_OPTIONS,
      numericInput: { quantityKind: 'length' },
    },
  },
];

// ─── Per-shape dimension panels (generated) ────────────────────────────────────

const SHAPE_DIMENSION_PANELS = GENERIC_SOLID_SHAPE_KINDS.map((kind) =>
  singleRowPanel(
    `generic-solid-dims-${kind}`,
    `ribbon.panels.genericSolidDimensions.${kind}`,
    GENERIC_SOLID_SHAPE_DIMENSIONS[kind].map((dim) => dimensionButton(kind, dim)),
    { visibilityKey: GENERIC_SOLID_PANEL_KEY_BY_KIND[kind] },
  ),
);

// ─── Tab definition ──────────────────────────────────────────────────────────

export const CONTEXTUAL_GENERIC_SOLID_TAB: RibbonTab = {
  id: 'generic-solid-editor',
  labelKey: 'ribbon.tabs.genericSolidProperties',
  isContextual: true,
  contextualTrigger: GENERIC_SOLID_CONTEXTUAL_TRIGGER,
  panels: [
    singleRowPanel('generic-solid-shape', 'ribbon.panels.genericSolidShape', [SHAPE_SELECTOR_BUTTON]),
    ...SHAPE_DIMENSION_PANELS,
    singleRowPanel('generic-solid-placement', 'ribbon.panels.genericSolidPlacement', PLACEMENT_BUTTONS),
    // ADR-684 Φ4-C — ταξινόμηση δομικό/διακοσμητικό (§4.3, οδηγεί την προμέτρηση BOQ).
    singleRowPanel('generic-solid-classification', 'ribbon.panels.genericSolidClassification', [STRUCTURAL_ROLE_BUTTON]),
  ],
};
