/**
 * @fileoverview **ΤΑ ΚΛΕΙΔΙΑ ΤΗΣ ΟΘΟΝΗΣ ΤΟΠΟΘΕΤΗΣΗΣ** — `spatial-tour:editor.*` (ADR-884 Φ2δ · §4.10).
 * @related `../viewer/tour-viewer-labels.ts` (τα κλειδιά του θεατή — ίδιο σκεπτικό χωριστού αντικειμένου) ·
 *   `../spatial-tour-labels.ts` (`TOUR_REFUSAL_KEY` — οι αρνήσεις του γράφου) · `tour-shape-labels.ts` (οι αρνήσεις και τα
 *   μηνύματα των σχημάτων χώρων — διαμέριση, Γ3γ-1)
 * @module components/spatial-tour/editor/tour-editor-labels
 *
 * 🔑 **Χωριστό αντικείμενο**: η οθόνη φορτώνεται πίσω από `next/dynamic` μόνο για τον υπεύθυνο — οι λέξεις της δεν
 *   ταξιδεύουν στο slice της σελίδας του ακινήτου (ADR-744 §15).
 */

export const TOUR_EDITOR_KEYS = {
  open: 'spatial-tour:editor.open',
  title: 'spatial-tour:editor.title',
  description: 'spatial-tour:editor.description',
  inbox: 'spatial-tour:editor.inbox',
  inboxEmpty: 'spatial-tour:editor.inboxEmpty',
  baking: 'spatial-tour:editor.baking',
  failed: 'spatial-tour:editor.failed',
  points: 'spatial-tour:editor.points',
  noPoints: 'spatial-tour:editor.noPoints',
  missingArrows: 'spatial-tour:editor.missingArrows',
  selectPrompt: 'spatial-tour:editor.selectPrompt',
  notReadyHint: 'spatial-tour:editor.notReadyHint',
  failedHint: 'spatial-tour:editor.failedHint',
  placeHeading: 'spatial-tour:editor.placeHeading',
  floor: 'spatial-tour:editor.floor',
  newFloor: 'spatial-tour:editor.newFloor',
  mode: 'spatial-tour:editor.mode',
  modeNew: 'spatial-tour:editor.modeNew',
  modeNextTo: 'spatial-tour:editor.modeNextTo',
  modeSameAs: 'spatial-tour:editor.modeSameAs',
  neighbour: 'spatial-tour:editor.neighbour',
  place: 'spatial-tour:editor.place',
  placed: 'spatial-tour:editor.placed',
  remove: 'spatial-tour:editor.remove',
  removeTitle: 'spatial-tour:editor.removeTitle',
  removeLast: 'spatial-tour:editor.removeLast',
  removeOne: 'spatial-tour:editor.removeOne',
  removed: 'spatial-tour:editor.removed',
  arrows: 'spatial-tour:editor.arrows',
  arrowsHint: 'spatial-tour:editor.arrowsHint',
  arrowHere: 'spatial-tour:editor.arrowHere',
  arrowHereFor: 'spatial-tour:editor.arrowHereFor',
  dragArrow: 'spatial-tour:editor.dragArrow',
  arrowMissing: 'spatial-tour:editor.arrowMissing',
  arrowSaved: 'spatial-tour:editor.arrowSaved',
  otherPoints: 'spatial-tour:editor.otherPoints',
  unlink: 'spatial-tour:editor.unlink',
  unlinked: 'spatial-tour:editor.unlinked',
  undo: 'spatial-tour:editor.undo',
  saveFailed: 'spatial-tour:editor.saveFailed',
  roomTitle: 'spatial-tour:editor.roomTitle',
  roomType: 'spatial-tour:editor.roomType',
  roomTypePlaceholder: 'spatial-tour:editor.roomTypePlaceholder',
  roomAlsoType: 'spatial-tour:editor.roomAlsoType',
  roomAddType: 'spatial-tour:editor.roomAddType',
  roomRemoveType: 'spatial-tour:editor.roomRemoveType',
  roomLabel: 'spatial-tour:editor.roomLabel',
  roomLabelHint: 'spatial-tour:editor.roomLabelHint',
  roomPreview: 'spatial-tour:editor.roomPreview',
  roomSave: 'spatial-tour:editor.roomSave',
  roomClear: 'spatial-tour:editor.roomClear',
  roomSaved: 'spatial-tour:editor.roomSaved',
  // ── Η κάτοψη (Φ2στ-β · §4.13) ──
  planTitle: 'spatial-tour:editor.planTitle',
  planHint: 'spatial-tour:editor.planHint',
  planNone: 'spatial-tour:editor.planNone',
  planLoadFailed: 'spatial-tour:editor.planLoadFailed',
  planSource: 'spatial-tour:editor.planSource',
  planSourcePlaceholder: 'spatial-tour:editor.planSourcePlaceholder',
  planSourceEngineer: 'spatial-tour:editor.planSourceEngineer',
  planSourceUserSketch: 'spatial-tour:editor.planSourceUserSketch',
  planUse: 'spatial-tour:editor.planUse',
  planChange: 'spatial-tour:editor.planChange',
  planChangeWarning: 'spatial-tour:editor.planChangeWarning',
  planCancel: 'spatial-tour:editor.planCancel',
  planChosen: 'spatial-tour:editor.planChosen',
  planScaleMissing: 'spatial-tour:editor.planScaleMissing',
  planScaleSet: 'spatial-tour:editor.planScaleSet',
  planScaleChange: 'spatial-tour:editor.planScaleChange',
  planScaleValue: 'spatial-tour:editor.planScaleValue',
  planCalibrated: 'spatial-tour:editor.planCalibrated',
  planMap: 'spatial-tour:editor.planMap',
  planPlaceHint: 'spatial-tour:editor.planPlaceHint',
  planRemovePoint: 'spatial-tour:editor.planRemovePoint',
  pointPositioned: 'spatial-tour:editor.pointPositioned',
  planDirection: 'spatial-tour:editor.planDirection',
  planDirectionHint: 'spatial-tour:editor.planDirectionHint',
  planDirectionValue: 'spatial-tour:editor.planDirectionValue',
  planSuggest: 'spatial-tour:editor.planSuggest',
  planSuggestHint: 'spatial-tour:editor.planSuggestHint',
  planSuggestSpread: 'spatial-tour:editor.planSuggestSpread',
  pointOriented: 'spatial-tour:editor.pointOriented',
  // Τα σχήματα χώρων (Γ3β) έχουν δικό τους αρχείο: `tour-shape-labels.ts` (CHECK 3.34, Γ3γ-1).
} as const;
